PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
DELETE {
    chc:BoundVolume emf:isSearchable "false"^^xsd:boolean.
    chc:DecorativeArt emf:isSearchable "false"^^xsd:boolean.
    chc:Drawing emf:isSearchable "false"^^xsd:boolean.
    chc:Ephemera emf:isSearchable "false"^^xsd:boolean.
    chc:Frame emf:isSearchable "false"^^xsd:boolean.
    chc:MediaArt emf:isSearchable "false"^^xsd:boolean.
    chc:Painting emf:isSearchable "false"^^xsd:boolean.
    chc:Sample emf:isSearchable "false"^^xsd:boolean.
    chc:Photograph emf:isSearchable "false"^^xsd:boolean.
    chc:Portfolio emf:isSearchable "false"^^xsd:boolean.
    chc:Print emf:isSearchable "false"^^xsd:boolean.
    chc:Sculpture emf:isSearchable "false"^^xsd:boolean.
    chc:TechnicalMaterial emf:isSearchable "false"^^xsd:boolean.
    chc:ConservationActivity emf:isSearchable "false"^^xsd:boolean.
}
INSERT {
    GRAPH <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation/NGA> {
        chc:BoundVolume emf:isSearchable "true"^^xsd:boolean.
        chc:DecorativeArt emf:isSearchable "true"^^xsd:boolean.
        chc:Drawing emf:isSearchable "true"^^xsd:boolean.
        chc:Ephemera emf:isSearchable "true"^^xsd:boolean.
        chc:Frame emf:isSearchable "true"^^xsd:boolean.
        chc:MediaArt emf:isSearchable "true"^^xsd:boolean.
        chc:Painting emf:isSearchable "true"^^xsd:boolean.
        chc:Sample emf:isSearchable "true"^^xsd:boolean.
        chc:Photograph emf:isSearchable "true"^^xsd:boolean.
        chc:Portfolio emf:isSearchable "true"^^xsd:boolean.
        chc:Print emf:isSearchable "true"^^xsd:boolean.
        chc:Sculpture emf:isSearchable "true"^^xsd:boolean.
        chc:TechnicalMaterial emf:isSearchable "true"^^xsd:boolean.
        chc:ConservationActivity emf:isSearchable "true"^^xsd:boolean.
    }
}
WHERE {
    
}