PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
delete {
     	emf:DataImportSource emf:isUploadable "true"^^xsd:boolean.
        emf:DataImportSource emf:isSearchable "true"^^xsd:boolean.
        emf:DataImportSource emf:isPartOfObjectLibrary "true"^^xsd:boolean.
        emf:DataImportReport emf:isSearchable "true"^^xsd:boolean.
        emf:DataImportReport emf:isPartOfObjectLibrary "true"^^xsd:boolean.
}insert{
	graph  <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    	emf:DataImportSource emf:isUploadable "false"^^xsd:boolean.
        emf:DataImportSource emf:isSearchable "false"^^xsd:boolean.
        emf:DataImportSource emf:isPartOfObjectLibrary "false"^^xsd:boolean.
        emf:DataImportReport emf:isSearchable "false"^^xsd:boolean.
        emf:DataImportReport emf:isPartOfObjectLibrary "false"^^xsd:boolean.
    }
}
where{
    
}