PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
DELETE {
    emf:BusinessProcess emf:isSearchable "true"^^xsd:boolean.
    emf:BusinessProcessTask emf:isSearchable "true"^^xsd:boolean.
    emf:DomainUser emf:isSearchable "true"^^xsd:boolean.
}
INSERT {
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:BusinessProcess emf:isSearchable "false"^^xsd:boolean.
        emf:BusinessProcessTask emf:isSearchable "false"^^xsd:boolean.
        emf:DomainUser emf:isSearchable "false"^^xsd:boolean.
    }
}
WHERE {
}