PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
delete {
    emf:hasChild emf:isSearchable "true"^^xsd:boolean.
    ptop:partOf emf:isSearchable "true"^^xsd:boolean.
    emf:publishedBy emf:isSearchable "true"^^xsd:boolean.
}insert{
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:hasChild emf:isSearchable "false"^^xsd:boolean.
        ptop:partOf emf:isSearchable "false"^^xsd:boolean.
        emf:publishedBy emf:isSearchable "false"^^xsd:boolean.
    }
}
where{
}