PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
delete {
    emf:isReporterOf rdfs:label "Is Reporter Of"@en.
    emf:hasReporter rdfs:label "Has Reporter"@en.
}insert{
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:isReporterOf rdfs:label "is reporter of"@en.
        emf:hasReporter rdfs:label "has reporter"@en.
    }
}
where{
}