PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
delete {
    chc:ConservationActivity emf:classCategory "objectinstance".
}
insert{
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        chc:ConservationActivity emf:classCategory "caseinstance".
    }
}where{
}