PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
DELETE {
    emf:hasChild emf:isSearchable "false"^^xsd:boolean.
    ptop:partOf emf:isSearchable "false"^^xsd:boolean.
}
INSERT {
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:hasChild emf:isSearchable "true"^^xsd:boolean.
        ptop:partOf emf:isSearchable "true"^^xsd:boolean.
    }
}
WHERE {
}