select ?class (group_concat(distinct ?data ; separator = "\n ") AS ?superClassesHierarchy)
	{
		?class rdfs:subClassOf ?class1 .
		?class1 rdfs:label ?label .
		?class rdfs:label ?classLabel .
		bind(concat("\"", ?label, "\" <|-- \"", ?classLabel, "\"") as ?data) .
		filter (?class != ?class1)
	}
	group by ?class