PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

insert {
?instance emf:uri ?uri .
} where {
{?instance a ptop:Object .} UNION {?instance a ptop:Happening .}
?instance a ?instanceType .
filter(not exists{?instance emf:uri ?instanceUri}) .
bind(str(?instance) as ?uri) .
}