import {Inject, Injectable} from 'app/app';
import {RestClient} from 'services/rest-client';
import {PromiseAdapter} from 'adapters/angular/promise-adapter';

@Injectable()
@Inject(RestClient, PromiseAdapter)
export class LabelRestService {
  constructor(restClient, promiseAdapter) {
    this.restClient = restClient;
    this.promiseAdapter = promiseAdapter;
  }

  getLabels(language) {
    return this.promiseAdapter.promise((resolve) => {
      var data = {
        en: {
          'chart.bar.chart': 'Bar chart',
          'chart.line.chart': 'Line chart',
          'chart.pie.chart': 'Pie chart',
          'chart.select.type': 'Select chart type',
          'chart.total.results': 'Total results:',
          'chart.view.widget.name': 'Chart view widget',
          'company.name': 'Sirma Platform',
          'breadcrumb.home': 'Home',
          'breadcrumb.dashboard': 'Dashboard',
          'top.header.title': 'User Dashboard',
          'context.current.object': 'Current object',
          'dialog.header.confirm': 'Confirm',
          'dialog.header.select.context': 'Select context',
          'dialog.header.error': 'Error!',
          'dialog.header.notification': 'Notification',
          'dialog.button.cancel': 'Cancel',
          'dialog.button.close': 'Close',
          'dialog.button.confirm': 'Confirm',
          'dialog.button.no': 'No',
          'dialog.button.ok': 'Ok',
          'dialog.button.yes': 'Yes',
          'dialog.button.upload': 'Upload',
          'dialog.button.save': 'Save',
          'dialog.button.upload.all': 'Upload All',
          'dialog.button.importfile': 'Import file',
          'dialog.button.validatefile': 'Validate file',
          'idoc.clone.header': 'Clone',
          'idoc.template.button.primary': 'Primary template',
          'idoc.template.create': 'Create template',
          'idoc.template.status.duplication': 'A template with this name already exists. Please change the name of the template.',
          'idoc.template.status.success': ' is saved successfully.',
          'idoc.template.title': 'Template title',
          'idoc.template.title.placeholder': 'Enter template title...',
          'idoc.template.type': 'Object type for the template',
          'idoc.template.purpose': 'Template purpose',
          'idoc.template.creatable': 'Creatable content',
          'idoc.template.uploadable': 'Uploadable content',
          'idoc.permissions.save.permissions': 'Save Permissions',
          'idoc.permissions.cancel.save': 'Cancel',
          'idoc.permissions.add.user': 'Add User/Group',
          'idoc.permissions.user': 'User/Group',
          'idoc.permissions.active': 'Active Permissions',
          'idoc.permissions.special': 'Special Permissions',
          'idoc.permissions.parent': 'Inherited Parent Permissions',
          'idoc.permissions.library': 'Inherited Library Permissions',
          'idoc.permissions.management': 'Management Permissions',
          'idoc.permissions.edit.permissions': 'Edit Permissions',
          'idoc.permissions.manage.inheritance': 'Manage inheritance for new instances:',
          'idoc.permissions.inherit.parent': 'Inherit parent permissions',
          'idoc.permissions.inherit.library': 'Inherit library permissions',
          'idoc.permissions.restore.children': 'Restore children permissions',
          'idoc.permissions.restore.children.confirmation': 'All special permissions of the children objects will be removed! The action is non-reversible! Are you sure that you want to continue?',
          'idoc.permissions.restore.children.done': 'The permissions are successfully restored.',
          'comments.action.edit': 'Edit',
          'comments.action.delete': 'Delete',
          'comments.action.delete.confirm': 'Are you sure you want to delete the comment?',
          'comments.action.reply': 'Reply',
          'comments.action.filter': 'Filter comments',
          'comments.toolbar.button.addcomment': 'Comment',
          'comments.toolbar.button.filter': 'Filter',
          'comments.filter.by.autor': 'Comment Author',
          'comments.filter.by.keywords': 'Search by keywords inside comments/replies..',
          'comments.filter.by.status': 'Comment Status',
          'comments.filter.by.keywords.clear': 'Clear',
          'comments.edit.dialog.header': 'Edit existing comment',
          'comments.edit.reply.header': 'Edit existing reply',
          'comments.create.dialog.header': 'Add new comment',
          'comments.create.dialog.button.save': 'Save',
          'comments.create.dialog.button.cancel': 'Cancel',
          'comments.status.ON_HOLD': 'Resolved',
          'comments.status.OPEN': 'Open',
          'comments.widget.name': 'Comments widget',
          'comments.widget.select.current': 'Include current object',
          'comments.widget.comments.limit': 'Display number of results',
          'comments.widget.display.options': 'Select display options',
          'comments.widget.select.users': 'Filter comments by users',
          'comments.widget.filters': 'Filters',
          'comments.widget.select.date': 'Filter comments by creation date',
          'comments.widget.error': 'There are no comments for the selected objects and filters',
          'comments.widget.select.all': 'All',
          'search.createdfrom.placeholder': 'Date created from...',
          'search.createdto.placeholder': 'Date created to...',
          'search.date.placeholder': 'Choose a date...',
          'search.date.from.placeholder': 'Choose date from...',
          'search.date.to.placeholder': 'Choose date to...',
          'search.numeric.placeholder': 'Enter a number...',
          'search.keyword.placeholder': 'Enter search terms...',
          'search.pagination.first': 'First',
          'search.pagination.last': 'Last',
          'search.messages.total': 'Results',
          'search.messages.orderDirection': 'Order results',
          'search.save.title.placeholder': 'Name and save this search for future use',
          'search.save.button.title': 'Save',
          'search.quick.placeholder': 'Search for objects, documents and more...',
          'search.save.confirm.message.update': 'Do you want to update the current Saved Search, or create a new one?',
          'search.save.confirm.message.create': 'Do you want to create a new saved search?',
          'search.save.confirm.create.new': 'Create New',
          'search.save.confirm.update': 'Update',
          'search.save.confirm.cancel': 'Cancel',
          'search.save.confirm.ok': 'Ok',
          'search.save.notification.message.create': 'Search with name {{searchName}} is created.',
          'search.save.notification.message.updated': 'Search with name{{searchName}} is updated.',
          'search.user.defined.query': 'User defined dynamic query',
          'select.codelist.placeholder': 'Select value...',
          'select.newobjecttype.placeholder': 'Select type...',
          'select.objecttype.placeholder': 'Select object types...',
          'select.search.context.placeholder': 'Select context...',
          'select.users.placeholder': 'Select created by...',
          'select.relationships.placeholder': 'Select relationships...',
          'select.object.automatically.more.than.one.message': 'More than one objects are found which satisfy the search criteria. Please select "Configure widget" action and chose only one of the objects in the search result.',
          'select.object.none': 'No selection.',
          'select.object.results.none': 'No object could be found with the selected search criteria.',
          'select.object.undefined.criteria': 'The widget has no search criteria configured. You need to perform a search before saving the configuration.',
          'idoc.page.button.save': 'Save',
          'idoc.page.button.just.save': 'Save & Edit',
          'idoc.page.button.edit': 'Edit',
          'idoc.page.button.cancel': 'Cancel',
          'idoc.menu.actions': 'Action',
          'idoc.save.notification.success': 'Document is saved successfully',
          'idoc.savedialog.header': 'Fill mandatory data',
          'idoc.savedialog.button.cancel': 'Cancel',
          'idoc.savedialog.button.save': 'Save',
          'idoc.widget.config.button.save': 'Save',
          'idoc.widget.config.button.cancel': 'Cancel',
          'idoc.tabs.configdialog.header': 'Tab Configuration',
          'idoc.tabs.configdialog.lock.tab': 'Lock tab',
          'idoc.tabs.configdialog.revision': 'Tab revision options',
          'idoc.tabs.configdialog.revision.clone.tab': 'Clone tab in the revision',
          'idoc.tabs.configdialog.revision.clone.tab.tooltip': 'This tab will be cloned in the next revision of the object.',
          'idoc.tabs.configdialog.revision.export.tab': 'Export tab in the revision',
          'idoc.tabs.configdialog.revision.export.tab.tooltip': 'This tab will be exported in the next revision of the object.',
          'idoc.tabs.configdialog.show.navigation': 'Show navigation',
          'idoc.tabs.configdialog.show.comments': 'Show comments',
          'idoc.tabs.delete.confirmation': 'Are you sure you want to delete this tab?',
          'idoc.tabs.delete.confirm': 'Confirm',
          'idoc.tabs.delete.cancel': 'Cancel',
          'idoc.tabs.delete.cannot.be.performed': 'Can not delete the last document tab',
          'idoc.tabs.title': 'Tab Title',
          'idoc.tabs.sections': 'Visible Tab Sections',
          'idoc.tabs.config.button.save': 'Save',
          'idoc.tabs.config.button.cancel': 'Cancel',
          'idoc.tabs.configure': 'Configure',
          'idoc.tabs.delete': 'Delete',
          'idoc.tabs.print': 'Print',
          'showMore.button': 'Show more...',
          'showLess.button': 'Show less...',
          'odw.config.deselect.all': 'Deselect all',
          'odw.config.display.show.more': 'Display "Show more..." button',
          'odw.config.display.show.regions.names': 'Show regions names',
          'odw.config.common.properties': 'Common properties',
          'odw.config.position.label': 'Properties label position',
          'odw.config.position.label.above': 'Position label above the field',
          'odw.config.position.label.hide': 'Hide label',
          'odw.config.position.label.left': 'Position label left from the field',
          'odw.config.position.label.align.left': 'Align label left',
          'odw.config.position.label.align.right': 'Align label right',
          'odw.config.borders': 'Borders',
          'odw.config.borders.show.widget.borders': 'Show widget borders',
          'odw.config.borders.show.input.field.borders': 'Show input field borders',
          'odw.config.select.all': 'Select all',
          'odw.config.type.to.filter': 'Type to start filtering',
          'odw.config.object.header': 'Object header',
          'widget.config.tab.chart.configuration': 'Chart configuration',
          'widget.config.tab.display.options': 'Widget display options',
          'widget.config.tab.object.details': 'Object details to be displayed',
          'widget.config.tab.select.object': 'Select object to be displayed',
          'widget.config.tab.select.objects': 'Select objects to be displayed',
          'widget.config.object.header.none': 'Do not display link of the objects',
          'widget.config.object.header.default': 'Display default header',
          'widget.config.object.header.compact': 'Display compact header',
          'widget.config.object.header.breadcrumb': 'Display breadcrumb header',
          'widget.config.label': 'Widget configuration',
          'widget.config.tab.report.configuration': 'Report Configuration',
          'widget.action.export.xlsx.tooltip': 'Export to Excel',
          'widget.recent-activities.none': 'No activities are available for the current selection.',
          'widgets.recent-activities.title': 'Recent activities',
          'widgets.recent-activities.page-size': 'Number of activities per page',
          'dtw.filter.field.placeholder': 'Search all',
          'dtw.filter.column.field.placeholder': 'Filter ',
          'dtw.column.header': 'Entity',
          'dtw.config.display.table.header.row': 'Display table header row',
          'dtw.config.object.header': 'Objects headers',
          'dtw.config.pages': 'Split results in pages',
          'dtw.config.pages.size': 'Page size: ',
          'dtw.config.pages.show.first.page.only': 'Display only first page',
          'table.config.grid': 'Configure table grid',
          'table.config.grid.on': 'Grid on',
          'table.config.grid.off': 'Grid off',
          'table.config.grid.horizontal': 'Grid by lines',
          'table.config.grid.vertical': 'Grid by columns',
          'picker.create.none': 'Objects of the selected predefined types can not be created.',
          'picker.basket.none': 'There are no selected objects.',
          'picker.basket.tab': 'Basket',
          'picker.dialog.header': 'Select object',
          'picker.recent.none': 'There are no recently used objects that could be selected.',
          'picker.create.tab': 'Create',
          'picker.recent.tab': 'Recently used',
          'picker.search.tab': 'Search',
          'widget.aggregated.table.number.column': 'Number',
          'widget.aggregated.table.total': 'Total results:',
          'widget.aggregated.table.show.footer': 'Show Total Row',
          'widget.aggregated.table.number.column.first': 'Display numbers in the first column',
          'widget.aggregated.table.value.column.first': 'Display values in the first column',
          'imagewidget.comments.new.topic': 'New Topic',
          'imagewidget.comments.header': 'Comments',
          'imagewidget.no.images.selected': 'No images selected.',
          'imagewidget.cannot.load.images': 'An error occurred while loading the images.',
          'imagewidget.config.lock.deactivate': 'Deactivate image manipulations in preview mode',
          'imagewidget.config.lock.widget': 'Lock widget',
          'image.widget.name': 'Image widget',
          'widget.property.option.checkbox': 'Display as checkbox',
          'widget.property.option.radio': 'Display as radio-button',
          'widget.property.option.dropdown': 'Display as dropdown',
          'object.selector.select.object.automatically': 'Automatically select object',
          'object.selector.select.object.automatically.includeCurrent': 'Include current object',
          'object.selector.select.object.current': 'Display information for the current object',
          'object.selector.select.object.manually': 'Manually select object',
          'objects.properties.modifiedOn': 'Modified On',
          'objects.properties.modifiedBy': 'Modified By',
          'objects.properties.createdOn': 'Created On',
          'objects.properties.createdBy': 'Created By',
          'objects.properties.type': 'Type',
          'objects.properties.title': 'Title',
          'labels.clear': 'Clear',
          'labels.preview.none': 'No preview available.',
          'labels.reset': 'Reset',
          'resizable.input.placeholder': 'Enter title',
          'context.selector.context.label': 'Context: ',
          'context.selector.context.select.btn': 'Select',
          'context.selector.no.context': 'No Context',
          'create.new.button': 'New',
          'action.add.thumbnail.existing': 'The object already has a thumbnail. Do you want to change it?',
          'action.add.thumbnail.header': 'Add thumbnail',
          'action.add.thumbnail.missing.id': 'Missing instance ID.',
          'action.add.thumbnail.success': 'The document was successfully added as thumbnail for the object.',
          'action.confirm.operation': 'Are you sure you want to execute operation [{{operationName}}]?',
          'action.create.revision': 'Revision has been created',
          'action.export.pdf.idoc.notification': 'Export to PDF has started.',
          'action.export.word.idoc.notification': 'Export to Word has started.',
          'action.move.completed': 'The object was successfully moved.',
          'action.move.not.allowed.error': 'Object can not be moved in the selected context.',
          'action.move.error': 'An error has occurred while moving the object.',
          'action.move.confirmation': 'The context of the current object will be changed. Are you sure?',
          'action.move.header': 'Move to',
          'action.print.idoc.notification': 'Preparing for print. When the page is ready, print dialog will be opened!',
          'action.notification.success': 'Successfully executed operation ',
          'dropdown.loading': 'Loading...',
          'user.menu.logout': 'Logout',
          'user.menu.change.password': 'Change password',
          'menu.admin': 'Administration Menu',
          'menu.admin.audit': 'Audit Log',
          'menu.admin.codelist': 'Code List Server',
          'menu.admin.configuration': 'System Configuration',
          'menu.admin.manage.actions.and.roles': 'Manage roles and actions',
          'menu.library.create.project': 'Create project',
          'menu.library.create.object': 'Create object',
          'menu.library.browse.project': 'Browse projects',
          'menu.dashboard': 'Dashboard',
          'menu.recent.objects': 'Recent Objects',
          'menu.browse.libraries': 'Browse Libraries',
          'recent.objects.load': 'Loading recently used objects...',
          'recent.objects.none': 'There are no recently used objects.',
          'instance.list.select.all': 'Select All',
          'instance.list.deselect.all': 'Deselect All',
          'instance.create.dialog.header': 'New',
          'instance.create.dialog.tab.create': 'Create',
          'instance.create.dialog.tab.upload': 'Upload',
          'instance.create.panel.clone': 'Clone',
          'instance.create.panel.create': 'Create',
          'instance.create.panel.create.success': 'Created object: ',
          'instance.create.panel.create.another': 'Create another',
          'instance.create.panel.type': 'Type',
          'instance.create.panel.subtype': 'Sub Type',
          'instance.create.panel.no.definition': 'You cannot create an object of this type. Please contact your system administrator!',
          'unsaved.data': 'Any unsaved changes will be lost. Do you want to proceed?',
          'fileupload.select': 'Select file...',
          'fileupload.selectMany': 'Select files...',
          'fileupload.upload': 'Upload',
          'fileupload.remove': 'Remove',
          'fileupload.successful': 'Uploaded Object: ',
          'fileupload.fail': 'Upload failed',
          'fileupload.maxSizeExceeded': 'Exceeded maximum allowed size of {{max_size}}.',
          'fileupload.wrongFileType': 'Wrong file type, please select {{file_type}}.',
          'iconupload.16x16header': 'Select 16x16 icon:',
          'iconupload.24x24header': 'Select 24x24 icon:',
          'iconupload.32x32header': 'Select 32x32 icon:',
          'iconupload.64x64header': 'Select 64x64 icon:',
          'content.viewer.widget.name': 'Content viewer',
          'object.data.widget.name': 'Object data widget',
          'datatable.widget.name': 'Data table widget',
          'aggregated.table.widget.name': 'Aggregated table',
          'objectlink.widget.name': 'Insert link',
          'administration.panel.tab.tenant.config': 'Tenant Configurations',
          'administration.panel.tab.manage.actions.per.role': 'Manage actions per role',
          'administration.tenant.confirmation.title': 'Tenant Configurations',
          'administration.tenant.button.save': 'Save',
          'administration.tenant.button.cancel': 'Cancel',
          'administration.tenant.filter.placeholder': 'Enter a keyword to filter configurations',
          'administration.tenant.filter.button': 'Filter',
          'administration.tenant.confirmation.message': 'Saving potentially incorrect configurations might harm the environment, are you sure you want to proceed ? Configurations that are modified:',
          'administration.tenant.notification.no.change': 'Nothing to save',
          'administration.tenant.notification.updated.success': 'Configurations have been updated',
          'administration.tenant.notification.updated.fail': 'Error during configurations reload',
          'administration.tenant.notification.reloaded.success': 'Configurations have been reloaded',
          'administration.tenant.notification.reloaded.fail': 'Error during configurations reload',
          'administration.tenant.notification.defaults': 'Default configurations reloaded',
          'administration.tenant.message.format': 'Invalid value format for the following configuration',
          'administration.role.actions.table.action.header': 'Action',
          'administration.role.actions.table.active.header': 'Active',
          'administration.role.actions.table.filter.header': 'Filter',
          'administration.role.actions.table.filter.placeholder': 'Enter a keyword to filter actions',
          'administration.role.actions.table.action.filters.placeholder': 'Select filters',
          'administration.role.actions.table.edit.btn': 'Edit actions per role',
          'administration.role.actions.table.save.btn': 'Save',
          'administration.role.actions.table.cancel.btn': 'Cancel',
          'search.advanced.criteria.and': 'And',
          'search.advanced.criteria.rule': 'Rule',
          'search.advanced.criteria.group': 'Group',
          'search.advanced.criteria.group.remove': 'Remove group',
          'search.advanced.criteria.or': 'Or',
          'search.advanced.criteria.remove': 'Remove',
          'search.advanced.operator.contains': 'Contains',
          'search.advanced.operator.does.not.contain': 'Does not contain',
          'search.advanced.operator.does.not.end.with': 'Does not end with',
          'search.advanced.operator.does.not.equal': 'Does not equal',
          'search.advanced.operator.does.not.start.with': 'Does not start with',
          'search.advanced.operator.empty': 'Is empty',
          'search.advanced.operator.ends.with': 'Ends with',
          'search.advanced.operator.equals': 'Equals',
          'search.advanced.operator.in': 'In',
          'search.advanced.operator.is': 'Is',
          'search.advanced.operator.is.after': 'Is after',
          'search.advanced.operator.is.before': 'Is before',
          'search.advanced.operator.is.between': 'Is between',
          'search.advanced.operator.is.not': 'Is not',
          'search.advanced.operator.is.within': 'Is within',
          'search.advanced.operator.not.in': 'Not in',
          'search.advanced.operator.starts.with': 'Starts with',
          'search.advanced.operator.set.to': 'Set to object',
          'search.advanced.operator.not.set.to': 'Not set to object',
          'search.advanced.operator.greater.than': 'Greater than',
          'search.advanced.operator.less.than': 'Less than',
          'search.advanced.operator.set.to.query': 'Set to query',
          'search.advanced.operator.not.set.to.query': 'Not set to query',
          'search.advanced.property.anyRelation': 'Any relation',
          'search.advanced.property.anyField': 'Any field',
          'search.advanced.property.anyField.warning': '"Any field" searches might be slower depending on the volume of data in the system',
          'search.advanced.value.anyObject': 'Any object',
          'search.advanced.value.boolean.true': 'True',
          'search.advanced.value.boolean.false': 'False',
          'search.advanced.search': 'Search',
          'search.basic': 'Basic search',
          'search.advanced': 'Advanced search',
          'search.daterange.dynamic.offset.placeholder': 'Enter date offset',
          'search.daterange.dynamic.step.after': 'After',
          'search.daterange.dynamic.step.before': 'Before',
          'search.daterange.dynamic.step.last': 'Last',
          'search.daterange.dynamic.step.next': 'Next',
          'search.daterange.dynamic.step.today': 'Today',
          'search.daterange.dynamic.type.days': 'Days',
          'search.daterange.dynamic.type.hours': 'Hours',
          'search.daterange.dynamic.type.months': 'Months',
          'search.daterange.dynamic.type.years': 'Years',
          'search.daterange.dynamic.type.weeks': 'Weeks',
          'search.select.group.by': 'Group by',
          'search.select.group.by.placeholder': 'Select property to group by',
          'system.tab.permissions': 'Permissions',
          'system.tab.versions': 'Versions',
          'permissions.no.manager': 'At least one manager is required.',
          'error.page.not.found': 'Sorry, the page you requested was not found',
          'error.page.unknown': 'Web server is returning an unknown error',
          'error.generic': 'An error occurred. Please contact your system administrator!',
          'error.object.not.found': 'Requested object not found in the system!',
          'error.object.forbidden': 'No permissions to see this object!',
          'change.password.dialog.header': 'Change password',
          'change.password.dialog.current': 'Enter current password',
          'change.password.dialog.current.mandatory': 'Current password is required',
          'change.password.dialog.new': 'Enter new password',
          'change.password.dialog.new.mandatory': 'New password is required',
          'change.password.dialog.new.length': 'New password must be between 6 and 30 characters long and cannot contain spaces',
          'change.password.dialog.new.same': 'The new password is the same as the current password',
          'change.password.dialog.confirm': 'Confirm new password',
          'change.password.dialog.confirm.mandatory': 'New password confirmation is required',
          'change.password.dialog.confirm.dont.match': 'New passwords don\'t match',
          'change.password.dialog.wrong': 'Old credential does not match with the existing credential',
          'change.password.dialog.change.btn': 'Change',
          'change.password.dialog.success': 'Your password has been successfully changed',
          'change.password.dialog.missing.args': 'Cannot change password without username, old password and new password',
          'instance.selector.select.btn': 'Select',
          'validation.field.mandatory': 'The field is mandatory!',
          'router.interrupt.dialog.btn.stay': 'Stay on page',
          'router.interrupt.dialog.btn.leave': 'Leave page',
          'router.interrupt.dialog.header': 'Confirmation Message',
          'router.interrupt.dialog.message': 'Please, confirm that you want to leave this page - Data you have entered may not be saved!',
          'unsaved.selection': 'The operation will clear your selection.',
          'external.import': 'Import',
          'external.update': 'Update',
          'external.search.error': 'The search results cannot be displayed. See the details below: \n',
          'external.search.no.results': '(0) objects found',
          'external.search.title.label': 'External search',
          'extenal.search.import.update': 'Import/Update selected',
          'external.operation.success': 'Operation was successful!',
          'checkbox.checked': 'Yes',
          'checkbox.unchecked': 'No',
          'draft.saved.message': 'Draft saved at {{draftCreatedOn}}',
          'draft.resume.confirmation': 'A version of this document you were editing at {{draftCreatedOn}} was saved as a draft. Do you want to resume editing or discard it?',
          'draft.btn.resume': 'Resume',
          'draft.btn.discard': 'Discard',
          'versions.not.processed': 'The version is unavailable at the moment, please check again later.',
          'versions.historical.versions': 'Historical versions',
          'versions.object': 'Object',
          'versions.version': 'Version',
          'versions.created.by': 'Created by',
          'versions.created.on': 'Created on',
          'versions.description': 'Description',
          'no.permissions': 'No permissions',
          'export.timeout.error.message': 'Process timed out. Please contact your system administrator.',
          'action.export.xlsx.idoc.notification': 'Export to Excel has started.',
          'help.label': 'Help',
          'common.results.all': 'All',
          'user.menu.help.request': 'Help Request',
          'user.menu.help.request.message.success': 'Your message was sent successfully.',
          'user.menu.help.request.message.error': 'Failed to send message.',
          'help.request.action.label': 'Contact us',
          'help.request.dialog.header': 'Get help from SEP support team',
          'help.request.dialog.send.btn': 'Send',
          'help.request.dialog.subject.label': 'Subject',
          'help.request.dialog.type.label': 'Type',
          'help.request.dialog.description.label': 'Description',
          'help.request.current.url': 'Link to the page.',
          'help.request.current.url.description': 'The problem is identified on page:',
          'version.original.instance.message': 'This is historical version. To view the current version click <a href="{{originalInstanceURL}}">here</a>',
          'bpm.transition': 'Action {{transitionId}} is successfully executed<br>',
          'bpm.created': 'The following objects have been created <br>',
          'bpm.transition.condition.failure': 'The object has been edited by another user. Try to execute the action again. <br>',
          'bpm.transition.condition.locked': 'The object is locked, and you cannot perform the action on it. <br>',
          'import.file.confirmation.message': 'Select "Import file" if you want to continue with the data import. You can check the validation report here ',
          'import.validation.message': 'Validation of the file format and the data in the file starts.',
          'idoc.info.data.import.triggered': 'Data import has been launched. Please wait!',
          'widgets.process.title': 'Process Widget',
          'widgets.process.empty': 'No process is selected.',
          'widgets.process.not.started': 'The process isn`t started.',
          'widgets.process.select.proper.value': 'Object of type Workflow should be selected. Please select "Configure widget" action and select "Automatically select object" or "Manually select object"',
          'widgets.process.select.single.value': 'More than one objects are found which satisfy the search criteria. Please select "Configure widget" action and chose only one of the objects in the search result.',
          'process.title': 'Current process progress',
          'template.activation.success': 'Template was successfully activated.',
          'template.activation.error': 'Template could not be activated.'
        },
        bg: {
          'chart.bar.chart': 'Колонна диаграма',
          'chart.line.chart': 'Линейна диаграма',
          'chart.pie.chart': 'Кръгова диаграма',
          'chart.select.type': 'Изберете тип диаграма',
          'chart.total.results': 'Общ брой резултати:',
          'chart.view.widget.name': 'Диаграми',
          'company.name': 'Платформа Сирма',
          'breadcrumb.home': 'Начало',
          'breadcrumb.dashboard': 'Работен плот',
          'top.header.title': 'Потребителски работен плот',
          'context.current.object': 'Текущия обект',
          'dialog.header.confirm': 'Потвърждение',
          'dialog.header.error': 'Грешка!',
          'dialog.header.notification': 'Уведомление',
          'dialog.header.select.context': 'Изберете контекст',
          'dialog.button.cancel': 'Отказ',
          'dialog.button.close': 'Затвори',
          'dialog.button.confirm': 'Подтвърждаване',
          'dialog.button.no': 'Не',
          'dialog.button.ok': 'Добре',
          'dialog.button.yes': 'Да',
          'dialog.button.upload': 'Качи',
          'dialog.button.save': 'Запази',
          'dialog.button.upload.all': 'Качи всички',
          'dialog.button.importfile': 'Импортиране',
          'dialog.button.validatefile': 'Валидиране на файл',
          'idoc.clone.header': 'Клониране',
          'idoc.template.button.primary': 'Главен шаблон',
          'idoc.template.create': 'Създаване на шаблон',
          'idoc.template.status.duplication': 'Вече съществува шаблон с това име. Моля променете името на шаблона.',
          'idoc.template.status.success': ' е запазен успешно.',
          'idoc.template.title': 'Име на шаблона',
          'idoc.template.title.placeholder': 'Въведете име на шаблона...',
          'idoc.template.type': 'Тип на обект за шаблона',
          'idoc.template.purpose': 'Цел на шаблона',
          'idoc.template.creatable': 'Съдържание, което може да се създава',
          'idoc.template.uploadable': 'Съдържание, което може да се качва',
          'idoc.permissions.save.permissions': 'Запази Права',
          'idoc.permissions.cancel.save': 'Отказ',
          'idoc.permissions.add.user': 'Добави Потребител/Група',
          'idoc.permissions.user': 'Потребител/Група',
          'idoc.permissions.active': 'Активни Права',
          'idoc.permissions.special': 'Специални Права',
          'idoc.permissions.parent': 'Наследени Родителски Права',
          'idoc.permissions.library': 'Наследени Библиотечни Права',
          'idoc.permissions.management': 'Мениджмънт Права',
          'idoc.permissions.edit.permissions': 'Промени Права',
          'idoc.permissions.manage.inheritance': 'Управление на наследяването на правата:',
          'idoc.permissions.inherit.parent': 'Наследи родителски права',
          'idoc.permissions.inherit.library': 'Наследи права от библиотека',
          'idoc.permissions.restore.children': 'Възстанови правата на подобектите',
          'idoc.permissions.restore.children.confirmation': 'Всички специални права на наследниците на този обект ще бъдат премахнати! Операцията е необратима! Желаете ли да продължите?',
          'idoc.permissions.restore.children.done': 'Правата са променени',
          'comments.action.edit': 'Редактирай',
          'comments.action.delete': 'Изтрий',
          'comments.action.delete.confirm': 'Сигурни ли сте, че искате да изтриете коментара?',
          'comments.action.reply': 'Отговори',
          'comments.action.filter': 'Филтриране на коментари',
          'comments.toolbar.button.addcomment': 'Нов коментар',
          'comments.toolbar.button.filter': 'Филтрирай',
          'comments.filter.by.autor': 'Автор',
          'comments.filter.by.keywords': 'Търсене по ключова дума в коментар/отговор..',
          'comments.filter.by.status': 'Статус',
          'comments.filter.by.keywords.clear': 'Изчисти',
          'comments.edit.dialog.header': 'Редактирай коментар',
          'comments.edit.reply.header': 'Редактирай отговор ',
          'comments.create.dialog.header': 'Нов коментар',
          'comments.create.dialog.button.save': 'Запази',
          'comments.create.dialog.button.cancel': 'Откажи',
          'comments.status.ON_HOLD': 'Разрешен',
          'comments.status.OPEN': 'Отворен',
          'comments.widget.name': 'Коментари',
          'comments.widget.select.current': 'Избери текущият обект',
          'comments.widget.comments.limit': 'Избери лимита на коментарите',
          'comments.widget.display.options': 'Настройки на визуализация',
          'comments.widget.select.users': 'Филтрирай по потребители',
          'comments.widget.filters': 'Филтри',
          'comments.widget.select.date': ' Филтрирай коментарите по дата на създаване',
          'comments.widget.error': 'Няма намерени коментари по зададените обекти и филтри',
          'comments.widget.select.all': 'Всички',
          'search.createdfrom.placeholder': 'Начална дата на създаване...',
          'search.createdto.placeholder': 'Крайна дата на създаване...',
          'search.date.placeholder': 'Изберете дата...',
          'search.date.from.placeholder': 'Изберете начална дата...',
          'search.date.to.placeholder': 'Изберете крайна дата...',
          'search.numeric.single.placeholder': 'Въведете число...',
          'search.keyword.placeholder': 'Въведете критерии за търсене...',
          'search.pagination.first': 'Първи',
          'search.pagination.last': 'Последен',
          'search.messages.total': 'Резултати',
          'search.messages.orderDirection': 'Подреждане на резултати',
          'search.save.title.placeholder': 'Въведи заглавие и запиши търсенето',
          'search.save.button.title': 'Запази',
          'search.quick.placeholder': 'Търсене на обекти, документ и още...',
          'search.save.confirm.message.update': 'Искате ли да обновите запазеното търсене или създайте нов?',
          'search.save.confirm.message.create': 'Искате ли да създадете ново търсене?',
          'search.save.confirm.create.new': 'Създай нов',
          'search.save.confirm.update': 'Обнови',
          'search.save.confirm.cancel': 'Откажи',
          'search.save.confirm.ok': 'Разбрах',
          'search.save.notification.message.create': 'Запазено търсене с име {{searchName}}.',
          'search.save.notification.message.updated': 'Обновено търсене с име {{searchName}}.',
          'search.user.defined.query': 'Динамична заявка създадена от потребител',
          'select.codelist.placeholder': 'Избери...',
          'select.objecttype.placeholder': 'Изберете типове обекти...',
          'select.newobjecttype.placeholder': 'Изберете тип...',
          'select.search.context.placeholder': 'Изберете контекст...',
          'select.users.placeholder': 'Изберете създаден от...',
          'select.relationships.placeholder': 'Изберете връзки...',
          'select.object.automatically.more.than.one.message': 'Намерени са повече от един обект. Моля изпълнете действието "Конфигурирай" и изберете само един обект от резултатите от търсенето.',
          'select.object.none': 'Няма избран обект.',
          'select.object.results.none': 'Няма обект, който да отговаря на избраните критерии за търсене.',
          'select.object.undefined.criteria': 'Няма конфигурирани критерии за търсене. Необходимо е да се изпълни търсене преди запазване на конфигурацията.',
          'idoc.page.button.save': 'Запази',
          'idoc.page.button.just.save': 'Запазване и Редактиране',
          'idoc.page.button.edit': 'Редактирай',
          'idoc.page.button.cancel': 'Откажи',
          'idoc.menu.actions': 'Операция',
          'idoc.save.notification.success': 'Документът е запазен успешно',
          'idoc.savedialog.header': 'Попълни задължителните полета',
          'idoc.savedialog.button.cancel': 'Откажи',
          'idoc.savedialog.button.save': 'Запази',
          'idoc.widget.config.button.save': 'Запази',
          'idoc.widget.config.button.cancel': 'Откажи',
          'idoc.tabs.configdialog.header': 'Конфигурация',
          'idoc.tabs.configdialog.lock.tab': 'Заключи таба',
          'idoc.tabs.configdialog.revision': 'Опции за ревизия',
          'idoc.tabs.configdialog.revision.clone.tab': 'Клонирай в ревизията',
          'idoc.tabs.configdialog.revision.clone.tab.tooltip': 'Този таб ще бъде клониран в следваща ревизия на обекта.',
          'idoc.tabs.configdialog.revision.export.tab': 'Експортирай в ревизията',
          'idoc.tabs.configdialog.revision.export.tab.tooltip': 'Този таб ще бъде експортиран в следваща ревизия на обекта.',
          'idoc.tabs.configdialog.show.navigation': 'Покажи навигацията',
          'idoc.tabs.configdialog.show.comments': 'Покажи коментарите',
          'idoc.tabs.delete.confirmation': 'Сигурни ли сте, че желаете да изтриете този таб',
          'idoc.tabs.delete.confirm': 'Потвърди',
          'idoc.tabs.delete.cancel': 'Откажи',
          'idoc.tabs.delete.cannot.be.performed': 'Последния таб не може да бъде изтрит',
          'idoc.tabs.title': 'Заглавие',
          'idoc.tabs.sections': 'Секции',
          'idoc.tabs.config.button.save': 'Запази',
          'idoc.tabs.config.button.cancel': 'Откажи',
          'idoc.tabs.configure': 'Конфигурирай',
          'idoc.tabs.delete': 'Изтрий',
          'idoc.tabs.print': 'Отпечатай',
          'showMore.button': 'Покажи още...',
          'showLess.button': 'Само избраните...',
          'odw.config.deselect.all': 'Премахни всички',
          'odw.config.display.show.more': 'Покажи "Покажи още..." бутона',
          'odw.config.display.show.regions.names': 'Покажи имената на регионите',
          'odw.config.common.properties': 'Общи полета',
          'odw.config.position.label': 'Позиция на етикета на полето',
          'odw.config.position.label.above': 'Позиционирай над полето',
          'odw.config.position.label.hide': 'Скрий етикета',
          'odw.config.position.label.left': 'Позиционирай от ляво на полето',
          'odw.config.position.label.align.left': 'Подравни етикета в ляво',
          'odw.config.position.label.align.right': 'Подравни етикета в дясно',
          'odw.config.borders': 'Рамки',
          'odw.config.borders.show.widget.borders': 'Покажи рамката на инструмента',
          'odw.config.borders.show.input.field.borders': 'Покажи рамката на полетата',
          'odw.config.select.all': 'Избери всички',
          'odw.config.type.to.filter': 'Въведи текст за филтриране',
          'odw.config.object.header': 'Етикет на обекта',
          'widget.config.tab.chart.configuration': 'Конфигуриране на диаграмата',
          'widget.config.tab.display.options': 'Настройки за визуализация',
          'widget.config.tab.object.details': 'Детайли на обекта за визуализиране',
          'widget.config.tab.select.object': 'Избери обект за визуализиране',
          'widget.config.tab.select.objects': 'Избери обекти за визуализиране',
          'widget.config.object.header.none': 'Скрии етикетите',
          'widget.config.object.header.default': 'Покажи стандартния етикет',
          'widget.config.object.header.compact': 'Покажи компактния етикет',
          'widget.config.object.header.breadcrumb': 'Покажи навигационния етикет',
          'widget.config.label': 'Конфигуриране на уиджета',
          'widget.config.tab.report.configuration': 'Конфигуриране на отчета',
          'widget.action.export.xlsx.tooltip': 'Експорт към ексел',
          'widget.recent-activities.none': 'Няма налични дейности за текущата селекция.',
          'widgets.recent-activities.title': 'Последни дейности',
          'widgets.recent-activities.page-size': 'Брой дейности на страница',
          'dtw.filter.field.placeholder': 'Търси във всички',
          'dtw.filter.column.field.placeholder': 'Филтрирай ',
          'dtw.column.header': 'Етикет',
          'dtw.config.display.table.header.row': 'Покажи заглавен ред в таблицата',
          'dtw.config.object.header': 'Етикети на обектите',
          'dtw.config.pages': 'Странициране',
          'dtw.config.pages.size': 'Брой резултати на страница: ',
          'dtw.config.pages.show.first.page.only': 'Покажи само първата страница',
          'table.config.grid': 'Конфигурирай Таблица',
          'table.config.grid.on': 'Решетка включена',
          'table.config.grid.off': 'Решетка изключена',
          'table.config.grid.horizontal': 'Решетка по редове',
          'table.config.grid.vertical': 'Решетка по колони',
          'picker.create.none': 'Обекти от текущо избраните предефинирани типове не могат да бъдат създавани.',
          'picker.basket.none': 'Няма избрани обекти.',
          'picker.basket.tab': 'Избрани обекти',
          'picker.dialog.header': 'Изберете обект',
          'picker.recent.none': 'Няма последно използвани обекти, които могат да бъдат избрани.',
          'picker.create.tab': 'Създаване',
          'picker.recent.tab': 'Последно използвани',
          'picker.search.tab': 'Търсене',
          'widget.aggregated.table.number.column': 'Брой',
          'widget.aggregated.table.total': 'Общ брой резултати:',
          'widget.aggregated.table.show.footer': 'Показвай общия брой резултати',
          'widget.aggregated.table.number.column.first': 'Покажи колоната с брой първа',
          'widget.aggregated.table.value.column.first': 'Покажи колоната със стойности първа',
          'imagewidget.comments.new.topic': 'Нова тема',
          'imagewidget.comments.header': 'Коментари',
          'image.widget.name': 'Изображения',
          'widget.property.option.checkbox': 'Визуализация с отметки',
          'widget.property.option.radio': 'Визуализация с радио бутони',
          'widget.property.option.dropdown': 'Визуализация чрез меню',
          'imagewidget.no.images.selected': 'Няма избрани изображения.',
          'imagewidget.config.lock.deactivate': 'Изключи манипулациите върху изображения в режим на преглед',
          'imagewidget.config.lock.widget': 'Заключи инструмента',
          'imagewidget.cannot.load.images': 'Възникна грешка при зареждането на изображения.',
          'object.selector.select.object.automatically': 'Автоматично избиране на обект',
          'object.selector.select.object.automatically.includeCurrent': 'Включи текущия обект',
          'object.selector.select.object.current': 'Покажи информация за текущия обект',
          'object.selector.select.object.manually': 'Ръчно избиране на обект',
          'objects.properties.modifiedOn': 'Дата на промяна',
          'objects.properties.modifiedBy': 'Променен от',
          'objects.properties.createdOn': 'Дата на създаване',
          'objects.properties.createdBy': 'Създаден от',
          'objects.properties.type': 'Тип',
          'objects.properties.title': 'Заглавие',
          'labels.clear': 'Изчисти',
          'labels.preview.none': 'Няма налична визуализация.',
          'labels.reset': 'Зачисти',
          'resizable.input.placeholder': 'Въведете име',
          'context.selector.context.label': 'Контекст: ',
          'context.selector.context.select.btn': 'Избери',
          'context.selector.no.context': 'Няма контекст',
          'create.new.button': 'Създай',
          'action.add.thumbnail.existing': 'Обектът вече има умалено изображение. Искате ли да го смените?',
          'action.add.thumbnail.header': 'Задаване на умалено изображение',
          'action.add.thumbnail.missing.id': 'Липсва идентификатор на обекта.',
          'action.add.thumbnail.success': 'Документът беше успешно зададен като умалено изображение на обекта.',
          'action.confirm.operation': 'Сигурни ли сте, че искате да изпълните операция [{{operationName}}]?',
          'action.create.revision': 'Ревизията е създадена',
          'action.export.pdf.idoc.notification': 'Експортът към PDF е стартиран.',
          'action.export.word.idoc.notification': 'Експортът към Word е стартиран.',
          'action.move.completed': 'Избраният обект беше успешно преместен.',
          'action.move.error': 'Възникна грешка по време на преместването на този обект.',
          'action.move.not.allowed.error': 'Обектът не може да бъде преместен в избрания контекст.',
          'action.move.confirmation': 'Контекста на текущия обект ще бъде сменен. Сигурни ли сте, че искате да продължите с операцията?',
          'action.move.header': 'Премести в',
          'action.print.idoc.notification': 'Започва подготовка за печат. Когато документът бъде готов, ще бъде отворен диалога за печат!',
          'action.notification.success': 'Успешно изпълнена операция ',
          'dropdown.loading': 'Зареждане...',
          'user.menu.change.password': 'Смяна на парола',
          'user.menu.logout': 'Изход',
          'menu.admin': 'Админиситративно меню',
          'menu.admin.audit': 'Аудит Лог',
          'menu.admin.codelist': 'Код Лист Сървър',
          'menu.admin.configuration': 'Системни конфигурации',
          'menu.admin.manage.actions.and.roles': 'Управление на роли и операции',
          'menu.library.create.project': 'Създай проект',
          'menu.library.create.object': 'Създай обект',
          'menu.library.browse.project': 'Търси проект',
          'menu.dashboard': 'Моят работен плот',
          'menu.recent.objects': 'Последно използвани',
          'menu.browse.libraries': 'Търси библиотека',
          'recent.objects.load': 'Зареждане на последно използвани обекти...',
          'recent.objects.none': 'Няма последно използвани обекти.',
          'instance.list.select.all': 'Избери всички',
          'instance.list.deselect.all': 'Премахни всички',
          'instance.create.dialog.header': 'Създаване',
          'instance.create.dialog.tab.create': 'Създай',
          'instance.create.dialog.tab.upload': 'Качи',
          'instance.create.panel.clone': 'Клонирай',
          'instance.create.panel.create': 'Създай',
          'instance.create.panel.create.success': 'Създаден е обект: ',
          'instance.create.panel.create.another': 'Създай друг',
          'instance.create.panel.type': 'Тип',
          'instance.create.panel.subtype': 'Подтип',
          'instance.create.panel.no.definition': 'Не можете да създадете обект от този тип. Моля свържете се със системния администратор!',
          'unsaved.data': 'Всички незапазени промени ще бъдат загубени. Желаете ли да продължите?',
          'fileupload.select': 'Избери файл...',
          'fileupload.selectMany': 'Избери файлове...',
          'fileupload.upload': 'Прикачи',
          'fileupload.remove': 'Изтрий',
          'fileupload.successful': 'Качен е обект: ',
          'fileupload.fail': 'Неуспешна операция',
          'fileupload.maxSizeExceeded': 'Превишен е максималния размер от {{max_size}}',
          'fileupload.wrongFileType': 'Грешен тип на файла. Моля въведи {{file_type}}',
          'iconupload.16x16header': 'Избери 16x16 икона:',
          'iconupload.24x24header': 'Избери 24x24 икона:',
          'iconupload.32x32header': 'Избери 32x32 икона:',
          'iconupload.64x64header': 'Избери 64x64 икона:',
          'content.viewer.widget.name': 'Преглед на съдържание',
          'object.data.widget.name': 'Данни за обект',
          'datatable.widget.name': 'Таблица с данни',
          'aggregated.table.widget.name': 'Агрегирана таблица',
          'objectlink.widget.name': 'Добави линк',
          'administration.panel.tab.tenant.config': 'Тенант конфигурации',
          'administration.panel.tab.manage.actions.per.role': 'Управление на роли и операции',
          'administration.tenant.confirmation.title': 'Тенант конфигурации',
          'administration.tenant.button.save': 'Запази',
          'administration.tenant.button.cancel': 'Отмени',
          'administration.tenant.filter.placeholder': 'Въведете ключова дума за филтриране на конфигурациите',
          'administration.tenant.filter.button': 'Филтрирай',
          'administration.tenant.confirmation.message': 'Запазването на евентуално некоректни конфигурации може да навреди на вашата среда, сигурни ли сте че искате да продължите ? Конфигурации, които са променени:',
          'administration.tenant.notification.no.change': 'Няма конфигурации за запазване',
          'administration.tenant.notification.updated.success': 'Конфигурациите бяха актуализирани',
          'administration.tenant.notification.updated.fail': 'Грешка по време на актуализиране на конфигурациите',
          'administration.tenant.notification.reloaded.success': 'Конфигурациите бяха презаредени',
          'administration.tenant.notification.reloaded.fail': 'Грешка по време на презареждане на конфигурациите',
          'administration.tenant.notification.defaults': 'Заредени са конфигурациите по подразбиране',
          'administration.tenant.message.format': 'Въведената стойност не отговаря на типа на конфигурацията',
          'administration.role.actions.table.action.header': 'Операция',
          'administration.role.actions.table.active.header': 'Активен',
          'administration.role.actions.table.filter.header': 'Филтър',
          'administration.role.actions.table.filter.placeholder': 'Въведете ключова дума за филтриране на операциите',
          'administration.role.actions.table.action.filters.placeholder': 'Избиране на филтри',
          'administration.role.actions.table.edit.btn': 'Редакция на роли и операции',
          'administration.role.actions.table.save.btn': 'Запазване',
          'administration.role.actions.table.cancel.btn': 'Отказване',
          'search.advanced.criteria.and': 'И',
          'search.advanced.criteria.rule': 'Правило',
          'search.advanced.criteria.group': 'Група',
          'search.advanced.criteria.group.remove': 'Премахни групата',
          'search.advanced.criteria.or': 'Или',
          'search.advanced.criteria.remove': 'Премахни',
          'search.advanced.operator.contains': 'Съдържа',
          'search.advanced.operator.does.not.contain': 'Не съдържа',
          'search.advanced.operator.does.not.end.with': 'Не завършва на',
          'search.advanced.operator.does.not.equal': 'Не се равнява на',
          'search.advanced.operator.does.not.start.with': 'Не започва с',
          'search.advanced.operator.empty': 'Без стойност',
          'search.advanced.operator.ends.with': 'Завършва на',
          'search.advanced.operator.equals': 'Се равнява на',
          'search.advanced.operator.in': 'Във',
          'search.advanced.operator.is': 'Е',
          'search.advanced.operator.is.after': 'След',
          'search.advanced.operator.is.before': 'Преди',
          'search.advanced.operator.is.between': 'Между',
          'search.advanced.operator.is.not': 'Не е',
          'search.advanced.operator.is.within': 'В рамките на',
          'search.advanced.operator.not.in': 'Не е във',
          'search.advanced.operator.starts.with': 'Започва с',
          'search.advanced.operator.set.to': 'Съществува към обект',
          'search.advanced.operator.not.set.to': 'Не съществува към обект',
          'search.advanced.operator.greater.than': 'По-голямо от',
          'search.advanced.operator.less.than': 'По-малко от',
          'search.advanced.operator.set.to.query': 'Съществува към заявка',
          'search.advanced.operator.not.set.to.query': 'Не съществува към заявка',
          'search.advanced.property.anyRelation': 'Всяка релация',
          'search.advanced.property.anyField': 'Всяко поле',
          'search.advanced.property.anyField.warning': 'Възможно е търсенията по "Всяко поле" да са по-бавни в зависимост от обема данни в системата',
          'search.advanced.value.anyObject': 'Всеки обект',
          'search.advanced.value.boolean.true': 'Истина',
          'search.advanced.value.boolean.false': 'Лъжа',
          'search.advanced.search': 'Търсене',
          'search.basic': 'Търсене на обекти',
          'search.advanced': 'Разширено търсене на обекти',
          'search.daterange.dynamic.offset.placeholder': 'Въведете време',
          'search.daterange.dynamic.step.after': 'След',
          'search.daterange.dynamic.step.before': 'Преди',
          'search.daterange.dynamic.step.last': 'Последните',
          'search.daterange.dynamic.step.next': 'Следващите',
          'search.daterange.dynamic.step.today': 'Днес',
          'search.daterange.dynamic.type.days': 'Дни',
          'search.daterange.dynamic.type.hours': 'Часове',
          'search.daterange.dynamic.type.months': 'Месеци',
          'search.daterange.dynamic.type.years': 'Години',
          'search.daterange.dynamic.type.weeks': 'Седмици',
          'search.select.group.by': 'Групирай по',
          'search.select.group.by.placeholder': 'Избор на поле за групиране',
          'system.tab.permissions': 'Права',
          'system.tab.versions': 'Версии',
          'permissions.no.manager': 'Изисква се поне един мениджър.',
          'error.page.not.found': 'Съжелявам, страницата която търсете не е намерена',
          'error.page.unknown': 'В сървърът възникна неразпозната грешка',
          'error.generic': 'Възникна грешка. Моля свържете се с администратор!',
          'error.object.not.found': 'Обекта не е намерен в системата!',
          'error.object.forbidden': 'Недостатъчни права за преглед на този обект!',
          'change.password.dialog.header': 'Смяна на парола',
          'change.password.dialog.current': 'Въведете текуща парола',
          'change.password.dialog.current.mandatory': 'Текущата парола е задължителна',
          'change.password.dialog.new': 'Въведете нова парола',
          'change.password.dialog.new.mandatory': 'Новата парола е задължителна',
          'change.password.dialog.new.length': 'Новата парола трябва да е между 6 и 30 символа дължина и не може да съдържа интервали',
          'change.password.dialog.new.same': 'Новата парола е същата като текущата',
          'change.password.dialog.confirm': 'Потвърдете новата парола',
          'change.password.dialog.confirm.mandatory': 'Потвърждаване на новата парола е задължителна',
          'change.password.dialog.confirm.dont.match': 'Новите пароли не съвпадат',
          'change.password.dialog.wrong': 'Текущата парола е грешна',
          'change.password.dialog.change.btn': 'Смяна',
          'change.password.dialog.success': 'Паролата е променена успешно',
          'change.password.dialog.missing.args': 'Паролата не може да бъде променена без текуща, нова и потвърждение на новата парола',
          'instance.selector.select.btn': 'Избери',
          'validation.field.mandatory': 'Полето е задължително!',
          'router.interrupt.dialog.btn.stay': 'Оставане на страницата',
          'router.interrupt.dialog.btn.leave': 'Напускане на страницата',
          'router.interrupt.dialog.header': 'Съобщение за потвърждение',
          'router.interrupt.dialog.message': 'Моля потвърдете напускането на страницата. Въведените данни може да не бъдат съхранени!',
          'unsaved.selection': 'Операцията ще премахне предварително избраните от вас обекти',
          'external.import': 'Импортиране',
          'external.update': 'Обновяване',
          'external.search.error': 'Резулататите не могат да бъдат показани, вижте детаилното съобщение : \n',
          'external.search.no.results': '(0) намерени обекта',
          'external.search.title.label': 'Търсене на обекти от външни системи',
          'external.operation.success': 'Операцията беше изпълнена успешно!',
          'checkbox.checked': 'Да',
          'checkbox.unchecked': 'Не',
          'draft.saved.message': 'Чернова запазена на {{draftCreatedOn}}',
          'draft.resume.confirmation': 'Версия на този документ, който сте редактирали на {{draftCreatedOn}} е запазена като чернова. Искате ли да подновите редакцията или ще я отхвърлите?',
          'draft.btn.resume': 'Поднови',
          'draft.btn.discard': 'Отхвърли',
          'versions.not.processed': ' Версията е недостъпна в момента, моля проверете отново по-късно.',
          'versions.historical.versions': 'Исторически версии',
          'versions.object': 'Обект',
          'versions.version': 'Версия',
          'versions.created.by': 'Създадена от',
          'versions.created.on': 'Създадена на',
          'versions.description': 'Описание',
          'no.permissions': 'Нямате права',
          'export.timeout.error.message': 'Процесът отнема твърде много време. Моля свържете се със системния администратор.',
          'action.export.xlsx.idoc.notification': 'Експортът към ексел е стартиран.',
          'help.label': 'Помощ',
          'common.results.all': 'Всички',
          'user.menu.help.request': 'Изпращане на запитване',
          'user.menu.help.request.message.success': 'Вашето съобщение беше успешно изпратено.',
          'user.menu.help.request.message.error': 'Вашето съобщение не беше изпратено.',
          'help.request.action.label': 'Свържете се с нас',
          'help.request.dialog.header': 'Получаване на помощ от екипа за поддръжка',
          'help.request.dialog.send.btn': 'Изпращане',
          'help.request.dialog.subject.label': 'Относно',
          'help.request.dialog.type.label': 'Тип',
          'help.request.dialog.description.label': 'Описание',
          'help.request.current.url': 'Линк към страницата.',
          'help.request.current.url.description': 'Проблемът е идентифициран на страница:',
          'version.original.instance.message': 'Това е историческа версия. За да видите текущата версия натиснете <a href="{{originalInstanceURL}}">тук</a>',
          'bpm.transition': 'Действието {{transitionId}} е изпълнено успешно <br>',
          'bpm.created': 'Създадени са следните обекти <br>',
          'bpm.transition.condition.failure': 'Обектът е бил редактиран от друг потребител. Опитайте да изпълните действието отново. <br>',
          'bpm.transition.condition.locked': 'Обектът е заключен, Вие не можете да изпълните действието. <br>',
          'import.file.confirmation.message': 'Моля потвърдете импортирането на данни от този файл. Може да разгледате отчета за валидация тук ',
          'import.validation.message': 'Стартира валидацията на данните.',
          'idoc.info.data.import.triggered': 'Импортирането на данни се стартира. Моля изчакайте!',
          'widgets.process.title': 'Бизнес процес',
          'widgets.process.empty': 'Не е избран процес',
          'widgets.process.not.started': 'Процесът не е стартиран',
          'widgets.process.select.proper.value': 'Обект от тип процес трябва да бъде избран. Моля изберете "Конфигуриране на уиджет" и изберете "Автоматично избиране на обекти" или "Ръчно избиране"',
          'widgets.process.select.single.value': 'Намерени са повече от един обект. Моля изпълнете действието "Конфигурирай" и изберете само един обект от резултатите от търсенето.',
          'process.title': 'Прогрес на текущия процес',
          'template.activation.success': 'Шаблона беше активиран успешно.',
          'template.activation.error': 'Шаблона не може да бъда активиран.'
        }
      };
      resolve(data[language]);
    });
  }
}