PREFIX cnctr: <http://www.sirma.com/ontologies/2017/06/connectors#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

delete {
    ?instance ?p ?o .
} where {
    ?instance a cnctr:Connector .
    ?instance ?p ?o .
    filter(?instance != cnctr:default_fts)
}

