PREFIX solr: <http://www.ontotext.com/connectors/solr#>
PREFIX solr-inst: <http://www.ontotext.com/connectors/solr/instance#>

INSERT DATA {
solr-inst:{coreName} solr:createConnector '''
{
    "fields": [
      {
      "fieldName": "rdfType",
      "propertyChain": [
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    {
    "fieldName": "instanceType",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#instanceType"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "type",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#type"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "isDeleted",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isDeleted"
      ],
      "datatype": "native:booleans",
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "isActive",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isActive"
      ],
      "datatype": "native:booleans",
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": false
    },
	{
      "fieldName": "filterType",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#filterType"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": false
    },
	{
      "fieldName": "mutable",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mutable"
      ],
      "datatype": "native:booleans",
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "identifier",
      "propertyChain": [
        "http://purl.org/dc/terms/identifier"
      ],
      "indexed": true,
      "stored": true,
      "datatype": "native:lowercase",
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "title",
      "propertyChain": [
        "http://purl.org/dc/terms/title"
      ],
      "indexed": true,
      "stored": true,
      "datatype": "native:lowercase",
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "name",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#fileName"
      ],
      "indexed": true,
      "stored": true,
      "datatype": "native:lowercase",
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "description",
      "propertyChain": [
        "http://purl.org/dc/terms/description"
      ],
      "indexed": true,
      "stored": true,
      "datatype": "native:lowercase",
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "status",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#status"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "owner",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#owner"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "assignee/1",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasAssignee",
        "http://www.ontotext.com/proton/protontop#hasMember"
      ],
      "indexed": true,
      "stored": true,
      "datatype": "native:lowercase",
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "assignee/2",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasAssignee"
      ],
      "indexed": true,
      "stored": true,
      "datatype": "native:lowercase",
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "poolOwner/1",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasPoolAssignee",
        "http://www.ontotext.com/proton/protontop#hasMember"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "poolOwner/2",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasPoolAssignee"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "mimetype",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mimetype"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "content/1",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#content"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": true,
      "multivalued": true
    },
    {
      "fieldName": "content/2",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#viewContent"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": true,
      "multivalued": true
    },
    {
      "fieldName": "content/3",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#viewWidgetsContent"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": true,
      "multivalued": true
    },
    {
      "fieldName": "ocrContent",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#ocrContent"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": true,
      "multivalued": true
    },
    {
      "fieldName": "endTime",
      "propertyChain": [
        "http://www.ontotext.com/proton/protontop#endTime"
      ],
      "datatype": "xsd:dateTime",
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "plannedEndDate",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#plannedEndDate"
      ],
      "datatype": "xsd:dateTime",
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "plannedStartDate",
      "propertyChain": [
            "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#plannedStartDate"
      ],
      "datatype": "xsd:dateTime",
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "priority",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#priority"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "createdOn",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#createdOn"
      ],
      "datatype": "xsd:dateTime",
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "modifiedOn",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#modifiedOn"
      ],
      "datatype": "xsd:dateTime",
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": false
    },
    {
      "fieldName": "createdBy",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#createdBy"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "modifiedBy",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#modifiedBy"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "emfParentOf",
      "propertyChain": [
            "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#parentOf"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "emfHasParent",
      "propertyChain": [
            "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasParent"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "isAttachedTo",
      "propertyChain": [
            "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isAttachedTo"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "hasAttachment",
      "propertyChain": [
            "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasAttachment"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "purpose",
      "propertyChain": [
            "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#purpose"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true
    },
    {
      "fieldName": "accessionNumber",
      "propertyChain": [
            "http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain#accessionNumber"
      ],
      "indexed": true,
      "stored": true,
      "datatype": "native:lowercase",
      "analyzed": true,
      "multivalued": true
    },
    {
      "fieldName": "objectId",
      "propertyChain": [
            "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#externalID"
      ],
      "indexed": true,
      "stored": true,
      "datatype": "native:lowercase",
      "analyzed": true,
      "multivalued": true
    },
    {
      "fieldName": "nonConformityType",
      "propertyChain": [
           "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#businessType"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true
    },
    {
      "fieldName": "department",
      "propertyChain": [
           "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#departmentType"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    {
      "fieldName": "creator",
      "propertyChain": [
            "http://purl.org/dc/terms/creator"
      ],
      "indexed": true,
      "stored": true,
      "datatype": "native:lowercase",
      "analyzed": true,
      "multivalued": false
    },
	{
      "fieldName": "revisionType",
      "propertyChain": [
             "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#revisionType"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "hasFavourite",
      "propertyChain": [
             "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasFavourite"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
	{
      "fieldName": "hasTag",
      "propertyChain": [
             "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasTag"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": false,
      "multivalued": true
    },
    
    
    {
      "fieldName": "facet_rdfType",
      "propertyChain": [
             "@rdfType"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_createdOn",
      "propertyChain": [
             "@createdOn"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_createdBy",
      "propertyChain": [
             "@createdBy"
      ],
      "indexed": false,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_modifiedOn",
      "propertyChain": [
             "@modifiedOn"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_modifiedBy",
      "propertyChain": [
             "@modifiedBy"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_assignee",
      "propertyChain": [
             "@assignee"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_hasTag",
      "propertyChain": [
             "@hasTag"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_isAttachedTo",
      "propertyChain": [
             "@isAttachedTo"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_mimetype",
      "propertyChain": [
             "@mimetype"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_owner",
      "propertyChain": [
             "@owner"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_plannedEndDate",
      "propertyChain": [
             "@plannedEndDate"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_priority",
      "propertyChain": [
             "@priority"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_startTime",
      "propertyChain": [
             "@createdOn"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_status",
      "propertyChain": [
             "@status"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    },
    {
      "fieldName": "facet_type",
      "propertyChain": [
             "@type"
      ],
      "indexed": true,
      "stored": false,
      "analyzed": false,
      "multivalued": false
    }
  ],
  "types": [
    "http://www.ontotext.com/proton/protontop#Happening",
    "http://www.ontotext.com/proton/protontop#Object",
    "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#ClassDescription"
  ],
  "entityFilter": "?isDeleted in (\\\"false\\\"^^xsd:boolean) && bound(?isDeleted)",
  "solrUrl": "{solrUrl}",
  "copyConfigsFrom": "collection1",
  "solrCore": "{coreName}",
  "manageCore": true,
  "manageSchema": true
}
''' .
}