PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
PREFIX chcart: <http://www.sirma.com/ontologies/2018/05/culturalHeritageConservationArtMuseums#>
delete {
    ?instance emf:type "FC236005"^^xsd:string .
    ?instance emf:definitionId "document"^^xsd:string .
} insert {
    graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
        ?instance emf:type "DAMDT06003"^^xsd:string .
        ?instance emf:definitionId "DAMDT06003"^^xsd:string .
    }
} where {
        ?instance chcart:subClassification "DAMDT06003"^^xsd:string .
}