PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
insert data {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
             rdfs:subClassOf skos:definition "Shows which class is sub class of current class"@en .	
             rdfs:domain skos:definition "Class in which current property is defined. Domain is used by SEP to filter the list of relations/object properties when searching by relations or creating relations."@en .
             rdfs:range skos:definition "Range is used to filter the list of relations/object properties when searching by relations or creating relations."@en .
             owl:inverseOf skos:definition "Specifies which relation is inverse to the current relation so we can track the inverse relations between objects"@en .
             rdfs:subPropertyOf skos:definition "Shows which property is sub property of current"@en .
    }
}