PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
        emf:Issue emf:classCategory "issue".
    }
}  where { }
