PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

insert data {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    
        xsd:string rdf:type emf:Primitive;
            rdfs:label "String"@en;
            rdfs:comment "Represents a string primitive"@en.
            
        xsd:int rdf:type emf:Primitive;
            rdfs:label "Integer"@en;
            rdfs:comment "Represents an integer primitive"@en.
            
        xsd:long rdf:type emf:Primitive;
            rdfs:label "Long"@en;
            rdfs:comment "Represents a long primitive"@en.
            
        xsd:float rdf:type emf:Primitive;
            rdfs:label "Float"@en;
            rdfs:comment "Represents a float primitive"@en.
            
        xsd:double rdf:type emf:Primitive;
            rdfs:label "Double"@en;
            rdfs:comment "Represents a double primitive"@en.
            
        xsd:date rdf:type emf:Primitive;
            rdfs:label "Date"@en;
            rdfs:comment "Represents a date primitive"@en.
            
        xsd:dateTime rdf:type emf:Primitive;
            rdfs:label "Date time"@en;
            rdfs:comment "Represents a date-time primitive"@en.
            
        xsd:boolean rdf:type emf:Primitive;
            rdfs:label "Boolean"@en;
            rdfs:comment "Represents a boolean primitive"@en.
    }
}