PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
insert data{
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
		<http://www.w3.org/2004/02/skos/core> rdfs:label "SKOS Vocabulary"@en .
		<http://purl.org/dc/terms/> rdfs:label "Dublin Core Terms Ontology"@en .
		<http://purl.org/dc/elements/1.1/> rdfs:label "Dublin Core Elements Ontology"@en .
		<http://www.w3.org/2002/07/owl> rdfs:label "Owl Ontology"@en .
		<http://www.w3.org/2000/01/rdf-schema> rdfs:label "RDF Schema Vocabulary"@en .
}
}