PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT DATA {
    GRAPH <http://www.sirma.com/ontologies/2014/11/security>{
        
		sec:allowInheritParentPermissions rdf:type owl:AnnotationProperty ;    
        	rdfs:label "Allow inherit parent permissions"@en,
					   "Позволи наследяване на права от родителя"@bg;
        	skos:definition "Indicates if a newly created instance from that class should inherit the permissions from its direct parent"@en ;      
        	dc:creator "Vilizar Tsonev"@en ; 
        	rdfs:range xsd:boolean .

		sec:allowInheritLibraryPermissions rdf:type owl:AnnotationProperty ;
        	rdfs:label "Allow inherit library permissions"@en,
					   "Позволи наследяване на права от библиотеката"@bg;
         	skos:definition "Indicates if a newly created instance from that class should inherit the permissions from the library"@en ;
         	dc:creator "Vilizar Tsonev"@en ;
         	rdfs:range xsd:boolean .
    }
}