PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
insert data {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:hasPoolAssignee  rdfs:label "Има потребители в пула"@bg ;
            emf:isSearchable "true"^^xsd:boolean .
        emf:isPoolAssigneeTo rdfs:label "Е добавен към пул"@bg ;
            emf:isSearchable "true"^^xsd:boolean .
    }
}