PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:defaultView rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "По подразбиране"@bg,
                       "Default view"@en;
            skos:definition "Default view"@en .
        emf:revisionNumber rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Ревизия номер"@bg,
                       "Revision number"@en;
            skos:definition "Revision number"@en .
        emf:ocrLanguage rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Език за OCR"@bg,
                       "OCR Language"@en;
            skos:definition "Ocr language"@en.
        emf:contentId rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Съдържание id"@bg,
                       "Content id"@en;
            skos:definition "Content id"@en.
        emf:actualEndDate rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Действителна крайна дата"@bg,
                       "Actual end date"@en;
            skos:definition "Actual end date"@en.
        emf:mobileNumber rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Мобилен телефон"@bg,
                       "Mobile number"@en;
            skos:definition "Mobile number"@en.
        emf:internationality rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Интернационалност"@bg,
                       "Internationality"@en;
            skos:definition "Internationality"@en.
        emf:isTopConcept rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Главна концепция"@bg,
                       "Is top concept"@en;
            skos:definition "Is top concept"@en.
        emf:templatePurpose rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Предназначение на шаблона"@bg,
                       "Template purpose"@en;
            skos:definition "Template purpose"@en.
        emf:isPrimaryTemplate rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Главен шаблон"@bg,
                       "Is primary template"@en;
            skos:definition "Is primary template"@en.
        emf:classCategory rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Категория"@bg,
                       "Class category"@en;
            skos:definition "Class category"@en.
        skos:prefLabel rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Предпочитан етикет"@bg,
                       "Preferred label"@en;
            skos:definition "Pref label"@en.
        skos:altLabel rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Alt наименование"@bg,
                       "Alt label"@en;
            skos:definition "Alt label"@en.
        dc:creator rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty;
            rdfs:label "Създател"@bg,
                       "Creator"@en;
            skos:definition "Creator"@en.
    }
}