
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasTemplate
        emf:hasTemplate rdf:type owl:ObjectProperty;
            rdfs:label "Има Темплейт"@bg ,
                "Has Template"@en ;
            emf:isSystemProperty "true"^^xsd:boolean ;
            emf:isSearchable "true"^^xsd:boolean ;
            dc:creator "Hristo Lungov"@en ;
            skos:definition "Links template instance with current instance"@en ;
            rdfs:range emf:Template ;
            rdfs:domain ptop:Entity .
    }
}