PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {

	###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#templateVersion          
		emf:templateVersion rdf:type owl:DatatypeProperty , emf:DefinitionDataProperty , emf:DefinitionProperty ;
                rdfs:label "Template version"@en ,
                           "Версия на приложения шаблон"@bg ;
            	emf:isSystemProperty "true"^^xsd:boolean ;
                dc:creator "Adrian Mitev"@en ;
                skos:definition "Version of the applied template"@en ;
                rdfs:range xsd:string ;
                rdfs:domain ptop:Entity .  
    }
}