PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {

        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#partOfOntology
		emf:partOfOntology rdf:type owl:AnnotationProperty ;
                 rdfs:label "Part of ontology"@en;
                 skos:definition "The ontology to which the class belongs to"@en ;
                 dc:creator "Vilizar Tsonev"@en .
    }
}