PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

insert {
graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
				
###  http://www.w3.org/2000/01/rdf-schema#label
rdfs:label rdf:type owl:AnnotationProperty ;
                 rdfs:label "Етикет"@bg ,
                            "Label"@en .

### http://www.w3.org/2000/01/rdf-schema#domain 
rdfs:domain rdf:type owl:AnnotationProperty ;
                 rdfs:label "Домейн"@bg ,
                            "Domain"@en .		

### http://www.w3.org/2000/01/rdf-schema#range 
rdfs:range rdf:type owl:AnnotationProperty ;
                 rdfs:label "Диапазон"@bg ,
                            "Range"@en .
        
### http://www.w3.org/2002/07/owl#inverseOf 
owl:inverseOf rdf:type owl:AnnotationProperty ;
                 rdfs:label "Обратното на"@bg ,
                            "Inverse of"@en .
        
### http://www.w3.org/1999/02/22-rdf-syntax-ns#type
rdf:type rdf:type owl:AnnotationProperty ;
                 rdfs:label "Тип"@bg ,
                            "Type"@en .
       
### http://www.w3.org/2000/01/rdf-schema#subPropertyOf 
rdfs:subPropertyOf rdf:type owl:AnnotationProperty ;
                 rdfs:label "Под пропърти на"@bg ,
                            "Sub property of"@en .
        
### http://www.w3.org/2004/02/skos/core#definition
skos:definition rdf:type owl:AnnotationProperty ;
                 rdfs:label "Описание"@bg ,
                            "Description"@en .
    }
}
where {}