# renames emf:DomainUser to Person for QVI 

PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
delete {
	emf:DomainUser rdfs:label ?label .	
} insert  {
	emf:DomainUser rdfs:label "Person"@en ;
	emf:isPartOfObjectLibrary "true"^^xsd:boolean .
} where {
	emf:DomainUser rdfs:label ?label .	
}