//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.31 at 12:56:11 PM EET
//

package com.sirma.itt.seip.template.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.sirma.itt.seip.definition.jaxb.ComplexFieldsDefinition;
import com.sirma.itt.seip.definition.jaxb.Labels;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fields" type="{}complexFieldsDefinition"/>
 *         &lt;element ref="{}labels" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{}idType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "fields", "labels" })
@XmlRootElement(name = "templateDefinition")
public class TemplateDefinition {

	/** The fields. */
	@XmlElement(required = true)
	protected ComplexFieldsDefinition fields;

	/** The labels. */
	protected Labels labels;

	/** The id. */
	@XmlAttribute(name = "id")
	protected String id;

	/**
	 * Gets the value of the fields property.
	 *
	 * @return possible object is {@link ComplexFieldsDefinition }
	 */
	public ComplexFieldsDefinition getFields() {
		if (fields == null) {
			fields = new ComplexFieldsDefinition();
		}
		return fields;
	}

	/**
	 * Sets the value of the fields property.
	 *
	 * @param value
	 *            allowed object is {@link ComplexFieldsDefinition }
	 */
	public void setFields(ComplexFieldsDefinition value) {
		fields = value;
	}

	/**
	 * Gets the value of the labels property.
	 *
	 * @return possible object is {@link Labels }
	 */
	public Labels getLabels() {
		return labels;
	}

	/**
	 * Sets the value of the labels property.
	 *
	 * @param value
	 *            allowed object is {@link Labels }
	 */
	public void setLabels(Labels value) {
		labels = value;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setId(String value) {
		id = value;
	}

}
