# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.9.5"

Vagrant.configure('2') do |config|

	config.vm.box = "centos/7"

	config.vm.network "private_network", ip: "172.17.8.101"
	config.vm.hostname = "zimbra-vm.com"

    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "provision/playbook.yml"
        ansible.config_file = 'provision-vagrant/ansible.cfg'
        ansible.vault_password_file = 'provision-vagrant/password.vault'
        ansible.extra_vars = '@provision-vagrant/vagrant-vars.yml'
    end

	config.vm.provider "virtualbox" do |vb|
	  vb.name = "zimbra-vm.com"

	  vb.memory = "4096"
	  vb.cpus = 2
	end

    config.vm.network "forwarded_port", guest: 8443, host: 8443
    config.vm.network "forwarded_port", guest: 7071, host: 7071

end
