PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>

INSERT DATA {

    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
		###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Email
		emf:Email rdf:type owl:Class ;
			rdfs:label "E-Mail"@en ,
                       "Електронно писмо"@bg ;
            rdfs:subClassOf emf:Document ;
            emf:isSearchable "true"^^xsd:boolean ;
            emf:isCreateable "true"^^xsd:boolean ;
            dc:creator "Stella Djulgerova"@en ;
            skos:definition "Represents email object in the system."@en ;
            emf:definitionId "objectinstance" ;
            emf:classCategory "email" ;
            sec:allowInheritParentPermissions "true"^^xsd:boolean .
    }
}