PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {

	GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
		###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mailboxAddress
		emf:mailboxAddress rdf:type owl:ObjectProperty ;
			rdfs:label "Email Address"@en,
					   "Електроннa поща"@bg ;
			skos:definition "Used to keep instance email address."@en ;
			emf:isSearchable "true"^^xsd:boolean ;
			dc:creator "Stella Djulgerova"@en ;
			rdfs:range ptop:Entity .
   	}
}