PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
  GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:User emf:isMailboxSupportable "true"^^xsd:boolean .
  }
}