PREFIX chd: <http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
insert data {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    
    emf:testField1Object rdf:type owl:DatatypeProperty ;
                      
                      rdfs:label "testField1Object"@en ;
                      
                      skos:definition "testField1Object"@en ;
                      
                      dc:creator "Kiril Penev"@en .
                      
        
        emf:testField2Object rdf:type owl:DatatypeProperty ;
                      
                      rdfs:label "testField2Object"@en ;
                      
                      skos:definition "testField2Object"@en ;
                      
                      dc:creator "Kiril Penev"@en .
                      
        
        emf:clFieldObject rdf:type owl:DatatypeProperty ;
                      
                      rdfs:label "clFieldObject"@en ;
                      
                      skos:definition "clFieldObject"@en ;
                      
                      dc:creator "Kiril Penev"@en .
                      
        
        emf:createdTOObject rdf:type owl:DatatypeProperty ;
                      
                      rdfs:label "createdTOObject"@en ;
                      
                      skos:definition "createdTOObject"@en ;
                      
                      dc:creator "Kiril Penev"@en ;
                      
                      rdfs:range xsd:dateTime .
                      
        
        emf:createdOnObject rdf:type owl:DatatypeProperty ;
                      
                      rdfs:label "createdOnObject"@en ;
                      
                      skos:definition "createdOnObject"@en ;
                      
                      dc:creator "Kiril Penev"@en ;
                      
                      rdfs:range xsd:dateTime .
    }
}