select ?class (group_concat(distinct ?data ; separator = "\n") AS ?objectPropertiesRelations)
	{
		?property rdfs:domain ?class .
		?property rdfs:range ?otherClass .
		?class rdfs:label ?classLabel .
		bind(if(lang(?classLabel) = '', "en", lang(?classLabel)) as ?classLabelLang) .
		filter(contains(?classLabelLang, "en")) .
		?otherClass rdfs:label ?otherClassLabel .
		bind(if(lang(?otherClassLabel) = '', "en", lang(?otherClassLabel)) as ?class1LabelLang) .
		filter(contains(?class1LabelLang, "en")) .
		?property a owl:ObjectProperty .
		#bind(if(contains(str(?property), "enterpriseManagementFramework"), "Enterprise Ontology - Classes and Properties", if(contains(str(?property), "proton"), "Proton Ontology - Classes and Properties", if(contains(str(?property), "skos"), "SKOS Ontology - Classes and Properties", if(contains(str(?property), "dc"), "Dublin Core Ontology - Classes and Properties", if(contains(str(?property), "culturalHeritageDomain"), "Cultural Object Ontology - Classes and Properties", if(contains(str(?property), "pdmConfiguration"), "Product Data Model Ontology - Classes and Properties", "")))))) as ?page) .
		bind(if(contains(str(?property), "#"), STRAFTER(str(?property), "#"), if(contains(str(?property), "dc/terms"), replace(str(?property), "http://purl.org/dc/terms/", ""),replace(str(?property), "http://purl.org/dc/elements/1.1/", ""))) as ?label) .
		bind(concat("\"", ?otherClassLabel, "\" o-- \"", ?classLabel, "\": ", ?label, "") as ?data) .
	}
	group by ?class 