PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
PREFIX chcart: <http://www.sirma.com/ontologies/2018/05/culturalHeritageConservationArtMuseums#>
delete {
    ?instance emf:hasTemplate emf:b75f358d-7f45-44dd-98eb-4880efc9c0bb .
} insert {
    graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
        ?instance emf:hasTemplate ?newTemplateId .
    }
} where {
	# Old Document Uploadable Default Template
    ?instance emf:hasTemplate emf:b75f358d-7f45-44dd-98eb-4880efc9c0bb .
	?instance chcart:subClassification ?oldSubType.
	?instance emf:contentId ?contentId .
    {
	# COREDT06002 Analysis Report Uploadable Template
        FILTER (?oldSubType = "COREDT06002"^^xsd:string).
        bind (emf:8163ae9a-87d5-4333-95cc-69204313e64c as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06003 Analysis Request Uploadable Template
        FILTER (?oldSubType = "COREDT06003"^^xsd:string).
        bind (emf:9c16eef1-3f38-4977-8a4e-3793643c5a91 as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06004 Article Uploadable Template
        FILTER (?oldSubType = "COREDT06004"^^xsd:string).
        bind (emf:e00dc898-0e7e-4cbc-991d-4d162160e27d as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06005 Artist Interview Uploadable Template
        FILTER (?oldSubType = "COREDT06005"^^xsd:string).
        bind (emf:12f84ce2-2cb7-414b-b30e-7a57161b8442 as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06006 Blank Uploadable Template
        FILTER (?oldSubType = "COREDT06006"^^xsd:string).
        bind (emf:e050842c-e9a2-4977-9367-4d4188b68e27 as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06007 Condition Report Uploadable Objects
        FILTER (?oldSubType = "COREDT06007"^^xsd:string).
        bind (emf:faf66947-453a-4ea8-af22-f27fbc6eae3c as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06008 Contract Uploadable Template
        FILTER (?oldSubType = "COREDT06008"^^xsd:string).
        bind (emf:8552444b-5503-4245-8d23-c738f6300e40 as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06009 Correspondence Uploadable Template
        FILTER (?oldSubType = "COREDT06009"^^xsd:string).
        bind (emf:c598dbd0-80f1-474a-a657-a86a4e09c448 as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06011 Examination Report Uploadable Template
        FILTER (?oldSubType = "COREDT06011"^^xsd:string).
        bind (emf:3470137b-eecc-4b2a-9045-ff779858ccc7 as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06012 Invoice Uploadable Template
        FILTER (?oldSubType = "COREDT06012"^^xsd:string).
        bind (emf:e29350a8-6120-49b4-9b39-f69d87c5d716 as ?newTemplateId) .
    } UNION {
	# COREDT06014 Notes Uploadable Template
        FILTER (?oldSubType = "COREDT06014"^^xsd:string).
        bind (emf:224a4957-f0df-45f1-b705-4a160f884be5 as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06015 Research Uploadable Template
        FILTER (?oldSubType = "COREDT06015"^^xsd:string).
        bind (emf:b42d0501-38fa-4de0-b528-75aa9e1776fe as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06016 Survey Uploadable Template
        FILTER (?oldSubType = "COREDT06016"^^xsd:string).
        bind (emf:d3255be6-b425-422e-85f1-e353b77889af as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    } UNION {
	# COREDT06019 Treatment Report Uploadable Template
        FILTER (?oldSubType = "COREDT06019"^^xsd:string).
        bind (emf:06929a7c-ebd2-4425-8fed-0ba2666f2d79 as ?newTemplateId) .
		?instance emf:contentId ?contentId .
    }
}	