PluginRegistry.add('actions',
  [{
    name: 'createInstanceAction',
    component: 'create-instance',
    module: 'idoc/actions/create-instance-action',
    forceRefresh: true
  }, {
    name: 'saveIdocAndPreviewAction',
    eventId: 'SaveIdocAndPreviewAction',
    label: 'idoc.action.save',
    handler: 'SaveIdocAndPreviewAction',
    module: 'idoc/actions/save-idoc-and-preview-action'
  }, {
    name: 'saveIdocAndContinueAction',
    eventId: 'SaveIdocAndContinueAction',
    label: 'idoc.action.save.continue',
    handler: 'SaveIdocAndContinueAction',
    module: 'idoc/actions/save-idoc-and-continue-action'
  }, {
    name: 'cancelSaveIdocAction',
    eventId: 'CancelSaveIdocAction',
    label: 'idoc.action.cancel',
    handler: 'CancelSaveIdocAction',
    module: 'idoc/actions/cancel-save-idoc-action'
  }, {
    name: 'editIdocAction',
    eventId: 'EditIdocAction',
    label: 'idoc.action.edit',
    handler: 'EditIdocAction',
    module: 'idoc/actions/edit-idoc-action'
  }, {
    name: 'cloneAction',
    module: 'idoc/actions/clone-action',
    forceRefresh: true
  }, {
    name: 'changeTypeAction',
    module: 'idoc/actions/change-type/change-type-action',
    forceRefresh: true
  }, {
    name: 'deleteAction',
    module: 'idoc/actions/delete-action',
    forceRefresh: true
  }, {
    name: 'transitionAction',
    module: 'idoc/actions/transition-action',
    forceRefresh: true
  }, {
    name: 'dummyAction',
    module: 'idoc/actions/dummy-action'
  }, {
    name: 'downloadAction',
    module: 'idoc/actions/download-action'
  }, {
    name: 'moveAction',
    module: 'idoc/actions/move-action',
    forceRefresh: true
  }, {
    name: 'uploadNewVersionAction',
    module: 'idoc/actions/upload/upload-new-version-action',
    forceRefresh: true
  }, {
    name: 'lockAction',
    module: 'idoc/actions/lock-action',
    forceRefresh: true
  }, {
    name: 'unlockAction',
    module: 'idoc/actions/unlock-action',
    forceRefresh: true
  }, {
    name: 'addThumbnailAction',
    module: 'idoc/actions/add-thumbnail-action',
    forceRefresh: true
  }, {
    name: 'editDetailsAction',
    module: 'idoc/actions/edit-details-action'
  }, {
    name: 'addRelationAction',
    module: 'idoc/actions/add-relation-action',
    forceRefresh: true
  }, {
    name: 'managePermissionsAction',
    module: 'idoc/actions/manage-permissions-action'
  }, {
    name: 'printAction',
    module: 'idoc/actions/print-action'
  }, {
    name: 'printTabAction',
    module: 'idoc/actions/print-tab-action',
    notApplicable: ['search', 'recent-objects', 'widget']
  }, {
    name: 'exportTabPDFAction',
    module: 'idoc/actions/export-tab-pdf-action',
    notApplicable: ['search', 'recent-objects', 'widget']
  }, {
    name: 'exportPDFAction',
    module: 'idoc/actions/export-pdf-action'
  }, {
    name: 'exportWordAction',
    module: 'idoc/actions/export-word-action'
  }, {
    name: 'exportTabWordAction',
    module: 'idoc/actions/export-tab-word-action',
    notApplicable: ['search', 'recent-objects', 'widget']
  }, {
    name: 'addIconsAction',
    module: 'idoc/actions/add-icons-action'
  }, {
    name: 'openAction',
    module: 'idoc/actions/open-action'
  }, {
    name: 'bpmTransitionAction',
    module: 'idoc/actions/bpm-action',
    forceRefresh: true
  }, {
    name: 'bpmStartAction',
    module: 'idoc/actions/bpm-start-action',
    forceRefresh: true
  }, {
    name: 'bpmStopAction',
    module: 'idoc/actions/bpm-stop-action',
    forceRefresh: true
  }, {
    name: 'bpmReleaseAction',
    module: 'idoc/actions/bpm-release-action',
    forceRefresh: true
  }, {
    name: 'bpmClaimAction',
    module: 'idoc/actions/bpm-claim-action',
    forceRefresh: true
  }, {
    name: 'publishAction',
    module: 'idoc/actions/publish-action',
    forceRefresh: true
  }, {
    name: 'publishAsPdfAction',
    module: 'idoc/actions/publish-as-pdf-action',
    forceRefresh: true
  }, {
    name: 'uploadRevisionAction',
    module: 'idoc/actions/upload/upload-revision-action',
    forceRefresh: true
  }, {
    name: 'importFileAction',
    module: 'idoc/actions/import-file-action'
  }, {
    name: 'composeEmailAction',
    module: 'idoc/actions/compose-email-action'
  }, {
    name: 'revertVersionAction',
    module: 'idoc/actions/revert-version-action'
  }, {
    name: 'editOfflineAction',
    module: 'idoc/actions/edit-offline-action'
  }, {
    name: 'changeTemplateAction',
    module: 'idoc/actions/change-template-action'
  }, {
    name: 'noAllowedAction',
    module: 'idoc/actions/no-allowed-action'
  }]
);
