PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
select (group_concat(distinct ?uri; separator = ",") as ?classes) where {
  ?class rdfs:subClassOf emf:DomainObject .
  bind(str(?class) as ?uri)
  }