DELETE {
    GRAPH ?annotationsDataGraph {
        ?annotation ?p ?o.
    }
}
WHERE {
    GRAPH ?annotationsDataGraph {
        ?annotation a oa:Annotation.
        ?annotation ?p ?o.
        ?annotation emf:commentsOn ?commentsOn.
        ?annotation oa:hasTarget ?hasTarget.
    }
}