PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX yul: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation/YUL#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#> 
DELETE {
	 GRAPH <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation/YUL> {
		yul:Activity sec:allowInheritParentPermissions "false"^^xsd:boolean .
		yul:Activity sec:allowInheritLibraryPermissions "true"^^xsd:boolean .
			
		}
}
INSERT {
    GRAPH <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation/YUL> {
		yul:Activity sec:allowInheritParentPermissions "true"^^xsd:boolean .
		yul:Activity sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
    }
}
WHERE {
    
}