PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
PREFIX chcart: <http://www.sirma.com/ontologies/2018/05/culturalHeritageConservationArtMuseums#>
delete {
    ?instance emf:hasTemplate ?oldTemplateId .
} insert {
    graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
        ?instance emf:hasTemplate ?newTemplateId .
    }
} where {
    ?instance emf:hasTemplate ?oldTemplateId .
    {
	# COREDT06001 Accident/Damage Report Template 
        FILTER (?oldTemplateId = emf:03bea27b-e48f-4e12-ab6e-8190a318634e).
        bind (emf:78d645a6-9e1c-4526-889a-b9e2e58e2db4 as ?newTemplateId) .
    } UNION {
	# COREDT06002 Analysis Report for Commercial Product Template
        FILTER (?oldTemplateId = emf:183c0302-ba69-438e-b82a-0d23234dc279).
        bind (emf:1262a9a1-b9f1-4171-90b0-3f4786141143 as ?newTemplateId) .
    } UNION {
	# COREDT06002 Analysis Report for Work of Art Template
        FILTER (?oldTemplateId = emf:2d3d8382-c77c-48ec-8582-37d86971a46b).
        bind (emf:090c02e2-1ed9-4b6e-bb55-ab0837ea806c as ?newTemplateId) .
    } UNION {
	# COREDT06003 Analysis Request Template
        FILTER (?oldTemplateId = emf:12484e7a-c5cc-4cf3-839c-1e7ea5e13481).
        bind (emf:c738122e-5365-4f94-9d1c-45d045d85d61 as ?newTemplateId) .
    } UNION {
	# COREDT06004 Article Template
        FILTER (?oldTemplateId = emf:b9a26064-e185-47c1-9108-d22a7f3355d9).
        bind (emf:3b410872-c73e-4b53-bf2d-ed0724653733 as ?newTemplateId) .
    } UNION {
	# COREDT06005 Artist Interview Template
        FILTER (?oldTemplateId = emf:4bbf90ab-40aa-4cc3-8804-65d94d208a14).
        bind (emf:4ca3bb34-581d-4411-a273-a82cc81f9401 as ?newTemplateId) .
    } UNION {
	# COREDT06006 Blank Template
        FILTER (?oldTemplateId = emf:f760f172-f87b-4508-8072-80e14053fc0b).
        bind (emf:8e853ab2-bd21-46bc-84af-aed5ddb6da6f as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Multiple Objects
        FILTER (?oldTemplateId = emf:4408032b-66e1-442b-b1f5-0dd156d0d946).
        bind (emf:fcbdce72-8cea-4c7a-b87c-594dd1be9137 as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Outgoing Loan Bound Volume Template
        FILTER (?oldTemplateId = emf:df517d78-7917-49b4-a18c-54fc18bde21e).
        bind (emf:70fcd458-80fc-4b26-8522-01d4f9772c0e as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Outgoing Loan Drawing Template
        FILTER (?oldTemplateId = emf:e0d990a1-4eda-47b3-8fa1-5a63c78ee13d).
        bind (emf:3a00fb74-46e8-4a1d-9982-8801576bbba1 as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Outgoing Loan Multiple Template
        FILTER (?oldTemplateId = emf:a5dfe05c-d245-4d14-b635-e216d7657ea5).
        bind (emf:cead48d7-575b-4cc7-858c-10c60707268a as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Outgoing Loan Painting Template
        FILTER (?oldTemplateId = emf:28dc9403-f365-44d7-94eb-d872d7463a82).
        bind (emf:5777afad-0403-40e9-89ff-3a743ae15f52 as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Outgoing Loan Photograph Template
        FILTER (?oldTemplateId = emf:7b77ebea-e2c4-4e55-9a17-4318eb964f85).
        bind (emf:27efbb75-6f7e-4ba4-be36-d84f5808875d as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Outgoing Loan Print Template
        FILTER (?oldTemplateId = emf:2144b2a4-4850-41ca-a556-0c89dbcb593f).
        bind (emf:a265683c-c315-4510-b033-a88ea7820606 as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Outgoing Loan Sculpture Template
        FILTER (?oldTemplateId = emf:8e9c0ee5-8f2a-4955-a134-030db044129d).
        bind (emf:095812aa-174d-4424-98a9-50ba140a57f2 as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Painting Template
        FILTER (?oldTemplateId = emf:b2b657bc-e733-4c1b-9316-5a31296087e5).
        bind (emf:0c253696-f672-432d-a65a-eee6941232e6 as ?newTemplateId) .
    } UNION {
	# COREDT06007 Condition Report Template
        FILTER (?oldTemplateId = emf:04db2154-ac85-4c23-93cb-4bd6b72ca1da).
        bind (emf:346bb7f1-7f6b-4525-bf97-ca6ae7eacab5 as ?newTemplateId) .
    } UNION {
	# COREDT06008 Contract Template
        FILTER (?oldTemplateId = emf:f647a468-09ae-4138-b0bd-f72451dd37ae).
        bind (emf:8f3638e7-b162-42b0-b7dc-5803830cd735 as ?newTemplateId) .
    } UNION {
	# COREDT06009 Correspondence Template
        FILTER (?oldTemplateId = emf:4dcc1b66-e6d2-447e-bede-345d169f5f91).
        bind (emf:80131cf3-6b44-4b34-aed7-a1af5d35f3a7 as ?newTemplateId) .
    } UNION {
	# COREDT06010 Data Report Template
        FILTER (?oldTemplateId = emf:a63eb04e-18c0-4a9e-9168-be1834fc94f7).
        bind (emf:dd7f45f1-503e-4c25-aa46-cedeb5af4280 as ?newTemplateId) .
    } UNION {
	# COREDT06011 Examination of Multiple Object Report Template
        FILTER (?oldTemplateId = emf:02b94408-ae07-4c1b-94a4-7605417b79f0).
        bind (emf:11276fde-8ef1-48e2-bf69-7e5561d74ed9 as ?newTemplateId) .
    } UNION {
	# COREDT06011 Examination Report Bound Volume Template
        FILTER (?oldTemplateId = emf:35e5f792-44f2-4340-8891-3266293c4f93).
        bind (emf:855eb663-5359-49f1-a0fe-2d513a3fd784 as ?newTemplateId) .
    } UNION {
	# COREDT06011 Examination Report Drawing Template
        FILTER (?oldTemplateId = emf:096434f6-f28b-4062-9925-e7d11f7bcfe2).
        bind (emf:85e91a8f-2040-4623-8675-dbf18f1db018 as ?newTemplateId) .
    } UNION {
	# COREDT06011 Examination Report of Painting Template
        FILTER (?oldTemplateId = emf:2547c442-0ab6-4db2-9b66-1d0ee192a806).
        bind (emf:0e75e4c4-533b-40bc-b9ff-2da96fe8375f as ?newTemplateId) .
    } UNION {
	# COREDT06011 Examination Report Photograph Template
        FILTER (?oldTemplateId = emf:ad7eda3c-3f0f-4c38-9a32-9331b2420e4f).
        bind (emf:dd9b933a-b231-489c-98b7-49c309106828 as ?newTemplateId) .
    } UNION {
	# COREDT06011 Examination Report Print Template
        FILTER (?oldTemplateId = emf:300b67b8-b671-4c1a-9b4e-4311e4de4a8d).
        bind (emf:842d3e72-b077-4270-807b-98dea08a1127 as ?newTemplateId) .
    } UNION {
	# COREDT06011 Examination Report Sculpture Template
        FILTER (?oldTemplateId = emf:8fc4dcc9-9d5d-447d-b8ba-80c7a488d984).
        bind (emf:087999a3-f062-4c0e-8ba9-5565b285c3f1 as ?newTemplateId) .
    } UNION {
	# COREDT06011 Examination Report Template
        FILTER (?oldTemplateId = emf:f05dfb81-10fb-48a8-9748-df87136c90be).
        bind (emf:237b8f4e-2813-4877-a6e2-cbc766c226ce as ?newTemplateId) .
    } UNION {
	# COREDT06012 Invoice Template
        FILTER (?oldTemplateId = emf:6fc6fbdf-c7a3-4920-8207-179d24a0c62e).
        bind (emf:7f0bb91e-8e4e-4e28-a705-1824551133ff as ?newTemplateId) .
    } UNION {
	# COREDT06013 Loan Document Template
        FILTER (?oldTemplateId = emf:ce6614ba-2ef8-4f1c-96f6-005197bd6a14).
        bind (emf:25f3ae9c-1464-4e2d-9a6a-679952a6c144 as ?newTemplateId) .
    } UNION {
	# COREDT06014 Note Template
        FILTER (?oldTemplateId = emf:e38df8cf-3ded-473d-be0a-7796b114de53).
        bind (emf:442f2d34-8a51-40d1-8d3d-490701dccdbd as ?newTemplateId) .
    } UNION {
	# COREDT06015 Research Template
        FILTER (?oldTemplateId = emf:61b834ea-dc4a-4ad9-afe6-3b7e53e0e029).
        bind (emf:489f3e4d-7f7e-4b65-aee8-aefd2c9801f9 as ?newTemplateId) .
    } UNION {
	# COREDT06016 Survey Template	
        FILTER (?oldTemplateId = emf:edaaab0b-e282-47dd-b09a-f6fa4bb970ea).
        bind (emf:abae2994-5aa3-4442-9862-4bbaf6ebcf90 as ?newTemplateId) .
    } UNION {
	# COREDT06017 Technical Examination Bound Volume Template
        FILTER (?oldTemplateId = emf:c67f2a70-ec55-4c22-896f-c934ff0890f4).
        bind (emf:e6e8a5ba-fb8c-4554-a8ef-386acaf488a2 as ?newTemplateId) .
    } UNION {
	# COREDT06017 Technical Examination Drawing Template
        FILTER (?oldTemplateId = emf:14e1bd96-76b7-4273-8943-b1c50f9b5c50).
        bind (emf:fd681775-e721-4810-b9a6-d4f020b64fae as ?newTemplateId) .
    } UNION {
	# COREDT06017 Technical Examination of Multiple Object Report Template
        FILTER (?oldTemplateId = emf:e478f65b-c9e8-4564-9b9b-ad72a8f2c032).
        bind (emf:f45af550-9758-40be-b0ae-e2d11b850f4d as ?newTemplateId) .
    } UNION {
	# COREDT06017 Technical Examination Painting Template
        FILTER (?oldTemplateId = emf:c7b49370-e6d2-4b10-9db8-72001b575442).
        bind (emf:dfddabdf-9420-4204-8382-636121127db6 as ?newTemplateId) .
    } UNION {
	# COREDT06017 Technical Examination Photograph Template
        FILTER (?oldTemplateId = emf:f0af60f8-8a02-48b5-887b-ef9b72513fc3).
        bind (emf:e8cf5d40-4b81-4bfc-8ded-2160799d226f as ?newTemplateId) .
    } UNION {
	# COREDT06017 Technical Examination Print Template
        FILTER (?oldTemplateId = emf:21369170-5221-458b-a0e8-d3c2ac14a5fc).
        bind (emf:77ce156f-8b90-4a49-ab24-f20760c86124 as ?newTemplateId) .
    } UNION {
	# COREDT06017 Technical Examination Sculpture Template
        FILTER (?oldTemplateId = emf:b6a4b4ff-facc-45b0-8e77-4e9abda72a6f).
        bind (emf:f0e03422-3194-4cb7-9efa-ef45875618fc as ?newTemplateId) .
    } UNION {
	# COREDT06017 Technical Examination Template
        FILTER (?oldTemplateId = emf:3641bf9e-81ba-4714-95e0-71a5074c3ee0).
        bind (emf:a7b7744a-26ef-43d7-be0e-43739c725076 as ?newTemplateId) .
    } UNION {
	# COREDT06018 Treatment Proposal Multiple Objects Template
        FILTER (?oldTemplateId = emf:4ed69022-c0d9-4e61-bdab-f5f5ccbf592b).
        bind (emf:ec4816e5-abb4-4449-b5bb-e119f6b5053c as ?newTemplateId) .
    } UNION {
	# COREDT06018 Treatment Proposal Single Object Template
        FILTER (?oldTemplateId = emf:1c1b50cd-95c7-4425-9c59-e722815c6f8b).
        bind (emf:fd30be59-1c21-4d73-be5f-27c5f93b58c3 as ?newTemplateId) .
    } UNION {
	# COREDT06018 Treatment Proposal Template
        FILTER (?oldTemplateId = emf:8e62d07a-dd9d-4e1f-9071-1c11f6f1be7f).
        bind (emf:13a54d9b-9754-4f59-8c3e-41fd5fbd8c48 as ?newTemplateId) .
    } UNION {
	# COREDT06019 Treatment Report Multiple Objects Template
        FILTER (?oldTemplateId = emf:15a990b2-25cc-4ab9-be3e-7ceef3484574).
        bind (emf:a7358962-6652-45b5-88cf-f1ce7716abbd as ?newTemplateId) .
    } UNION {
	# COREDT06019 Treatment Report Single Object Template
        FILTER (?oldTemplateId = emf:a13a10de-dd37-489e-b1af-005c81a7b6f5).
        bind (emf:79b2a8a0-e156-461c-99eb-1db8bd08f623 as ?newTemplateId) .
    } UNION {
	# VGM_Condition_report Template
        FILTER (?oldTemplateId = emf:2b108e71-6f9f-4d83-b17a-e3729e2846b8).
        bind (emf:e2d445e3-8b5a-446f-8e93-549c2d416f43 as ?newTemplateId) .
    } UNION {
	# Condition Report Painting Template + Image Template
        FILTER (?oldTemplateId = emf:f94450e1-2cf2-4693-9844-5fb57e767e39).
        bind (emf:5640a431-3ae0-404f-b47a-2f0b9c62eea6 as ?newTemplateId) .
    }
}