{
	{
	    ?currentUser sec:assignedTo ?permissionsRole
	} UNION {
	    ?currentUser emf:isMemberOf ?group  .
	    ?group sec:assignedTo ?permissionsRole
	}
	{
		?permissionsRole sec:hasPermission %instance% .
		FILTER(NOT EXISTS {
		    ?permissionsRole sec:hasRoleType conc:SecurityRoleTypes-Forbidden
		})
	} UNION {
		?permissionsRole sec:isManagerOf %instance% .
	}
} UNION {
	sec:SYSTEM_ALL_OTHER_USERS sec:assignedTo ?permissionsRole .
	{
		?permissionsRole sec:hasPermission %instance% .
		FILTER(not exists {
	        ?permissionsRole sec:hasRoleType conc:SecurityRoleTypes-Forbidden
	    })
    } UNION {
		?permissionsRole sec:isManagerOf %instance% .
	}
}
FILTER (NOT EXISTS {
	?currentUser sec:assignedTo ?noPermissionRole .
    ?noPermissionRole sec:hasPermission %instance% .
    ?noPermissionRole sec:hasRoleType conc:SecurityRoleTypes-Forbidden
})