PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
        
        emf:queriesContentId rdf:type owl:DatatypeProperty , emf:DefinitionDataProperty , emf:DefinitionProperty ;
            rdfs:label "Queries content id"@en ;
            dc:creator "Tony Kunchev"@en ;
            skos:definition "System property that is used to store the id of the content of the queries for different instances versions."@en ;
            rdfs:domain ptop:Entity .
        
        emf:queriesResultContentId rdf:type owl:DatatypeProperty , emf:DefinitionDataProperty , emf:DefinitionProperty ;
            rdfs:label "Queries results content id"@en ;
            dc:creator "Tony Kunchev"@en ;
            skos:definition "System property that is used to store the result of the queries execution. The results are stored as content and this property contains id of this content."@en ;
            rdfs:domain ptop:Entity .
    }
}