PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX chd: <http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

INSERT DATA {
	GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{

    	emf:isVersionable rdf:type owl:AnnotationProperty ;
                     	rdfs:label "Is versionable"@en ;
                     	skos:definition "Used as marker to show if instance is versionable or not. Primary used in content versioning."@en ;
                    	dc:creator "Tony Kunchev"@en ;
                     	rdfs:range xsd:boolean .
   	}
}