PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
delete {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
        emf:User emf:definitionId "user".
        emf:Group emf:definitionId "group".
    }
}
insert {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
    	emf:User emf:definitionId "objectinstance".
        emf:Group emf:definitionId "objectinstance".
    }
}
where {
    
}