PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
DELETE {
    ?instance emf:instanceType "classinstance" . 
}
WHERE {
    ?instance a owl:Class
}