PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
delete {
    GRAPH<http://ittruse.ittbg.com/data/enterpriseManagementFramework>{
        ?instance emf:instanceType "user".
    }
}
insert {
    GRAPH<http://ittruse.ittbg.com/data/enterpriseManagementFramework>{
        ?instance emf:instanceType "objectinstance".
    }
}
where {
    ?instance a emf:User.
    ?instance emf:instanceType "user".
}