PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE data {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:hasRevision	rdfs:subPropertyOf emf:parentOf
    }
}