PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
delete{
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {      
        emf:DataImportReport emf:isCreateable "true"^^xsd:boolean .
    }
}
insert{
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {       
        emf:DataImportReport emf:isCreateable "false"^^xsd:boolean .
    }
}where{}