PluginRegistry.add('model-management-attribute', [
  {
    'order': 10,
    'name': 'model-string-attribute',
    'type': 'string',
    'component': 'model-string-attribute',
    'module': 'administration/model-management/components/attributes/string/model-string-attribute'
  }, {
    'order': 20,
    'name': 'model-multi-lang-string-attribute',
    'type': 'multiLangString',
    'component': 'model-label-attribute',
    'module': 'administration/model-management/components/attributes/label/model-label-attribute'
  }, {
    'order': 30,
    'name': 'model-label-attribute',
    'type': 'label',
    'component': 'model-label-attribute',
    'module': 'administration/model-management/components/attributes/label/model-label-attribute'
  }, {
    'order': 40,
    'name': 'model-boolean-attribute',
    'type': 'boolean',
    'component': 'model-boolean-attribute',
    'module': 'administration/model-management/components/attributes/bool/model-boolean-attribute'
  }, {
    'order': 50,
    'name': 'model-option-attribute',
    'type': 'option',
    'component': 'model-option-attribute',
    'module': 'administration/model-management/components/attributes/option/model-option-attribute'
  }, {
    'order': 60,
    'name': 'model-source-attribute',
    'type': 'source',
    'component': 'model-source-attribute',
    'module': 'administration/model-management/components/attributes/source-attr/model-source-attribute'
  }, {
    'order': 70,
    'name': 'model-constraint-attribute',
    'type': 'type',
    'component': 'model-constraint-attribute',
    'module': 'administration/model-management/components/attributes/constraint/model-constraint-attribute'
  }, {
    'order': 80,
    'name': 'model-codelist-attribute',
    'type': 'codeList',
    'component': 'model-codelist-attribute',
    'module': 'administration/model-management/components/attributes/codelist/model-codelist-attribute'
  }, {
    'order': 90,
    'name': 'model-field-type-attribute',
    'type': 'typeOption',
    'component': 'model-field-type-attribute',
    'module': 'administration/model-management/components/attributes/type/model-field-type-attribute'
  }, {
    'order': 100,
    'name': 'model-property-type-attribute',
    'type': 'propertyType',
    'component': 'model-property-type-attribute',
    'module': 'administration/model-management/components/attributes/type/model-property-type-attribute'
  }, {
    'order': 110,
    'name': 'model-number-attribute',
    'type': 'integer',
    'component': 'model-number-attribute',
    'module': 'administration/model-management/components/attributes/number/model-number-attribute'
  }, {
    'order': 120,
    'name': 'model-codevalue-attribute',
    'type': 'codeValue',
    'component': 'model-codevalue-attribute',
    'module': 'administration/model-management/components/attributes/codevalue/model-codevalue-attribute'
  }, {
    'order': 130,
    'name': 'model-value-attribute',
    'type': 'value',
    'component': 'model-value-attribute',
    'module': 'administration/model-management/components/attributes/value/model-value-attribute'
  }, {
    'order': 140,
    'name': 'model-domain-attribute',
    'type': 'domain',
    'component': 'model-domain-attribute',
    'module': 'administration/model-management/components/attributes/domain/model-domain-attribute'
  }, {
    'order': 150,
    'name': 'model-range-attribute',
    'type': 'range',
    'component': 'model-range-attribute',
    'module': 'administration/model-management/components/attributes/range/model-range-attribute'
  }
]);