//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.5-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.11.05 at 02:34:28 PM EET
//

package com.sirma.itt.cmf.beans.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.sirma.itt.cmf.beans.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes
	 * for package: com.sirma.itt.cmf.beans.jaxb
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link TemplateDefinition }.
	 * 
	 * @return the template definition
	 */
	public TemplateDefinition createTemplateDefinition() {
		return new TemplateDefinition();
	}

	/**
	 * Create an instance of {@link CaseDefinition }.
	 * 
	 * @return the case definition
	 */
	public CaseDefinition createCaseDefinition() {
		return new CaseDefinition();
	}

	/**
	 * Create an instance of {@link SectionsDefinition }.
	 * 
	 * @return the sections definition
	 */
	public SectionsDefinition createSectionsDefinition() {
		return new SectionsDefinition();
	}

	/**
	 * Create an instance of {@link WorkflowDefinition }.
	 * 
	 * @return the workflow definition
	 */
	public WorkflowDefinition createWorkflowDefinition() {
		return new WorkflowDefinition();
	}

	/**
	 * Create an instance of {@link TasksDefinition }.
	 * 
	 * @return the tasks definition
	 */
	public TaskDefinitions createTaskDefinitions() {
		return new TaskDefinitions();
	}

	/**
	 * Create an instance of {@link DocumentDefinitions }.
	 * 
	 * @return the document definitions
	 */
	public DocumentDefinitions createDocumentDefinitions() {
		return new DocumentDefinitions();
	}

	/**
	 * Create an instance of {@link DocumentDefinition }.
	 * 
	 * @return the document definition
	 */
	public DocumentDefinition createDocumentDefinition() {
		return new DocumentDefinition();
	}

	/**
	 * Create an instance of {@link TaskDefinition }.
	 * 
	 * @return the task definition
	 */
	public TaskDefinition createTaskDefinition() {
		return new TaskDefinition();
	}

	/**
	 * Create an instance of {@link SectionDefinition }.
	 * 
	 * @return the section definition
	 */
	public SectionDefinition createSectionDefinition() {
		return new SectionDefinition();
	}

	/**
	 * Create an instance of {@link Definition }.
	 * 
	 * @return the definition
	 */
	public Definition createDefinition() {
		return new Definition();
	}

	/**
	 * Create an instance of {@link SubDefinitionType }.
	 * 
	 * @return the sub definition type
	 */
	public SubDefinitionType createSubDefinitionType() {
		return new SubDefinitionType();
	}
}
