//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.24 at 01:57:10 PM EET
//

package com.sirma.itt.cmf.beans.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.sirma.itt.emf.definition.model.jaxb.AllowedChildrenType;
import com.sirma.itt.emf.definition.model.jaxb.ComplexFieldsDefinition;
import com.sirma.itt.emf.definition.model.jaxb.RegionsDefinition;
import com.sirma.itt.emf.definition.model.jaxb.StateTransitionsDefinition;
import com.sirma.itt.emf.definition.model.jaxb.TransitionsDefinition;

/**
 * <p>
 * Java class for taskDefinition complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="taskDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fields" type="{}complexFieldsDefinition" minOccurs="0"/>
 *         &lt;element name="regions" type="{}regionsDefinition" minOccurs="0"/>
 *         &lt;element name="transitions" type="{}transitionsDefinition" minOccurs="0"/>
 *         &lt;element name="stateTransitions" type="{}stateTransitionsDefinition" minOccurs="0"/>
 *         &lt;element name="allowedChildren" type="{}allowedChildrenType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{}idType" />
 *       &lt;attribute name="purpose" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="referenceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="saveCondition" type="{}expressionType" />
 *       &lt;attribute name="standalone" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="dmsType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isAbstract" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "taskDefinition", propOrder = { "fields", "regions", "transitions",
		"stateTransitions", "allowedChildren" })
public class TaskDefinition {

	/** The fields. */
	protected ComplexFieldsDefinition fields;

	/** The regions. */
	protected RegionsDefinition regions;

	/** The transitions. */
	protected TransitionsDefinition transitions;

	/** The state transitions. */
	protected StateTransitionsDefinition stateTransitions;

	/** The allowed children. */
	protected AllowedChildrenType allowedChildren;

	/** The id. */
	@XmlAttribute(name = "id", required = true)
	protected String id;

	/** The purpose. */
	@XmlAttribute(name = "purpose")
	protected String purpose;

	/** The parent id. */
	@XmlAttribute(name = "parentId")
	protected String parentId;

	/** The reference id. */
	@XmlAttribute(name = "referenceId")
	protected String referenceId;

	/** The save condition. */
	@XmlAttribute(name = "saveCondition")
	protected String saveCondition;

	/** The standalone. */
	@XmlAttribute(name = "standalone")
	protected Boolean standalone;

	/** The dms type. */
	@XmlAttribute(name = "dmsType")
	protected String dmsType;

	/** The is abstract. */
	@XmlAttribute(name = "isAbstract")
	protected Boolean isAbstract;

	/**
	 * Gets the value of the fields property.
	 * 
	 * @return possible object is {@link ComplexFieldsDefinition }
	 */
	public ComplexFieldsDefinition getFields() {
		return fields;
	}

	/**
	 * Sets the value of the fields property.
	 * 
	 * @param value
	 *            allowed object is {@link ComplexFieldsDefinition }
	 */
	public void setFields(ComplexFieldsDefinition value) {
		this.fields = value;
	}

	/**
	 * Gets the value of the regions property.
	 * 
	 * @return possible object is {@link RegionsDefinition }
	 */
	public RegionsDefinition getRegions() {
		return regions;
	}

	/**
	 * Sets the value of the regions property.
	 * 
	 * @param value
	 *            allowed object is {@link RegionsDefinition }
	 */
	public void setRegions(RegionsDefinition value) {
		this.regions = value;
	}

	/**
	 * Gets the value of the transitions property.
	 * 
	 * @return possible object is {@link TransitionsDefinition }
	 */
	public TransitionsDefinition getTransitions() {
		return transitions;
	}

	/**
	 * Sets the value of the transitions property.
	 * 
	 * @param value
	 *            allowed object is {@link TransitionsDefinition }
	 */
	public void setTransitions(TransitionsDefinition value) {
		this.transitions = value;
	}

	/**
	 * Gets the value of the stateTransitions property.
	 * 
	 * @return possible object is {@link StateTransitionsDefinition }
	 */
	public StateTransitionsDefinition getStateTransitions() {
		return stateTransitions;
	}

	/**
	 * Sets the value of the stateTransitions property.
	 * 
	 * @param value
	 *            allowed object is {@link StateTransitionsDefinition }
	 */
	public void setStateTransitions(StateTransitionsDefinition value) {
		this.stateTransitions = value;
	}

	/**
	 * Gets the value of the allowedChildren property.
	 * 
	 * @return possible object is {@link AllowedChildrenType }
	 */
	public AllowedChildrenType getAllowedChildren() {
		return allowedChildren;
	}

	/**
	 * Sets the value of the allowedChildren property.
	 * 
	 * @param value
	 *            allowed object is {@link AllowedChildrenType }
	 */
	public void setAllowedChildren(AllowedChildrenType value) {
		this.allowedChildren = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the purpose property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getPurpose() {
		return purpose;
	}

	/**
	 * Sets the value of the purpose property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setPurpose(String value) {
		this.purpose = value;
	}

	/**
	 * Gets the value of the parentId property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * Sets the value of the parentId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setParentId(String value) {
		this.parentId = value;
	}

	/**
	 * Gets the value of the referenceId property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getReferenceId() {
		return referenceId;
	}

	/**
	 * Sets the value of the referenceId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setReferenceId(String value) {
		this.referenceId = value;
	}

	/**
	 * Gets the value of the saveCondition property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getSaveCondition() {
		return saveCondition;
	}

	/**
	 * Sets the value of the saveCondition property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setSaveCondition(String value) {
		this.saveCondition = value;
	}

	/**
	 * Gets the value of the standalone property.
	 * 
	 * @return possible object is {@link Boolean }
	 */
	public boolean isStandalone() {
		if (standalone == null) {
			return false;
		} else {
			return standalone;
		}
	}

	/**
	 * Sets the value of the standalone property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 */
	public void setStandalone(Boolean value) {
		this.standalone = value;
	}

	/**
	 * Gets the value of the dmsType property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getDmsType() {
		return dmsType;
	}

	/**
	 * Sets the value of the dmsType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setDmsType(String value) {
		this.dmsType = value;
	}

	/**
	 * Gets the value of the isAbstract property.
	 * 
	 * @return possible object is {@link Boolean }
	 */
	public boolean isIsAbstract() {
		if (isAbstract == null) {
			return false;
		} else {
			return isAbstract;
		}
	}

	/**
	 * Sets the value of the isAbstract property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 */
	public void setIsAbstract(Boolean value) {
		this.isAbstract = value;
	}

}
