select ?instance ?property ?value where {
    ?instance a cnctr:Connector ;
               ?property ?value .
    {
        ?property a owl:DatatypeProperty .
    } UNION {
        bind(rdf:type as ?property)
    }
}