PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX chcart: <http://www.sirma.com/ontologies/2018/05/culturalHeritageConservationArtMuseums#>
delete {
    ?instance emf:definitionId "coreDocument"^^xsd:string .
} insert {
    graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
        ?instance emf:definitionId "document"^^xsd:string .
    }
} where {
    ?instance emf:type "FC236005"^^xsd:string .
    ?instance emf:definitionId "coreDocument"^^xsd:string .
}