PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#> 
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
DELETE {
    GRAPH <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        ptop:Organization emf:isSearchable "false"^^xsd:boolean;
            emf:isCreateable "false"^^xsd:boolean.
    }
}
INSERT {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        ptop:Organization emf:isSearchable "true"^^xsd:boolean;
            emf:isCreateable "true"^^xsd:boolean.
    }
}
WHERE {
}