PREFIX solr:<http://www.ontotext.com/connectors/solr#>
PREFIX inst:<http://www.ontotext.com/connectors/solr/instance#>
INSERT DATA {
    inst:ftsearch solr:createConnector '''

   "fields": [
    {
      "fieldName": "uri",
      "propertyChain": [
        "http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#uri"
      ],
      "index": true,
      "facet": false,
      "sort": true,
      "syncAsis": true
    }}}}],
"types": [
    "http://www.ontotext.com/proton/protontop#Happening",
    "http://www.ontotext.com/proton/protontop#Object"
  ]
     