//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.12 at 05:48:31 PM EET
//

package com.sirma.itt.seip.definition.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for checkTypes.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="checkTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="hasValue"/&gt;
 *     &lt;enumeration value="isEmpty"/&gt;
 *     &lt;enumeration value="contains"/&gt;
 *     &lt;enumeration value="equals"/&gt;
 *     &lt;enumeration value="in"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "checkTypes")
@XmlEnum
public enum CheckTypes {

	/** The has value. */
	@XmlEnumValue("hasValue") HAS_VALUE("hasValue"),

	/** The is empty. */
	@XmlEnumValue("isEmpty") IS_EMPTY("isEmpty"),

	/** The contains. */
	@XmlEnumValue("contains") CONTAINS("contains"),

	/** The equals. */
	@XmlEnumValue("equals") EQUALS("equals"),

	/** The in. */
	@XmlEnumValue("in") IN("in");

	/** The value. */
	private final String value;

	/**
	 * Instantiates a new check types.
	 *
	 * @param v
	 *            the v
	 */
	CheckTypes(String v) {
		value = v;
	}

	/**
	 * Value.
	 *
	 * @return the string
	 */
	public String value() {
		return value;
	}

	/**
	 * From value.
	 *
	 * @param v
	 *            the v
	 * @return the check types
	 */
	public static CheckTypes fromValue(String v) {
		for (CheckTypes c : CheckTypes.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
