//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.07.19 at 02:15:35 PM EEST
//

package com.sirma.itt.seip.definition.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for childType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="childType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="configs" type="{}configsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" use="required" type="{}allowedChildType" /&gt;
 *       &lt;attribute name="id" use="required" type="{}allowedChildIdType" /&gt;
 *       &lt;attribute name="defaultChild" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "childType", propOrder = { "configs" })
public class ChildType {

	protected ConfigsType configs;
	@XmlAttribute(name = "type", required = true)
	protected ObjectType type;
	@XmlAttribute(name = "id", required = true)
	protected String id;
	@XmlAttribute(name = "defaultChild")
	protected Boolean defaultChild;

	/**
	 * Gets the value of the configs property.
	 *
	 * @return possible object is {@link ConfigsType }
	 */
	public ConfigsType getConfigs() {
		return configs;
	}

	/**
	 * Sets the value of the configs property.
	 *
	 * @param value
	 *            allowed object is {@link ConfigsType }
	 */
	public void setConfigs(ConfigsType value) {
		configs = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return possible object is {@link ObjectType }
	 */
	public ObjectType getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *            allowed object is {@link ObjectType }
	 */
	public void setType(ObjectType value) {
		type = value;
	}

	/**
	 * Gets the value of the id property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setId(String value) {
		id = value;
	}

	/**
	 * Gets the value of the defaultChild property.
	 *
	 * @return possible object is {@link Boolean }
	 */
	public boolean isDefaultChild() {
		if (defaultChild == null) {
			return false;
		} else {
			return defaultChild;
		}
	}

	/**
	 * Sets the value of the defaultChild property.
	 *
	 * @param value
	 *            allowed object is {@link Boolean }
	 */
	public void setDefaultChild(Boolean value) {
		defaultChild = value;
	}

	public Boolean getDefaultChild() {
		return defaultChild;
	}
}
