//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.30 at 04:03:20 PM EEST
//

package com.sirma.itt.seip.definition.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for stateTransitionDefinition complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="stateTransitionDefinition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="condition" type="{}conditionDefinition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="from" use="required" type="{}idType" /&gt;
 *       &lt;attribute name="transition" use="required" type="{}idType" /&gt;
 *       &lt;attribute name="to" type="{}idType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stateTransitionDefinition", propOrder = { "condition" })
public class StateTransitionDefinition {

	/** The condition. */
	protected List<ConditionDefinition> condition;

	/** The from. */
	@XmlAttribute(name = "from", required = true)
	protected String from;

	/** The transition. */
	@XmlAttribute(name = "transition", required = true)
	protected String transition;

	/** The to. */
	@XmlAttribute(name = "to")
	protected String to;

	/**
	 * Gets the value of the condition property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the condition property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getCondition().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ConditionDefinition }
	 *
	 * @return the condition
	 */
	public List<ConditionDefinition> getCondition() {
		if (condition == null) {
			condition = new ArrayList<>();
		}
		return condition;
	}

	public void setCondition(List<ConditionDefinition> condition) {
		this.condition = condition;
	}

	/**
	 * Gets the value of the from property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getFrom() {
		return from;
	}

	/**
	 * Sets the value of the from property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setFrom(String value) {
		from = value;
	}

	/**
	 * Gets the value of the transition property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getTransition() {
		return transition;
	}

	/**
	 * Sets the value of the transition property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setTransition(String value) {
		transition = value;
	}

	/**
	 * Gets the value of the to property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getTo() {
		return to;
	}

	/**
	 * Sets the value of the to property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setTo(String value) {
		to = value;
	}

}
