//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.5-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2012.11.02 at 06:39:56 PM EET
//

package com.sirma.itt.seip.definition.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for transitionsDefinition complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="transitionsDefinition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transition" type="{}transitionDefinition" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transitionsDefinition", propOrder = { "transition", "group" })
public class TransitionsDefinition {

	@XmlElement(required = true, name = "transition")
	protected List<TransitionDefinition> transition;

	@XmlElement(required = true, name = "group")
	protected List<TransitionGroupDefinition> group;

	/**
	 * Gets the value of the transition property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the transition property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getTransition().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 *
	 * @return the transition {@link TransitionDefinition }
	 */
	public List<TransitionDefinition> getTransition() {
		if (transition == null) {
			transition = new ArrayList<>();
		}
		return transition;
	}

	/**
	 * Provides list of the transition groups.
	 *
	 * @return list of the groups.
	 */
	public List<TransitionGroupDefinition> getGroup() {
		if (group == null) {
			group = new ArrayList<>();
		}
		return group;
	}

	public void setTransition(List<TransitionDefinition> transition) {
		this.transition = transition;
	}

	public void setGroup(List<TransitionGroupDefinition> group) {
		this.group = group;
	}
}
