PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#> 
DELETE {
		emf:hasPrimaryImage emf:isSearchable "true"^^xsd:boolean .
		emf:isPrimaryImageOf emf:isSearchable "true"^^xsd:boolean .
			
		}
INSERT {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:hasPrimaryImage emf:isSearchable "false"^^xsd:boolean .
		emf:isPrimaryImageOf emf:isSearchable "false"^^xsd:boolean .
    }
}
WHERE {
    
}