PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
PREFIX cia: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation/CIA#>
delete {
    ?instance emf:priority ?o
}  where  {
    ?instance emf:priority ?o .
    {
        ?instance a emf:Project .
    } union
    {
        ?instance a cia:Survey .
    } 
}