SELECT DISTINCT ?instance ?instanceType WHERE {
	?instance rdf:type ?recordSpace .
    ?instance dcterms:title	?title.
    ?instance emf:instanceType ?instanceType.
    ?instance emf:isDeleted	"false"^^xsd:boolean.
}