System.config({
  "baseURL": "/",
  "transpiler": "babel",
  "babelOptions": {
    "modules": "system",
    "moduleIds": false,
    "comments": false,
    "compact": false,
    "externalHelpers": true,
    "optional": [
      "es7.decorators",
      "runtime"
    ]
  },
  "paths": {
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
    "*": "build/*.js"
  },
  "bundles": {
    "build/main-bundle": [
      "npm:core-js@0.9.18/library/modules/$.fw",
      "npm:babel-runtime@5.8.38/helpers/class-call-check",
      "npm:core-js@0.9.18/library/modules/$.def",
      "npm:core-js@0.9.18/library/modules/$.get-names",
      "npm:babel-runtime@5.8.38/helpers/bind",
      "npm:core-js@0.9.18/library/modules/$.unscope",
      "npm:core-js@0.9.18/library/modules/$.uid",
      "npm:core-js@0.9.18/library/modules/$.shared",
      "npm:core-js@0.9.18/library/modules/$.assert",
      "npm:core-js@0.9.18/library/modules/$.redef",
      "npm:core-js@0.9.18/library/modules/$.string-at",
      "npm:core-js@0.9.18/library/modules/core.iter-helpers",
      "idoc/idoc-constants",
      "github:components/jquery@2.1.4/jquery",
      "github:angular/bower-angular@1.5.4/angular",
      "npm:process@0.11.10/browser",
      "npm:stacktrace-js@0.6.4/stacktrace",
      "adapters/angular/window-adapter",
      "npm:bowser@1.4.3/src/bowser",
      "services/rest-client",
      "services/rest/configurations-service",
      "github:postaljs/postal.js@1.0.6/postal",
      "common/command-chain/command-chain",
      "npm:core-js@0.9.18/library/fn/object/get-own-property-descriptor",
      "npm:core-js@0.9.18/library/fn/object/create",
      "npm:core-js@0.9.18/library/modules/$.ctx",
      "npm:core-js@0.9.18/library/modules/es6.number.statics",
      "services/storage/storage",
      "common/lib/base64",
      "adapters/angular/promise-adapter",
      "npm:core-js@0.9.18/library/modules/es6.object.to-string",
      "npm:core-js@0.9.18/library/modules/$.iter-call",
      "npm:core-js@0.9.18/library/modules/$.mix",
      "npm:core-js@0.9.18/library/modules/$.species",
      "npm:core-js@0.9.18/library/modules/$.collection-to-json",
      "npm:core-js@0.9.18/library/fn/object/get-own-property-names",
      "github:angular-translate/bower-angular-translate@2.7.2/angular-translate",
      "services/i18n/language-change-success-event",
      "common/html-util",
      "github:CodeSeven/toastr@2.1.1/toastr.css!github:systemjs/plugin-css@0.1.18",
      "form-builder/validation/after-form-validation-event",
      "npm:core-js@0.9.18/library/modules/$",
      "npm:core-js@0.9.18/library/modules/es6.object.statics-accept-primitives",
      "npm:core-js@0.9.18/library/modules/$.wks",
      "npm:core-js@0.9.18/library/modules/$.iter-define",
      "npm:core-js@0.9.18/library/modules/es6.string.iterator",
      "common/url-utils",
      "github:components/jquery@2.1.4",
      "github:angular/bower-angular@1.5.4",
      "npm:process@0.11.10",
      "npm:stacktrace-js@0.6.4",
      "npm:bowser@1.4.3",
      "services/rest/logging-service",
      "github:postaljs/postal.js@1.0.6",
      "npm:babel-runtime@5.8.38/core-js/object/get-own-property-descriptor",
      "npm:babel-runtime@5.8.38/core-js/object/create",
      "npm:core-js@0.9.18/library/modules/$.set-proto",
      "npm:core-js@0.9.18/library/fn/number/is-nan",
      "services/storage/local-storage-service",
      "npm:core-js@0.9.18/library/modules/$.for-of",
      "npm:core-js@0.9.18/library/modules/$.collection",
      "npm:core-js@0.9.18/library/modules/es7.set.to-json",
      "npm:babel-runtime@5.8.38/core-js/object/get-own-property-names",
      "github:angular-translate/bower-angular-translate@2.7.2",
      "github:CodeSeven/toastr@2.1.1/toastr",
      "npm:core-js@0.9.18/library/fn/object/define-property",
      "npm:core-js@0.9.18/library/fn/object/keys",
      "npm:core-js@0.9.18/library/modules/$.cof",
      "github:jspm/nodelibs-process@0.1.2/index",
      "adapters/navigator-adapter",
      "services/eventbus/eventbus",
      "npm:babel-runtime@5.8.38/helpers/get",
      "npm:core-js@0.9.18/library/modules/es6.object.set-prototype-of",
      "npm:babel-runtime@5.8.38/core-js/number/is-nan",
      "services/security/authentication-service",
      "npm:core-js@0.9.18/library/modules/$.collection-strong",
      "adapters/angular-translate/translate-adapter",
      "github:CodeSeven/toastr@2.1.1",
      "npm:babel-runtime@5.8.38/core-js/object/define-property",
      "npm:babel-runtime@5.8.38/core-js/object/keys",
      "npm:core-js@0.9.18/library/modules/$.iter",
      "github:jspm/nodelibs-process@0.1.2",
      "services/logging/extended-exception-handler",
      "npm:core-js@0.9.18/library/fn/object/set-prototype-of",
      "npm:core-js@0.9.18/library/modules/es6.set",
      "services/i18n/translate-service",
      "services/notification/notification-service",
      "npm:babel-runtime@5.8.38/helpers/create-class",
      "npm:core-js@0.9.18/library/modules/es6.array.iterator",
      "npm:lodash@3.10.0/index",
      "adapters/angular/logger-adapter",
      "npm:babel-runtime@5.8.38/core-js/object/set-prototype-of",
      "npm:core-js@0.9.18/library/fn/set",
      "npm:core-js@0.9.18/library/modules/web.dom.iterable",
      "npm:lodash@3.10.0",
      "npm:babel-runtime@5.8.38/helpers/inherits",
      "npm:babel-runtime@5.8.38/core-js/set",
      "npm:core-js@0.9.18/library/fn/get-iterator",
      "common/convert/type-converter",
      "common/object-utils",
      "npm:babel-runtime@5.8.38/core-js/get-iterator",
      "common/application-config",
      "services/plugin/plugins-service",
      "app/app",
      "services/logging/logger",
      "form-builder/validation/validation-service",
      "form-builder/validation/field-validator",
      "common/convert/property-converter",
      "npm:core-js@0.9.18/library/modules/$.same",
      "npm:core-js@0.9.18/library/modules/$.invoke",
      "npm:core-js@0.9.18/library/modules/$.dom-create",
      "npm:core-js@0.9.18/library/modules/$.iter-detect",
      "services/rest/definition-service",
      "npm:babel-runtime@5.8.38/helpers/define-property",
      "npm:core-js@0.9.18/library/modules/es6.array.from",
      "instance-header/header-constants",
      "npm:core-js@0.9.18/library/fn/object/define-properties",
      "common/uuid",
      "npm:core-js@0.9.18/library/modules/$.enum-keys",
      "common/json-util",
      "search/components/advanced/criteria/advanced-search-criteria-operators",
      "npm:core-js@0.9.18/library/modules/es7.map.to-json",
      "npm:core-js@0.9.18/library/modules/$.task",
      "npm:core-js@0.9.18/library/fn/array/from",
      "npm:babel-runtime@5.8.38/core-js/object/define-properties",
      "common/event-emitter",
      "npm:core-js@0.9.18/library/modules/$.assign",
      "search/utils/query-builder",
      "npm:core-js@0.9.18/library/modules/es6.promise",
      "npm:babel-runtime@5.8.38/core-js/array/from",
      "models/instance-model",
      "npm:core-js@0.9.18/library/modules/es6.object.assign",
      "npm:core-js@0.9.18/library/modules/es6.map",
      "npm:core-js@0.9.18/library/fn/promise",
      "npm:babel-runtime@5.8.38/helpers/to-consumable-array",
      "npm:core-js@0.9.18/library/fn/object/assign",
      "npm:core-js@0.9.18/library/fn/map",
      "npm:babel-runtime@5.8.38/core-js/promise",
      "models/model-utils",
      "npm:babel-runtime@5.8.38/core-js/object/assign",
      "npm:babel-runtime@5.8.38/core-js/map",
      "services/rest/requests-cache-service",
      "search/utils/search-criteria-utils",
      "services/rest/properties-service",
      "form-builder/validation/unique/unique",
      "form-builder/validation/unique/plugin",
      "form-builder/validation/related-codelist-filter/codelist-filter-provider",
      "form-builder/validation/related-codelist-filter/related-codelist-filter",
      "form-builder/validation/related-codelist-filter/plugin",
      "form-builder/validation/regex/regex",
      "form-builder/validation/regex/plugin",
      "form-builder/validation/regex-plain/regex-plain",
      "form-builder/validation/regex-plain/plugin",
      "form-builder/validation/not-equal-fields/plugin",
      "form-builder/validation/not-equal-fields/not-equal-fields",
      "form-builder/validation/mandatory/plugin",
      "form-builder/validation/condition-evaluator",
      "form-builder/validation/mandatory/mandatory",
      "form-builder/validation/less-than-or-equal/plugin",
      "form-builder/validation/less-than-or-equal/less-than-or-equal",
      "form-builder/validation/less-string-length-than/plugin",
      "form-builder/validation/less-string-length-than/less-string-length-than",
      "form-builder/validation/less-number-than/plugin",
      "form-builder/validation/less-number-than/less-number-than",
      "form-builder/validation/greater-than-or-equal/plugin",
      "form-builder/validation/greater-than-or-equal/greater-than-or-equal",
      "form-builder/validation/greater-string-length-than/plugin",
      "form-builder/validation/greater-string-length-than/greater-string-length-than",
      "form-builder/validation/greater-number-than/plugin",
      "form-builder/validation/greater-number-than/greater-number-than",
      "form-builder/validation/equal/plugin",
      "form-builder/validation/equal/equal",
      "form-builder/validation/equal-fields/plugin",
      "form-builder/validation/equal-fields/equal-fields",
      "form-builder/validation/disabled-if-equal/plugin",
      "form-builder/validation/disabled-if-equal/disabled-if-equal",
      "form-builder/validation/condition/plugin",
      "form-builder/validation/condition/condition",
      "form-builder/validation/calculation/plugin",
      "npm:core-js@0.9.18/library/fn/is-iterable",
      "services/rest/labels",
      "idoc/actions/events/before-idoc-save-event",
      "github:moment/moment@2.14.1/moment",
      "services/rest/http-headers",
      "models/definition-model",
      "models/related-object",
      "adapters/angular/angular-adapter",
      "services/rest/response/instance-response",
      "services/rest/response/object-properties-response",
      "services/rest/response/batch-instance-response",
      "common/router/router-state-change-start-event",
      "npm:babel-runtime@5.8.38/core-js/is-iterable",
      "services/rest/label-service",
      "github:moment/moment@2.14.1",
      "services/rest/response/search-response",
      "models/instance-object",
      "services/rest/codelist-service",
      "adapters/moment-adapter",
      "services/rest/instance-service",
      "instance-header/headers-service",
      "npm:babel-runtime@5.8.38/helpers/sliced-to-array",
      "form-builder/validation/calculation/calculation",
      "form-builder/common/validation-message.html!github:systemjs/plugin-text@0.0.2",
      "components/hint/hint.css!github:systemjs/plugin-css@0.1.18",
      "components/hint/hint.html!github:systemjs/plugin-text@0.0.2",
      "components/configurable",
      "adapters/angular/contextual-escape-adapter",
      "npm:core-js@0.9.18/library/fn/object/freeze",
      "services/resolver/search-resolver-service",
      "search/search-mediator",
      "search/search-selection-modes",
      "search/components/common/search-component",
      "search/order-constants",
      "instance/instance-properties",
      "search/components/saved/saved-searches-loader",
      "search/components/saved/saved-search-select/saved-search-select.css!github:systemjs/plugin-css@0.1.18",
      "search/components/saved/saved-search-select/saved-search-select.html!github:systemjs/plugin-text@0.0.2",
      "idoc/shared-objects-registry",
      "idoc/shared-object-updated-event",
      "services/rest/status-codes",
      "services/context/contextual-objects-factory",
      "common/keys",
      "filters/remove-whitespaces",
      "components/dialog/generic-dialog.css!github:systemjs/plugin-css@0.1.18",
      "common/lib/jquery-ui/jquery-ui.min",
      "common/lib/jquery-ui/jquery-ui.min.css!github:systemjs/plugin-css@0.1.18",
      "components/dialog/generic-dialog.html!github:systemjs/plugin-text@0.0.2",
      "components/tabs/tabs.css!github:systemjs/plugin-css@0.1.18",
      "components/tabs/tabs.html!github:systemjs/plugin-text@0.0.2",
      "components/extensions-panel/extensions-panel.html!github:systemjs/plugin-text@0.0.2",
      "components/extensions-panel/extensions-panel.css!github:systemjs/plugin-css@0.1.18",
      "services/rest/models-service",
      "github:sirmaenterprise/select2@4.0.3-custom.1/js/select2",
      "components/reusable-component",
      "github:sirmaenterprise/select2@4.0.3-custom.1/css/select2.css!github:systemjs/plugin-css@0.1.18",
      "components/select/select.css!github:systemjs/plugin-css@0.1.18",
      "components/select/select.html!github:systemjs/plugin-text@0.0.2",
      "components/select/object/object-type-select.css!github:systemjs/plugin-css@0.1.18",
      "components/select/object/object-type-select.html!github:systemjs/plugin-text@0.0.2",
      "common/paths",
      "github:angular-ui/ui-router@0.2.18/angular-ui-router",
      "common/router/router-state-change-success-event",
      "components/dialog/confirmation-dialog-service",
      "adapters/router/state-params-adapter",
      "instance-header/static-instance-header/static-instance-header.html!github:systemjs/plugin-text@0.0.2",
      "instance-header/static-instance-header/static-instance-header.css!github:systemjs/plugin-css@0.1.18",
      "services/bootstrap-service",
      "idoc/events/instance-created-event",
      "services/actions/events",
      "components/help/contextual-help.css!github:systemjs/plugin-css@0.1.18",
      "components/help/contextual-help.html!github:systemjs/plugin-text@0.0.2",
      "search/components/search-bar/search-bar-options.css!github:systemjs/plugin-css@0.1.18",
      "search/components/search-bar/search-bar-options.html!github:systemjs/plugin-text@0.0.2",
      "services/rest/resources-service",
      "instance/utils",
      "recent-objects/events",
      "search/components/search-bar/search-context-menu.css!github:systemjs/plugin-css@0.1.18",
      "search/components/search-bar/search-context-menu.html!github:systemjs/plugin-text@0.0.2",
      "search/components/search-bar/search-bar.css!github:systemjs/plugin-css@0.1.18",
      "search/components/search-bar/search-bar.html!github:systemjs/plugin-text@0.0.2",
      "search/components/advanced/advanced-search-components",
      "npm:font-awesome@4.6.3/css/font-awesome.css!github:systemjs/plugin-css@0.1.18",
      "search/components/advanced/advanced-search-criteria-controls.css!github:systemjs/plugin-css@0.1.18",
      "search/components/advanced/advanced-search-criteria-controls.html!github:systemjs/plugin-text@0.0.2",
      "search/components/advanced/filters/advanced-search-filter-executor",
      "search/components/advanced/advanced-search-criteria-row.css!github:systemjs/plugin-css@0.1.18",
      "search/components/advanced/advanced-search-criteria-row.html!github:systemjs/plugin-text@0.0.2",
      "search/components/advanced/advanced-search-criteria.css!github:systemjs/plugin-css@0.1.18",
      "search/components/advanced/advanced-search-criteria.html!github:systemjs/plugin-text@0.0.2",
      "search/components/advanced/advanced-search-section.css!github:systemjs/plugin-css@0.1.18",
      "search/components/advanced/advanced-search-section.html!github:systemjs/plugin-text@0.0.2",
      "services/rest/permissions-service",
      "search/components/saved/events",
      "search/components/saved/save-search.css!github:systemjs/plugin-css@0.1.18",
      "search/components/saved/save-search.html!github:systemjs/plugin-text@0.0.2",
      "search/components/advanced/advanced-search.html!github:systemjs/plugin-text@0.0.2",
      "search/components/common/pagination.css!github:systemjs/plugin-css@0.1.18",
      "search/components/common/pagination.html!github:systemjs/plugin-text@0.0.2",
      "search/components/common/order-toolbar.css!github:systemjs/plugin-css@0.1.18",
      "search/components/common/order-toolbar.html!github:systemjs/plugin-text@0.0.2",
      "search/components/common/results-toolbar.html!github:systemjs/plugin-text@0.0.2",
      "search/components/common/results-toolbar.css!github:systemjs/plugin-css@0.1.18",
      "filters/instance-by-type-filter",
      "services/rest/actions-service",
      "services/actions/action-handler",
      "idoc/actions/actions-helper",
      "components/dropdownmenu/submenu.html!github:systemjs/plugin-text@0.0.2",
      "components/dropdownmenu/submenu.css!github:systemjs/plugin-css@0.1.18",
      "components/dropdownmenu/dropdownmenu.html!github:systemjs/plugin-text@0.0.2",
      "components/dropdownmenu/dropdownmenu.css!github:systemjs/plugin-css@0.1.18",
      "idoc/actions-menu/actions-menu.html!github:systemjs/plugin-text@0.0.2",
      "idoc/actions-menu/actions-menu.css!github:systemjs/plugin-css@0.1.18",
      "header-container/header-container.css!github:systemjs/plugin-css@0.1.18",
      "header-container/header-container.html!github:systemjs/plugin-text@0.0.2",
      "instance/instance-list.html!github:systemjs/plugin-text@0.0.2",
      "instance/instance-list.css!github:systemjs/plugin-css@0.1.18",
      "search/components/common/search-results.css!github:systemjs/plugin-css@0.1.18",
      "search/components/common/search-results.html!github:systemjs/plugin-text@0.0.2",
      "services/rest/external-object-service",
      "external-search/actions/reload-search-event",
      "external-search/components/results-with-actions.css!github:systemjs/plugin-css@0.1.18",
      "external-search/components/results-with-actions.html!github:systemjs/plugin-text@0.0.2",
      "services/rest/eai-service",
      "services/rest/external-search-service",
      "external-search/external-search.css!github:systemjs/plugin-css@0.1.18",
      "external-search/external-search.html!github:systemjs/plugin-text@0.0.2",
      "search/components/common/mixed-search-criteria.css!github:systemjs/plugin-css@0.1.18",
      "search/components/common/mixed-search-criteria.html!github:systemjs/plugin-text@0.0.2",
      "search/components/common/search-toolbar.css!github:systemjs/plugin-css@0.1.18",
      "search/components/common/search-toolbar.html!github:systemjs/plugin-text@0.0.2",
      "search/components/search.html!github:systemjs/plugin-text@0.0.2",
      "idoc/widget/object-selector/object-selector.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/form-wrapper.css!github:systemjs/plugin-css@0.1.18",
      "form-builder/form-wrapper.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/textfield/textarea/textarea.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/common/validation-message",
      "adapters/tooltip-adapter",
      "filters/to-trusted-html",
      "npm:babel-runtime@5.8.38/core-js/object/freeze",
      "search/components/common/search-criteria-component",
      "search/components/saved/saved-search-select/saved-search-select",
      "components/dialog/generic-dialog",
      "components/tabs/tabs",
      "services/codelist/codelist-service",
      "github:sirmaenterprise/select2@4.0.3-custom.1",
      "services/icons/icons-service",
      "github:angular-ui/ui-router@0.2.18",
      "services/help/help-service",
      "services/identity/user-service",
      "search/components/advanced/advanced-search-criteria-controls",
      "search/components/advanced/advanced-search-criteria-row",
      "search/components/saved/save-search",
      "search/components/common/pagination",
      "search/components/common/order-toolbar",
      "search/components/common/results-toolbar",
      "services/actions/action-executor",
      "components/dropdownmenu/submenu",
      "search/components/common/search-toolbar",
      "services/rest/namespace-service",
      "components/dialog/dialog-service",
      "components/extensions-panel/extensions-panel",
      "services/search/search-criteria-service",
      "components/select/adapters/custom-data-adapter",
      "adapters/router/router",
      "components/help/contextual-help",
      "services/recent/recent-objects-service",
      "search/components/advanced/advanced-search-criteria",
      "components/dropdownmenu/dropdownmenu",
      "components/resizabletextarea/resizable-textarea",
      "services/extensions-dialog/extensions-dialog-service",
      "services/picker/picker-restrictions-service",
      "components/select/select",
      "layout/url-decorator/url-decorator",
      "search/components/search-bar/search-context-menu",
      "search/components/advanced/advanced-search-section",
      "idoc/actions-menu/actions-menu",
      "idoc/idoc-context",
      "services/picker/picker-service",
      "components/select/object/object-type-select",
      "instance-header/static-instance-header/static-instance-header",
      "search/components/advanced/advanced-search",
      "header-container/header-container",
      "components/hint/hint",
      "search/components/search-bar/search-bar-options",
      "instance/instance-list",
      "services/rest/search-service",
      "search/components/search-bar/search-bar",
      "search/components/common/search-results",
      "external-search/components/results-with-actions",
      "external-search/external-search",
      "search/components/common/mixed-search-criteria",
      "search/components/search",
      "idoc/widget/object-selector/object-selector",
      "idoc/widget/properties-selector/properties-selector-helper",
      "form-builder/form-wrapper",
      "form-builder/form-control",
      "form-builder/textfield/text-field",
      "form-builder/textfield/textarea/textarea",
      "form-builder/textfield/textarea/plugin",
      "idoc/editor/idoc-editor-change-listener",
      "form-builder/textfield/rich-text/rich-text.css!github:systemjs/plugin-css@0.1.18",
      "form-builder/textfield/rich-text/rich-text.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/textfield/rich-text/rich-text",
      "form-builder/textfield/rich-text/plugin",
      "form-builder/textfield/input-text/plugin",
      "form-builder/textfield/input-text/input-text.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/textfield/input-text/input-text",
      "components/collapsible/collapsible.css!github:systemjs/plugin-css@0.1.18",
      "form-builder/region/region.html!github:systemjs/plugin-text@0.0.2",
      "components/collapsible/collapsible",
      "form-builder/region/region",
      "form-builder/region/plugin",
      "form-builder/radiobutton-group/radiobutton-group.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/radiobutton-group/radiobutton-group",
      "form-builder/radiobutton-group/plugin",
      "form-builder/object-control/plugin",
      "services/storage/session-storage-service",
      "services/rest/relationships-service",
      "services/rest/relations-service",
      "components/instance-selector/instance-selector.css!github:systemjs/plugin-css@0.1.18",
      "components/instance-selector/instance-selector.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/object-control/object-control.html!github:systemjs/plugin-text@0.0.2",
      "services/idoc/idoc-context-factory",
      "components/select/instance/instance-suggest-select",
      "components/instance-selector/instance-selector",
      "form-builder/object-control/object-control",
      "form-builder/instance-type-resource/user/user.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/instance-type-resource/instance-type-resource",
      "form-builder/instance-type-resource/user/user",
      "form-builder/instance-type-resource/user/plugin",
      "form-builder/instance-type-resource/resource/resource.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/instance-type-resource/resource/resource",
      "form-builder/instance-type-resource/resource/plugin",
      "form-builder/input-password/plugin",
      "form-builder/input-password/input-password.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/input-password/input-password",
      "form-builder/header/plugin",
      "form-builder/header/header.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/header/header",
      "form-builder/empty-cell/plugin",
      "form-builder/empty-cell/empty-cell.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/empty-cell/empty-cell",
      "form-builder/email-control/plugin",
      "form-builder/email-control/email-control.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/email-control/email-control",
      "form-builder/datetime/plugin",
      "github:Eonasdan/bootstrap-datetimepicker@4.17.37/src/js/bootstrap-datetimepicker",
      "github:Eonasdan/bootstrap-datetimepicker@4.17.37/build/css/bootstrap-datetimepicker.css!github:systemjs/plugin-css@0.1.18",
      "components/datetimepicker/datetimepicker.css!github:systemjs/plugin-css@0.1.18",
      "components/datetimepicker/datetimepicker.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/datetime/datetime.html!github:systemjs/plugin-text@0.0.2",
      "github:Eonasdan/bootstrap-datetimepicker@4.17.37",
      "components/datetimepicker/datetimepicker",
      "form-builder/datetime/datetime",
      "form-builder/concept/plugin",
      "services/rest/concept-service",
      "github:clivezhg/select2-to-tree@1.1.1/src/select2totree",
      "github:clivezhg/select2-to-tree@1.1.1/src/select2totree.css!github:systemjs/plugin-css@0.1.18",
      "components/select/tree-select/tree-select.css!github:systemjs/plugin-css@0.1.18",
      "components/select/tree-select/tree-select.html!github:systemjs/plugin-text@0.0.2",
      "components/concept-picker/concept-picker.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/concept/concept-control.html!github:systemjs/plugin-text@0.0.2",
      "components/select/tree-select/tree-select",
      "components/concept-picker/concept-picker",
      "form-builder/concept/concept-control",
      "form-builder/codelist/plugin",
      "filters/array-to-csv",
      "form-builder/codelist/codelist-select/codelist-select.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/codelist/codelist.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/codelist/codelist-select/codelist-select",
      "form-builder/codelist/codelist",
      "form-builder/codelist/codelist-list/plugin",
      "form-builder/codelist/codelist-list/codelist-list.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/codelist/codelist-list/codelist-list",
      "form-builder/checkbox/plugin",
      "form-builder/checkbox/checkbox.html!github:systemjs/plugin-text@0.0.2",
      "form-builder/checkbox/checkbox",
      "layout/window-resized/window-resized-event",
      "layout/window-resized/window-resized-handler",
      "layout/window-resized/plugin",
      "layout/url-decorator/plugin",
      "layout/url-decorator/click-handler",
      "layout/ui-view/ui-view",
      "layout/ui-view/plugin",
      "layout/top-header/top-header.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/top-header.css!github:systemjs/plugin-css@0.1.18",
      "layout/top-header/top-header",
      "layout/top-header/plugin",
      "layout/top-header/main-menu/user-menu/user-menu.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/user-menu/user-menu",
      "layout/top-header/main-menu/user-menu/user-help/user-help.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/user-menu/user-help/user-help",
      "layout/top-header/main-menu/user-menu/user-help/plugin",
      "user/avatar/user-avatar.html!github:systemjs/plugin-text@0.0.2",
      "user/avatar/user-avatar.css!github:systemjs/plugin-css@0.1.18",
      "layout/top-header/main-menu/user-menu/settings/settings.css!github:systemjs/plugin-css@0.1.18",
      "layout/top-header/main-menu/user-menu/settings/settings.html!github:systemjs/plugin-text@0.0.2",
      "user/avatar/user-avatar",
      "layout/top-header/main-menu/user-menu/settings/settings",
      "layout/top-header/main-menu/user-menu/settings/preferences/preferences",
      "layout/top-header/main-menu/user-menu/settings/preferences/plugin",
      "layout/top-header/main-menu/user-menu/settings/plugin",
      "layout/top-header/main-menu/user-menu/settings/logout/plugin",
      "layout/top-header/main-menu/user-menu/settings/logout/logout-event",
      "layout/top-header/main-menu/user-menu/settings/logout/logout",
      "layout/top-header/main-menu/user-menu/settings/help-request/plugin",
      "user/help-request/help-request-service",
      "layout/top-header/main-menu/user-menu/settings/help-request/help-request",
      "layout/top-header/main-menu/user-menu/settings/fullscreen/plugin",
      "layout/top-header/main-menu/user-menu/settings/fullscreen/fullscreen",
      "layout/top-header/main-menu/user-menu/settings/change-password/plugin",
      "user/change-password/change-password-dialog.html!github:systemjs/plugin-text@0.0.2",
      "user/change-password/change-password-dialog.css!github:systemjs/plugin-css@0.1.18",
      "user/change-password/change-password-dialog",
      "user/change-password/change-password-service",
      "layout/top-header/main-menu/user-menu/settings/change-password/change-password",
      "layout/top-header/main-menu/user-menu/plugin",
      "components/contextselector/context-selector.css!github:systemjs/plugin-css@0.1.18",
      "components/contextselector/context-selector.html!github:systemjs/plugin-text@0.0.2",
      "npm:blueimp-file-upload@9.12.1/js/vendor/jquery.ui.widget",
      "npm:blueimp-file-upload@9.12.1/js/jquery.fileupload",
      "services/servlet-client",
      "layout/session/user-activity-event",
      "idoc/actions/events/refresh-widgets-command",
      "npm:filesize@3.2.1/lib/filesize",
      "file-upload/events",
      "file-upload/file-upload-integration",
      "idoc/template/template-constants",
      "idoc/template/template-data-panel.css!github:systemjs/plugin-css@0.1.18",
      "idoc/template/template-data-panel.html!github:systemjs/plugin-text@0.0.2",
      "npm:core-js@0.9.18/library/modules/es7.object.to-array",
      "services/rest/template-service",
      "components/select/instance/instance-select",
      "idoc/template/rules/template-rule-utils",
      "idoc/template/idoc-template-selector.html!github:systemjs/plugin-text@0.0.2",
      "create/instance-create-panel.html!github:systemjs/plugin-text@0.0.2",
      "create/instance-create-panel.css!github:systemjs/plugin-css@0.1.18",
      "create/instance-create-configuration.html!github:systemjs/plugin-text@0.0.2",
      "create/instance-create-configuration.css!github:systemjs/plugin-css@0.1.18",
      "file-upload/file-item.html!github:systemjs/plugin-text@0.0.2",
      "file-upload/file-upload.css!github:systemjs/plugin-css@0.1.18",
      "file-upload/file-upload.html!github:systemjs/plugin-text@0.0.2",
      "create/file-upload-panel.css!github:systemjs/plugin-css@0.1.18",
      "create/file-upload-panel.html!github:systemjs/plugin-text@0.0.2",
      "file-upload/dnd-support/file-upload-dnd-support",
      "layout/top-header/main-menu/upload-new/upload-new.css!github:systemjs/plugin-css@0.1.18",
      "layout/top-header/main-menu/upload-new/upload-new.html!github:systemjs/plugin-text@0.0.2",
      "npm:blueimp-file-upload@9.12.1",
      "services/rest/content-service",
      "npm:filesize@3.2.1",
      "idoc/template/template-data-panel",
      "npm:core-js@0.9.18/library/fn/object/values",
      "idoc/template/idoc-template-selector",
      "npm:babel-runtime@5.8.38/core-js/object/values",
      "services/idoc/instance-context-service",
      "create/instance-create-panel",
      "components/contextselector/context-selector",
      "create/instance-create-configuration",
      "file-upload/file-item",
      "file-upload/file-upload",
      "create/file-upload-panel",
      "services/create/create-panel-service",
      "layout/top-header/main-menu/upload-new/upload-new",
      "layout/top-header/main-menu/upload-new/plugin",
      "layout/top-header/main-menu/quick-access/tasks/tasks.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/quick-access/tasks/tasks",
      "layout/top-header/main-menu/quick-access/tasks/plugin",
      "layout/top-header/main-menu/quick-access/recent-objects-menu/recent-objects-menu.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/quick-access/recent-objects-menu/recent-objects-menu",
      "layout/top-header/main-menu/quick-access/recent-objects-menu/plugin",
      "layout/top-header/main-menu/quick-access/quick-access.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/quick-access/quick-access",
      "layout/top-header/main-menu/quick-access/plugin",
      "layout/top-header/main-menu/quick-access/open-ui-action",
      "layout/top-header/main-menu/quick-access/mail-menu/plugin",
      "idoc/system-tabs/mailbox/events/personal-mailbox-updated-event",
      "services/rest/mailbox-info-service",
      "layout/top-header/main-menu/quick-access/mail-menu/mail-menu.css!github:systemjs/plugin-css@0.1.18",
      "layout/top-header/main-menu/quick-access/mail-menu/mail-menu.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/quick-access/mail-menu/mail-menu",
      "layout/top-header/main-menu/quick-access/dashboard/plugin",
      "layout/top-header/main-menu/quick-access/dashboard/dashboard.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/quick-access/dashboard/dashboard",
      "layout/top-header/main-menu/quick-access/browse-libraries-action",
      "layout/top-header/main-menu/quick-access/admin/plugin",
      "layout/top-header/main-menu/quick-access/admin/admin-menu.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/quick-access/admin/admin-menu",
      "layout/top-header/main-menu/plugin",
      "layout/top-header/main-menu/main-menu.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/main-menu.css!github:systemjs/plugin-css@0.1.18",
      "layout/top-header/main-menu/main-menu",
      "layout/top-header/main-menu/create-new/plugin",
      "layout/top-header/main-menu/create-new/create-new.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/main-menu/create-new/create-new",
      "layout/top-header/logo/top-header-logo.css!github:systemjs/plugin-css@0.1.18",
      "layout/top-header/logo/top-header-logo.html!github:systemjs/plugin-text@0.0.2",
      "layout/top-header/logo/top-header-logo",
      "layout/top-header/logo/plugin",
      "layout/session/session-keep-alive-handler",
      "layout/session/plugin",
      "layout/public/public-component-wrapper.css!github:systemjs/plugin-css@0.1.18",
      "layout/public/public-component-wrapper.html!github:systemjs/plugin-text@0.0.2",
      "layout/public/public-component-wrapper",
      "layout/public/plugin",
      "layout/breadcrumb/plugin",
      "layout/breadcrumb/breadcrumb-entry-manager",
      "layout/breadcrumb/breadcrumb-entry/entry-item",
      "idoc/events/after-idoc-loaded-event",
      "idoc/actions/events/instance-refresh-event",
      "search/components/quick-search.css!github:systemjs/plugin-css@0.1.18",
      "search/components/quick-search.html!github:systemjs/plugin-text@0.0.2",
      "layout/breadcrumb/breadcrumb-entry/entry-selected-event",
      "layout/breadcrumb/breadcrumb-entry/entry-component",
      "services/interceptors/active-requests-status-changed-event",
      "components/http-requests-indicator/http-requests-indicator.css!github:systemjs/plugin-css@0.1.18",
      "components/http-requests-indicator/http-requests-indicator.html!github:systemjs/plugin-text@0.0.2",
      "layout/breadcrumb/breadcrumb.css!github:systemjs/plugin-css@0.1.18",
      "layout/breadcrumb/breadcrumb.html!github:systemjs/plugin-text@0.0.2",
      "components/http-requests-indicator/http-requests-indicator",
      "search/components/quick-search",
      "layout/breadcrumb/breadcrumb-state-handler",
      "layout/breadcrumb/breadcrumb",
      "github:sdecima/javascript-detect-element-resize@0.5.3/detect-element-resize",
      "github:sdecima/javascript-detect-element-resize@0.5.3",
      "adapters/resize-detector-adapter",
      "components/ui-preference/ui-preference",
      "components/toolbars/toolbar.html!github:systemjs/plugin-text@0.0.2",
      "components/toolbars/toolbar.css!github:systemjs/plugin-css@0.1.18",
      "components/toolbars/toolbar",
      "github:nathancahill/Split.js@1.2.0/split",
      "components/splitter/splitter.css!github:systemjs/plugin-css@0.1.18",
      "github:nathancahill/Split.js@1.2.0",
      "components/splitter/splitter",
      "components/select/resource/resource-select",
      "components/select/object/object-select",
      "components/resizableinput/resizable-input.css!github:systemjs/plugin-css@0.1.18",
      "components/resizableinput/resizable-input.html!github:systemjs/plugin-text@0.0.2",
      "components/resizableinput/resizable-input",
      "components/refreshable",
      "github:vakata/jstree@3.3.5/dist/jstree",
      "components/object-browser/object-browser.html!github:systemjs/plugin-text@0.0.2",
      "components/object-browser/object-browser.css!github:systemjs/plugin-css@0.1.18",
      "github:vakata/jstree@3.3.5",
      "components/object-browser/object-browser",
      "components/media/video-player/video-player.html!github:systemjs/plugin-text@0.0.2",
      "components/media/video-player/video-player.css!github:systemjs/plugin-css@0.1.18",
      "components/media/video-player/video-player",
      "components/media/pdf-viewer/pdf-viewer.html!github:systemjs/plugin-text@0.0.2",
      "components/media/pdf-viewer/pdf-viewer.css!github:systemjs/plugin-css@0.1.18",
      "components/media/pdf-viewer/pdf-viewer",
      "components/media/image-viewer/image-viewer.html!github:systemjs/plugin-text@0.0.2",
      "components/media/image-viewer/image-viewer.css!github:systemjs/plugin-css@0.1.18",
      "components/media/image-viewer/image-viewer",
      "components/media/audio-player/audio-player.html!github:systemjs/plugin-text@0.0.2",
      "components/media/audio-player/audio-player.css!github:systemjs/plugin-css@0.1.18",
      "components/media/audio-player/audio-player",
      "components/filter/input-filter.css!github:systemjs/plugin-css@0.1.18",
      "components/filter/input-filter.html!github:systemjs/plugin-text@0.0.2",
      "components/filter/input-filter",
      "github:johnny/jquery-sortable@0.9.13/source/js/jquery-sortable",
      "github:johnny/jquery-sortable@0.9.13",
      "components/draganddrop/drag-and-drop",
      "npm:base64-js@1.2.1/index",
      "npm:ieee754@1.1.8/index",
      "npm:spectrum-colorpicker@1.8.0/spectrum",
      "npm:spectrum-colorpicker@1.8.0/spectrum.css!github:systemjs/plugin-css@0.1.18",
      "components/color-picker/color-picker.css!github:systemjs/plugin-css@0.1.18",
      "npm:base64-js@1.2.1",
      "npm:ieee754@1.1.8",
      "npm:spectrum-colorpicker@1.8.0",
      "npm:buffer@5.0.7/index",
      "npm:buffer@5.0.7",
      "github:jspm/nodelibs-buffer@0.1.1/index",
      "github:jspm/nodelibs-buffer@0.1.1",
      "npm:d3@4.7.1/build/d3",
      "npm:d3@4.7.1",
      "components/color-picker/color-picker",
      "components/charts/chart.css!github:systemjs/plugin-css@0.1.18",
      "components/charts/pie-chart/pie-chart.html!github:systemjs/plugin-text@0.0.2",
      "components/charts/pie-chart/pie-chart.css!github:systemjs/plugin-css@0.1.18",
      "components/charts/chart",
      "components/charts/pie-chart/pie-chart",
      "components/charts/line-chart/line-chart.html!github:systemjs/plugin-text@0.0.2",
      "components/charts/line-chart/line-chart.css!github:systemjs/plugin-css@0.1.18",
      "components/charts/line-chart/line-chart",
      "components/charts/bar-chart/bar-chart.html!github:systemjs/plugin-text@0.0.2",
      "components/charts/bar-chart/bar-chart",
      "components/alt-src",
      "filters/time-ago",
      "filters/paginate",
      "adapters/router/route-interrupter",
      "adapters/angular/location-adapter",
      "common/window-message-dispatcher",
      "common/translate",
      "common/simple-date-to-moment-format",
      "common/polling-utils",
      "common/plugin",
      "github:angular/bower-angular-animate@1.5.5/angular-animate",
      "github:chieffancypants/angular-loading-bar@0.8.0/build/loading-bar.css!github:systemjs/plugin-css@0.1.18",
      "github:angular/bower-angular-sanitize@1.5.10/angular-sanitize",
      "github:twbs/bootstrap-sass@3.3.5/assets/javascripts/bootstrap",
      "github:chieffancypants/angular-loading-bar@0.8.0/src/loading-bar.css!github:systemjs/plugin-css@0.1.18",
      "github:angular/bower-angular-animate@1.5.5",
      "github:chieffancypants/angular-loading-bar@0.8.0/build/loading-bar",
      "github:angular/bower-angular-sanitize@1.5.10",
      "github:twbs/bootstrap-sass@3.3.5",
      "github:chieffancypants/angular-loading-bar@0.8.0",
      "common/libs",
      "common/check-for-new-build",
      "github:pellepim/jstimezonedetect@master/dist/jstz",
      "services/interceptors/active-requests-counter-interceptor",
      "services/interceptors/request-headers-update-interceptor",
      "github:pellepim/jstimezonedetect@master",
      "services/interceptors/http-error-interceptor",
      "main"
    ]
  },
  "rootURL": "build/"
});

System.config({
  "map": {
    "CodeSeven/toastr": "github:CodeSeven/toastr@2.1.1",
    "Eonasdan/bootstrap-datetimepicker": "github:Eonasdan/bootstrap-datetimepicker@4.17.37",
    "angular": "github:angular/bower-angular@1.5.4",
    "angular-animate": "github:angular/bower-angular-animate@1.5.5",
    "angular-loading-bar": "github:chieffancypants/angular-loading-bar@0.8.0",
    "angular-sanitize": "github:angular/bower-angular-sanitize@1.5.10",
    "angular-translate": "github:angular-translate/bower-angular-translate@2.7.2",
    "angular-ui-router": "github:angular-ui/ui-router@0.2.18",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "bowser": "npm:bowser@1.4.3",
    "bpmn-js": "npm:bpmn-js@0.20.5",
    "clean-css": "npm:clean-css@3.4.28",
    "clivezhg/select2-to-tree": "github:clivezhg/select2-to-tree@1.1.1",
    "core-js": "npm:core-js@0.9.18",
    "css": "github:systemjs/plugin-css@0.1.18",
    "d3": "npm:d3@4.7.1",
    "dotdotdot": "npm:dotdotdot@1.7.0",
    "file-saver": "npm:file-saver@1.3.3",
    "filesize": "npm:filesize@3.2.1",
    "font-awesome": "npm:font-awesome@4.6.3",
    "johnculviner/jquery.fileDownload": "github:johnculviner/jquery.fileDownload@1.4.6",
    "johnny/jquery-sortable": "github:johnny/jquery-sortable@0.9.13",
    "jquery": "github:components/jquery@2.1.4",
    "jquery-file-download": "npm:jquery-file-download@1.4.6",
    "jquery-file-upload": "npm:blueimp-file-upload@9.12.1",
    "jquery-lazyload": "npm:jquery-lazyload@1.9.7",
    "json": "github:systemjs/plugin-json@0.1.2",
    "jstz": "github:pellepim/jstimezonedetect@master",
    "lodash": "npm:lodash@3.10.0",
    "moment": "github:moment/moment@2.14.1",
    "nathancahill/Split.js": "github:nathancahill/Split.js@1.2.0",
    "node-emoji": "npm:node-emoji@1.4.1",
    "polished": "npm:polished@1.9.2",
    "postaljs/monologue.js": "github:postaljs/monologue.js@0.3.5",
    "postaljs/postal.js": "github:postaljs/postal.js@1.0.6",
    "riveter": "npm:riveter@0.2.0",
    "sdecima/javascript-detect-element-resize": "github:sdecima/javascript-detect-element-resize@0.5.3",
    "select2": "github:sirmaenterprise/select2@4.0.3-custom.1",
    "shortid": "npm:shortid@2.2.8",
    "spectrum-colorpicker": "npm:spectrum-colorpicker@1.8.0",
    "stacktrace-js": "npm:stacktrace-js@0.6.4",
    "string-matcher": "github:radpet/node-kmp@master",
    "text": "github:systemjs/plugin-text@0.0.2",
    "twbs/bootstrap-sass": "github:twbs/bootstrap-sass@3.3.5",
    "underscore": "npm:lodash@3.10.0",
    "vakata/jstree": "github:vakata/jstree@3.3.5",
    "github:CodeSeven/toastr@2.1.1": {
      "css": "github:systemjs/plugin-css@0.1.18",
      "jquery": "github:components/jquery@2.1.4"
    },
    "github:angular-translate/bower-angular-translate@2.7.2": {
      "angular": "github:angular/bower-angular@1.5.4"
    },
    "github:angular-ui/ui-router@0.2.18": {
      "angular": "github:angular/bower-angular@1.5.4"
    },
    "github:angular/bower-angular-animate@1.5.5": {
      "angular": "github:angular/bower-angular@1.5.4"
    },
    "github:angular/bower-angular-sanitize@1.5.10": {
      "angular": "github:angular/bower-angular@1.5.4"
    },
    "github:chieffancypants/angular-loading-bar@0.8.0": {
      "angular": "github:angular/bower-angular@1.5.4",
      "css": "github:systemjs/plugin-css@0.1.18"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.1": {
      "buffer": "npm:buffer@5.0.7"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.10"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:amdefine@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:asn1.js@4.9.1": {
      "bn.js": "npm:bn.js@4.11.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:blueimp-file-upload@9.12.1": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:bn.js@4.11.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1"
    },
    "npm:bpmn-js@0.20.5": {
      "bpmn-moddle": "npm:bpmn-moddle@0.14.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "diagram-js": "npm:diagram-js@0.19.3",
      "diagram-js-direct-editing": "npm:diagram-js-direct-editing@0.17.1",
      "diagram-js-origin": "npm:diagram-js-origin@0.15.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ids": "npm:ids@0.2.0",
      "inherits": "npm:inherits@2.0.1",
      "lodash": "npm:lodash@3.10.0",
      "min-dom": "npm:min-dom@0.2.0",
      "object-refs": "npm:object-refs@0.1.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "tiny-svg": "npm:tiny-svg@0.1.1"
    },
    "npm:bpmn-moddle@0.14.0": {
      "lodash": "npm:lodash@3.10.0",
      "moddle": "npm:moddle@1.0.0",
      "moddle-xml": "npm:moddle-xml@1.0.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:brorand@1.1.0": {
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.3",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "cipher-base": "npm:cipher-base@1.0.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.11.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:browserify-sign@4.0.4": {
      "bn.js": "npm:bn.js@4.11.6",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.4.0",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.1.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer@5.0.7": {
      "base64-js": "npm:base64-js@1.2.1",
      "ieee754": "npm:ieee754@1.1.8"
    },
    "npm:cipher-base@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:clean-css@3.4.28": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "commander": "npm:commander@2.8.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.4.4",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:commander@2.8.1": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graceful-readlink": "npm:graceful-readlink@1.0.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:component-classes@1.2.6": {
      "component-indexof": "npm:component-indexof@0.0.3"
    },
    "npm:component-closest@0.1.4": {
      "component-matches-selector": "npm:component-matches-selector@0.1.6"
    },
    "npm:component-delegate@0.2.4": {
      "component-closest": "npm:component-closest@0.1.4",
      "component-event": "npm:component-event@0.1.4"
    },
    "npm:component-matches-selector@0.1.6": {
      "component-query": "npm:component-query@0.0.3"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.11.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.4.0"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "cipher-base": "npm:cipher-base@1.0.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.8"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.4",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.9",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:d3-brush@1.0.3": {
      "d3-dispatch": "npm:d3-dispatch@1.0.2",
      "d3-drag": "npm:d3-drag@1.0.3",
      "d3-interpolate": "npm:d3-interpolate@1.1.3",
      "d3-selection": "npm:d3-selection@1.0.4",
      "d3-transition": "npm:d3-transition@1.0.3"
    },
    "npm:d3-chord@1.0.3": {
      "d3-array": "npm:d3-array@1.1.0",
      "d3-path": "npm:d3-path@1.0.4"
    },
    "npm:d3-drag@1.0.3": {
      "d3-dispatch": "npm:d3-dispatch@1.0.2",
      "d3-selection": "npm:d3-selection@1.0.4"
    },
    "npm:d3-dsv@1.0.4": {
      "commander": "npm:commander@2.8.1",
      "iconv-lite": "npm:iconv-lite@0.4.15",
      "rw": "npm:rw@1.3.3"
    },
    "npm:d3-force@1.0.5": {
      "d3-collection": "npm:d3-collection@1.0.2",
      "d3-dispatch": "npm:d3-dispatch@1.0.2",
      "d3-quadtree": "npm:d3-quadtree@1.0.2",
      "d3-timer": "npm:d3-timer@1.0.4",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:d3-geo@1.6.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "d3-array": "npm:d3-array@1.1.0"
    },
    "npm:d3-interpolate@1.1.3": {
      "d3-color": "npm:d3-color@1.0.2"
    },
    "npm:d3-request@1.0.4": {
      "d3-collection": "npm:d3-collection@1.0.2",
      "d3-dispatch": "npm:d3-dispatch@1.0.2",
      "d3-dsv": "npm:d3-dsv@1.0.4",
      "xmlhttprequest": "npm:xmlhttprequest@1.8.0"
    },
    "npm:d3-scale@1.0.4": {
      "d3-array": "npm:d3-array@1.1.0",
      "d3-collection": "npm:d3-collection@1.0.2",
      "d3-color": "npm:d3-color@1.0.2",
      "d3-format": "npm:d3-format@1.1.0",
      "d3-interpolate": "npm:d3-interpolate@1.1.3",
      "d3-time": "npm:d3-time@1.0.5",
      "d3-time-format": "npm:d3-time-format@2.0.4"
    },
    "npm:d3-shape@1.0.5": {
      "d3-path": "npm:d3-path@1.0.4"
    },
    "npm:d3-time-format@2.0.4": {
      "d3-time": "npm:d3-time@1.0.5"
    },
    "npm:d3-transition@1.0.3": {
      "d3-color": "npm:d3-color@1.0.2",
      "d3-dispatch": "npm:d3-dispatch@1.0.2",
      "d3-ease": "npm:d3-ease@1.0.2",
      "d3-interpolate": "npm:d3-interpolate@1.1.3",
      "d3-selection": "npm:d3-selection@1.0.4",
      "d3-timer": "npm:d3-timer@1.0.4"
    },
    "npm:d3-zoom@1.1.2": {
      "d3-dispatch": "npm:d3-dispatch@1.0.2",
      "d3-drag": "npm:d3-drag@1.0.3",
      "d3-interpolate": "npm:d3-interpolate@1.1.3",
      "d3-selection": "npm:d3-selection@1.0.4",
      "d3-transition": "npm:d3-transition@1.0.3"
    },
    "npm:d3@4.7.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "d3-array": "npm:d3-array@1.1.0",
      "d3-axis": "npm:d3-axis@1.0.5",
      "d3-brush": "npm:d3-brush@1.0.3",
      "d3-chord": "npm:d3-chord@1.0.3",
      "d3-collection": "npm:d3-collection@1.0.2",
      "d3-color": "npm:d3-color@1.0.2",
      "d3-dispatch": "npm:d3-dispatch@1.0.2",
      "d3-drag": "npm:d3-drag@1.0.3",
      "d3-dsv": "npm:d3-dsv@1.0.4",
      "d3-ease": "npm:d3-ease@1.0.2",
      "d3-force": "npm:d3-force@1.0.5",
      "d3-format": "npm:d3-format@1.1.0",
      "d3-geo": "npm:d3-geo@1.6.1",
      "d3-hierarchy": "npm:d3-hierarchy@1.1.2",
      "d3-interpolate": "npm:d3-interpolate@1.1.3",
      "d3-path": "npm:d3-path@1.0.4",
      "d3-polygon": "npm:d3-polygon@1.0.2",
      "d3-quadtree": "npm:d3-quadtree@1.0.2",
      "d3-queue": "npm:d3-queue@3.0.4",
      "d3-random": "npm:d3-random@1.0.2",
      "d3-request": "npm:d3-request@1.0.4",
      "d3-scale": "npm:d3-scale@1.0.4",
      "d3-selection": "npm:d3-selection@1.0.4",
      "d3-shape": "npm:d3-shape@1.0.5",
      "d3-time": "npm:d3-time@1.0.5",
      "d3-time-format": "npm:d3-time-format@2.0.4",
      "d3-timer": "npm:d3-timer@1.0.4",
      "d3-transition": "npm:d3-transition@1.0.3",
      "d3-voronoi": "npm:d3-voronoi@1.1.1",
      "d3-zoom": "npm:d3-zoom@1.1.2",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diagram-js-direct-editing@0.17.1": {
      "diagram-js": "npm:diagram-js@0.19.3",
      "lodash": "npm:lodash@3.10.0",
      "min-dom": "npm:min-dom@0.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:diagram-js-origin@0.15.1": {
      "diagram-js": "npm:diagram-js@0.19.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tiny-svg": "npm:tiny-svg@0.1.1"
    },
    "npm:diagram-js@0.19.3": {
      "didi": "npm:didi@0.1.1",
      "hammerjs": "npm:hammerjs@2.0.8",
      "inherits": "npm:inherits@2.0.1",
      "lodash": "npm:lodash@3.10.0",
      "min-dom": "npm:min-dom@0.2.0",
      "object-refs": "npm:object-refs@0.1.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tiny-svg": "npm:tiny-svg@0.1.1"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.11.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:dotdotdot@1.7.0": {
      "jquery": "npm:jquery@3.2.1"
    },
    "npm:elliptic@6.4.0": {
      "bn.js": "npm:bn.js@4.11.6",
      "brorand": "npm:brorand@1.1.0",
      "hash.js": "npm:hash.js@1.0.3",
      "hmac-drbg": "npm:hmac-drbg@1.0.1",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "minimalistic-crypto-utils": "npm:minimalistic-crypto-utils@1.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:font-awesome@4.6.3": {
      "css": "github:systemjs/plugin-css@0.1.18"
    },
    "npm:graceful-readlink@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:hammerjs@2.0.8": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:hmac-drbg@1.0.1": {
      "hash.js": "npm:hash.js@1.0.3",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "minimalistic-crypto-utils": "npm:minimalistic-crypto-utils@1.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:iconv-lite@0.4.15": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:ids@0.2.0": {
      "hat": "npm:hat@0.0.3"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:jquery-file-download@1.4.6": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:lodash@2.4.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:lodash@3.10.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.11.6",
      "brorand": "npm:brorand@1.1.0"
    },
    "npm:min-dom@0.2.0": {
      "component-classes": "npm:component-classes@1.2.6",
      "component-closest": "npm:component-closest@0.1.4",
      "component-delegate": "npm:component-delegate@0.2.4",
      "component-event": "npm:component-event@0.1.4",
      "component-matches-selector": "npm:component-matches-selector@0.1.6",
      "component-query": "npm:component-query@0.0.3",
      "domify": "npm:domify@1.4.0"
    },
    "npm:moddle-xml@1.0.0": {
      "lodash": "npm:lodash@3.10.0",
      "moddle": "npm:moddle@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "sax": "npm:sax@0.6.1",
      "tiny-stack": "npm:tiny-stack@0.1.0"
    },
    "npm:moddle@1.0.0": {
      "lodash": "npm:lodash@3.10.0"
    },
    "npm:node-emoji@1.4.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "string.prototype.codepointat": "npm:string.prototype.codepointat@0.2.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:parse-asn1@5.1.0": {
      "asn1.js": "npm:asn1.js@4.9.1",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.9",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.10": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.11.6",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.1.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:randombytes@2.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:riveter@0.2.0": {
      "lodash": "npm:lodash@2.4.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:rw@1.3.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sax@0.6.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:sha.js@2.4.8": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:shortid@2.2.8": {
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:source-map@0.4.4": {
      "amdefine": "npm:amdefine@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1"
    },
    "npm:tiny-svg@0.1.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:xmlhttprequest@1.8.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "url": "github:jspm/nodelibs-url@0.1.0"
    }
  }
});

