PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix chd: <http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain#>

insert data {
graph <http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain> {
chd:accordingToProposal emf:isSearchable "true"^^xsd:boolean .
chd:hasActionList emf:isSearchable "true"^^xsd:boolean .
chd:usesMaterials emf:isSearchable "true"^^xsd:boolean .
}
}