PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
insert data {

graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
emf:attachment_mail emf:isSearchable "true"^^xsd:boolean .
emf:blocks emf:isSearchable "true"^^xsd:boolean .
emf:completedBy emf:isSearchable "true"^^xsd:boolean .
emf:createdBy emf:isSearchable "true"^^xsd:boolean .
emf:dependsOn emf:isSearchable "true"^^xsd:boolean .
emf:hasAssignee emf:isSearchable "true"^^xsd:boolean .
emf:hasChild emf:isSearchable "true"^^xsd:boolean .
emf:hasOwner emf:isSearchable "true"^^xsd:boolean .
emf:hasPrimaryImage emf:isSearchable "true"^^xsd:boolean .
emf:isDuplicatedBy emf:isSearchable "true"^^xsd:boolean .
emf:isMemberOf emf:isSearchable "true"^^xsd:boolean .
emf:isPrimaryImageOf emf:isSearchable "true"^^xsd:boolean .
emf:isRelatedTo emf:isSearchable "true"^^xsd:boolean .
emf:mail_attachment emf:isSearchable "true"^^xsd:boolean .
emf:modifiedBy emf:isSearchable "true"^^xsd:boolean .
emf:owner emf:isSearchable "true"^^xsd:boolean .
emf:priority emf:isSearchable "true"^^xsd:boolean .
emf:processedBy emf:isSearchable "true"^^xsd:boolean .
emf:processes emf:isSearchable "true"^^xsd:boolean .
emf:replyTo emf:isSearchable "true"^^xsd:boolean .
emf:updatedBy emf:isSearchable "true"^^xsd:boolean .
ptop:partOf emf:isSearchable "true"^^xsd:boolean .
emf:modifiedBy emf:isSearchable "true"^^xsd:boolean .
ptop:involvedIn emf:isSearchable "true"^^xsd:boolean .
}
}