PREFIX pdm: <http://www.sirma.com/ontologies/2013/10/pdmConfiguration#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
insert data {
graph <http://www.sirma.com/ontologies/2013/10/pdmConfiguration> {
pdm:hasConfigurationChart emf:isSearchable "true"^^xsd:boolean . 
pdm:hasConfigurationOption emf:isSearchable "true"^^xsd:boolean .
pdm:hasConfiguredPart emf:isSearchable "true"^^xsd:boolean .
pdm:hasDesign emf:isSearchable "true"^^xsd:boolean .
pdm:hasFeature emf:isSearchable "true"^^xsd:boolean .
pdm:hasPart emf:isSearchable "true"^^xsd:boolean .
pdm:hasProductConfiguration emf:isSearchable "true"^^xsd:boolean .
pdm:hasProductModel emf:isSearchable "true"^^xsd:boolean .
}

}