PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
INSERT {
	graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
		?instance emf:compact_header ?header.
   }
}
WHERE
{
	?instance rdf:type emf:CaseSection.
	?instance rdf:type ?type.
	?type emf:definitionId ?defType.
	?instance emf:definitionId ?defId.
	filter ( NOT EXISTS { ?instance emf:compact_header ?h } ) .
	BIND(CONCAT("<a class=\"",STR(?defId),"\" href=\"/emf/entity/open.jsf?type=",STR(?defType),"&instanceId=",REPLACE(STR(?instance),"^http.*#","emf:"),"\">",UCASE(SUBSTR(?defId,1,1)),SUBSTR(?defId,2,STRLEN(?defId)-1)," section</a>") as ?header).
}