PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
INSERT {
	graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
		?instance emf:purpose "objectsSection".
   }
}
WHERE
{
?instance rdf:type emf:CaseSection.
filter ( NOT EXISTS { ?instance emf:purpose ?h } ).
{
	?instance emf:parentOf ?child.
	?child rdf:type emf:DomainObject
} UNION {
	?instance emf:definitionId ?defId.
	filter(REGEX(?defId, "objects|domainEntities|internalEntities|externalEntities|samples|samplingObjects|trader|customer|verndor|product|transportCompany|transportCompany|order|company")).
}	
}