PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
INSERT {
	graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
		?instance emf:purpose "iDoc".
   }
}
WHERE
{
?instance rdf:type emf:IntelligentDocument.
filter ( NOT EXISTS { ?instance emf:purpose ?h } ).
}