PREFIX emf:<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

INSERT {
	graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
		?parent emf:parentOf ?instance.
		?instance emf:hasParent ?parent.
	}
}
WHERE
{
	graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> { 
		?instance ptop:partOf ?parent 
	} 
}