PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


insert
{
GRAPH <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
	?relation emf:inverseRelation ?reverse.
}
} where {
?relation a emf:Relation . 
?relation emf:source ?source.
?relation emf:destination ?destination.

?reverse a emf:Relation . 
?reverse emf:source ?destination.
?reverse emf:destination ?source.
{
?relation emf:relationType ?relationType.
?reverse emf:relationType ?relationType.
} UNION {
?relation emf:relationType emf:hasChild.
?reverse emf:relationType ptop:partOf.
} UNION {
?relation emf:relationType ptop:partOf.
?reverse emf:relationType emf:hasChild.
} UNION {
?relation emf:relationType emf:processedBy.
?reverse emf:relationType emf:processedBy.
} UNION {
?relation emf:relationType emf:processedBy.
?reverse emf:relationType emf:processedBy.
}
}
