PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

PREFIX eqms: <http://www.sirma.com/ontologies/2014/03/eQMS#>
insert data {

graph <http://www.sirma.com/ontologies/2014/03/eQMS>  {

###  http://www.sirma.com/ontologies/2014/03/eQMS#isRecord

eqms:isRecord rdf:type owl:DatatypeProperty ;
              
              rdfs:label "Is Record"@en ;
              
              dc:creator "Hristo Lungov"@en ;
              
              skos:definition "Is Record"@en .
              
###  http://www.sirma.com/ontologies/2014/03/eQMS#rmAddress

eqms:rmAddress rdf:type owl:DatatypeProperty ;
               
               rdfs:label "Addressee"@en ;
               
               dc:creator "Hristo Lungov"@en ;
               
               skos:definition "RM Addressee"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmDateFiled

eqms:rmDateFiled rdf:type owl:DatatypeProperty ;
                 
                 rdfs:label "Date Filed"@en ;
                 
                 dc:creator "Hristo Lungov"@en ;
                 
                 skos:definition "RM Date Filed"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmDateReceived

eqms:rmDateReceived rdf:type owl:DatatypeProperty ;
                    
                    rdfs:label "Date Received"@en ;
                    
                    dc:creator "Hristo Lungov"@en ;
                    
                    skos:definition "RM Date Received"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmFormat

eqms:rmFormat rdf:type owl:DatatypeProperty ;
              
              rdfs:label "Format"@en ;
              
              dc:creator "Hristo Lungov"@en ;
              
              skos:definition "RM Format"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmIdentifier

eqms:rmIdentifier rdf:type owl:DatatypeProperty ;
                  
                  rdfs:label "RM Identifier"@en ;
                  
                  dc:creator "Hristo Lungov"@en ;
                  
                  skos:definition "Records Identifier"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmLocation

eqms:rmLocation rdf:type owl:DatatypeProperty ;
                
                rdfs:label "RM Location"@en ;
                
                dc:creator "Hristo Lungov"@en ;
                
                skos:definition "RM Location"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmMediaType

eqms:rmMediaType rdf:type owl:DatatypeProperty ;
                 
                 rdfs:label "Media Type"@en ;
                 
                 dc:creator "Hristo Lungov"@en ;
                 
                 skos:definition "RM Media Type"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmOriginatingOrganization

eqms:rmOriginatingOrganization rdf:type owl:DatatypeProperty ;
                               
                               rdfs:label "Originating Organization"@en ;
                               
                               dc:creator "Hristo Lungov"@en ;
                               
                               skos:definition "RM Originating Organization"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmOriginator

eqms:rmOriginator rdf:type owl:DatatypeProperty ;
                  
                  rdfs:label "Originator"@en ;
                  
                  dc:creator "Hristo Lungov"@en ;
                  
                  skos:definition "RM Originator"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmOtherAddressee

eqms:rmOtherAddressee rdf:type owl:DatatypeProperty ;
                      
                      rdfs:label "Other Addressee"@en ;
                      
                      dc:creator "Hristo Lungov"@en ;
                      
                      skos:definition "RM Other Addressee"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmPublicationDate

eqms:rmPublicationDate rdf:type owl:DatatypeProperty ;
                       
                       rdfs:label "Publication Date"@en ;
                       
                       dc:creator "Hristo Lungov"@en ;
                       
                       skos:definition "RM Publication Date"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#rmSupplementalMarkingList

eqms:rmSupplementalMarkingList rdf:type owl:DatatypeProperty ;
                               
                               rdfs:label "Supplementary Marking List"@en ;
                               
                               dc:creator "Hristo Lungov"@en ;
                               
                               skos:definition "RM Supplementary Marking List"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#template

eqms:template rdf:type owl:DatatypeProperty ;
              
              rdfs:label "Template"@en ;
              
              dc:creator "Hristo Lungov"@en ;
              
              skos:definition "Template"@en .
              

}
}