PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
insert data {
graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
  ptop:Organization                  
                  emf:definitionId "objectinstance"@en .

}

graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
emf:Customer emf:definitionId "objectinstance"@en .
}

}