PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

PREFIX pdm: <http://www.sirma.com/ontologies/2013/10/pdmConfiguration#>

insert data {

graph  <http://www.sirma.com/ontologies/2013/10/pdmConfiguration>  {

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#hasImplementation

pdm:hasImplementation rdf:type owl:ObjectProperty ;
                      
                      rdfs:label "Has Implementation"@en ;
                      
                      emf:isSearchable "true"^^xsd:boolean ;
                      
                      dc:creator "Kiril Penev"@en ;
                      
                      skos:definition "Relation between the design and the implementation of this design"@en ;
                      
                      rdfs:domain pdm:DesignObject ;
                      
                      rdfs:range pdm:InstanceObject ;
                      
                      owl:inverseOf pdm:hasDesign .
					  
}

}