PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

PREFIX pdm: <http://www.sirma.com/ontologies/2013/10/pdmConfiguration#>
insert data {

graph <http://www.sirma.com/ontologies/2013/10/pdmConfiguration>  {


###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#incidentReason

pdm:incidentReason rdf:type owl:DatatypeProperty ;
                   
                   rdfs:label "incident reason"@en ;
                   
                   dc:creator "Kiril Penev"@en ;
                   
                   skos:definition "TBD"@en ;
                   
                   rdfs:domain pdm:Incident .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#incidentResolution

pdm:incidentResolution rdf:type owl:DatatypeProperty ;
                       
                       rdfs:label "incident resolution"@en ;
                       
                       dc:creator "Kiril Penev"@en ;
                       
                       skos:definition "TBD"@en ;
                       
                       rdfs:domain pdm:Incident .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#partFailure

pdm:partFailure rdf:type owl:DatatypeProperty ;
                
                rdfs:label "part failure"@en ;
                
                dc:creator "Kiril Penev"@en ;
                
                skos:definition "TBD"@en ;
                
                rdfs:domain pdm:Incident .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#partOrder

pdm:partOrder rdf:type owl:DatatypeProperty ;
              
              rdfs:label "part order"@en ;
              
              dc:creator "Kiril Penev"@en ;
              
              skos:definition "TBD"@en ;
              
              rdfs:domain pdm:Incident .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#rma

pdm:rma rdf:type owl:DatatypeProperty ;
        
        rdfs:label "RMA"@en ;
        
        dc:creator "Kiril Penev"@en ;
        
        skos:definition "TBD"@en ;
        
        rdfs:domain pdm:Incident .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#serviceDispatch

pdm:serviceDispatch rdf:type owl:DatatypeProperty ;
                    
                    rdfs:label "service dispatch"@en ;
                    
                    dc:creator "Kiril Penev"@en ;
                    
                    skos:definition "TBD"@en ;
                    
                    rdfs:domain pdm:Incident .





}

}