PREFIX pdm: <http://www.sirma.com/ontologies/2013/10/pdmConfiguration#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
insert data {

graph <http://www.sirma.com/ontologies/2013/10/pdmConfiguration> {

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#configuredAsPartIn

pdm:assembledIn rdf:type owl:ObjectProperty ;
                   
                   rdfs:label "Assembled in"@en ;
                   
                   emf:isSearchable "true"^^xsd:boolean ;
                   
                   dc:creator "Kiril Penev"@en ;
                   
                   skos:definition "TBD"@en ;
                   
                   rdfs:range pdm:ProductInstance ;
                   
                   rdfs:domain pdm:PartInstance ;
                   
                   owl:inverseOf pdm:hasAssembledPart .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#configuredAsPartIn

pdm:configuredAsPartIn rdf:type owl:ObjectProperty ;
                   
                   rdfs:label "Configured as Part in"@en ;
                   
                   emf:isSearchable "true"^^xsd:boolean ;
                   
                   dc:creator "Kiril Penev"@en ;
                   
                   skos:definition "TBD"@en ;
                   
                   rdfs:range pdm:DesignObject ;
                   
                   rdfs:domain pdm:DesignObject ;
                   
                   owl:inverseOf pdm:hasConfiguredPart .
                   
                   
###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#engeneeringContact

pdm:hasAssembledPart rdf:type owl:ObjectProperty ;
                       
                       rdfs:label "Has Assembled Part"@en ;
                       
                       emf:isSearchable "true"^^xsd:boolean ;
                       
                       skos:definition "TBD"@en ;
                       
                       dc:creator "Kiril Penev"@en ;
                       
                       rdfs:range pdm:PartInstance ;
                       
                       rdfs:domain pdm:ProductInstance .
                       


}

}