PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

insert data {

graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#priority

emf:priority rdf:type owl:DatatypeProperty ;
             
             rdfs:label "Priority"@en ;
                          
             skos:definition "Events Priority. Chosen from predefined dictionary"@en ;
             
             dc:creator "Kiril Penev"@en ;
             
             rdfs:domain ptop:Event .
             
emf:communicatesWith rdf:type owl:ObjectProperty ;
               
               rdfs:label "communicates with"@en ;
               
               dc:creator "Kiril Penev"@en ;
               
               skos:definition "TBD"@en ;
               
               rdfs:domain emf:DomainObject ;
               
               rdfs:range emf:DomainObject .

emf:contactPerson emf:isSearchable "true"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasVendor

emf:hasVenor rdf:type owl:ObjectProperty ;
                    
                    rdfs:label "Has Vendor"@en ;
                    
                    emf:isSearchable "true"^^xsd:boolean ;
                    
                    skos:definition "TBD"@en ;
                    
                    dc:creator "Kiril Penev"@en ;
                    
                    rdfs:range emf:Vendor ;
                    
                    rdfs:domain emf:DomainObject .

emf:references emf:isSearchable "true"^^xsd:boolean .

}

}