PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

insert data {

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#defaultTemplate

emf:defaultTemplate rdf:type owl:DatatypeProperty ;
                    
                    rdfs:label "Default Template"@en ;
                    
                    skos:definition "Default template for the object"@en ;
                    
                    dc:creator "Kiril Penev"@en .
					
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#SavedFilter

emf:SavedFilter rdf:type owl:Class ;
                
                rdfs:label "Saved Filter"@en ;
                
                rdfs:subClassOf ptop:Object ;
                
                skos:definition "Saved filter data"@en ;
                
                emf:definitionId "savedfilterbase" ;
                
                dc:creator "Kiril Penev"@en .

}