PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

insert {
 GRAPH <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
  ?source ?type ?destination.
 }
} where {
	graph  <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
	 ?instance a emf:Relation;
	  emf:source ?source;
	  emf:destination ?destination;
	  emf:relationType ?type ;
	  emf:isActive "true"^^xsd:boolean.
	 ?source emf:isDeleted "false"^^xsd:boolean.
	 ?destination emf:isDeleted "false"^^xsd:boolean.
	 
	 ?instance emf:inverseRelation ?inverseRelation .
	}
}