PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

PREFIX eqms: <http://www.sirma.com/ontologies/2014/03/eQMS#>
insert data {

graph <http://www.sirma.com/ontologies/2014/03/eQMS>  {

###  http://www.sirma.com/ontologies/2014/03/eQMS#eisoDepartment

eqms:eisoDepartment rdf:type owl:DatatypeProperty ;
                    
                    rdfs:label "Department"@en ;
                    
                    dc:creator "Hristo Lungov"@en ;
                    
                    skos:definition "e-ISO Department"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#eisoDocNumber

eqms:eisoDocNumber rdf:type owl:DatatypeProperty ;
                   
                   rdfs:label "Document Number"@en ;
                   
                   dc:creator "Hristo Lungov"@en ;
                   
                   skos:definition "e-ISO Document Number"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#eisoDocType

eqms:eisoDocType rdf:type owl:DatatypeProperty ;
                 
                 rdfs:label "Document Type"@en ;
                 
                 dc:creator "Hristo Lungov"@en ;
                 
                 skos:definition "e-ISO Document Type"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#eisoRevision

eqms:eisoRevision rdf:type owl:DatatypeProperty ;
                  
                  rdfs:label "Revision"@en ;
                  
                  dc:creator "Hristo Lungov"@en ;
                  
                  skos:definition "e-ISO Document Revision Date"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#eisoSubDepartment

eqms:eisoSubDepartment rdf:type owl:DatatypeProperty ;
                       
                       rdfs:label "Functional Group"@en ;
                       
                       dc:creator "Hristo Lungov"@en ;
                       
                       skos:definition "e-ISO Sub Department / Functional Group"@en .



###  http://www.sirma.com/ontologies/2014/03/eQMS#footerStatus

eqms:footerStatus rdf:type owl:DatatypeProperty ;
                  
                  rdfs:label "Footer Status"@en ;
                  
                  skos:definition "Document Footer Status"@en ;
                  
                  dc:creator "Hristo Lungov"@en .

###  http://www.sirma.com/ontologies/2014/03/eQMS#isEiso

eqms:isEiso rdf:type owl:DatatypeProperty ;
            
            rdfs:label "Is e-ISO"@en ;
            
            dc:creator "Hristo Lungov" ;
            
            skos:definition "Boolean Marker for is e-ISO"@en ;
            
            rdfs:range xsd:boolean .


###  http://www.sirma.com/ontologies/2014/03/eQMS#owner

eqms:owner rdf:type owl:DatatypeProperty ;
           
           rdfs:label "Owner"@en ;
           
           skos:definition "Document Owner"@en ;
           
           dc:creator "Hristo Lungov"@en .

}
}