PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX pdm: <http://www.sirma.com/ontologies/2013/10/pdmConfiguration#>

insert data {

graph <http://www.sirma.com/ontologies/2013/10/pdmConfiguration>  {

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#descriptionOfChange

pdm:descriptionOfChange rdf:type owl:DatatypeProperty ;
                        
                        rdfs:label "Description of Change"@en ;
                        
                        skos:definition "Description of Change"@en ;
                        
                        dc:creator "Hristo Lungov"@en .
                        
###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#detailedChanges

pdm:detailedChanges rdf:type owl:DatatypeProperty ;
                    
                    rdfs:label "Detailed Changes"@en ;
                    
                    skos:definition "Detailed Changes"@en ;
                    
                    dc:creator "Hristo Lungov"@en .


###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#dispositionClarifications

pdm:dispositionClarifications rdf:type owl:DatatypeProperty ;
                              
                              rdfs:label "Disposition Clarifications"@en ;
                              
                              skos:definition "Disposition Clarifications"@en ;
                              
                              dc:creator "Hristo Lungov"@en .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#dmsLocation

pdm:dmsLocation rdf:type owl:DatatypeProperty ;
                
                rdfs:label "DMS Location"@en ;
                
                skos:definition "DMS Location"@en ;
                
                dc:creator "Hristo Lungov"@en .


###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#ecnAuthor

pdm:ecnAuthor rdf:type owl:DatatypeProperty ;
              
              rdfs:label "ECN Author"@en ;
              
              skos:definition "ECN Author"@en ;
              
              dc:creator "Hristo Lungov"@en .


###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#ecnDate

pdm:ecnDate rdf:type owl:DatatypeProperty ;
            
            rdfs:label "ECN Date"@en ;
            
            skos:definition "ECN Date"@en ;
            
            dc:creator "Hristo Lungov"@en .


###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#effectivityDate

pdm:effectivityDate rdf:type owl:DatatypeProperty ;
                    
                    rdfs:label "Effectivity Date"@en ;
                    
                    skos:definition "Effectivity Date"@en ;
                    
                    dc:creator "Hristo Lungov"@en .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#engineeringChangeId

pdm:engineeringChangeId rdf:type owl:DatatypeProperty ;
                        
                        rdfs:label "Engineering Change Identifier"@en ;
                        
                        skos:definition "Engineering Change Identifier"@en ;
                        
                        dc:creator "Hristo Lungov"@en .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#reaNumber

pdm:reaNumber rdf:type owl:DatatypeProperty ;
              
              rdfs:label "REA Number"@en ;
              
              dc:creator "Hristo Lungov"@en ;
              
              skos:definition "REA Number"@en .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#reaToClose

pdm:reaToClose rdf:type owl:DatatypeProperty ;
               
               rdfs:label "REA to Close"@en ;
               
               dc:creator "Hristo Lungov"@en ;
               
               skos:definition "REA to Close"@en .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#reasonForChange

pdm:reasonForChange rdf:type owl:DatatypeProperty ;
                    
                    rdfs:label "Reason for Change"@en ;
                    
                    dc:creator "Hristo Lungov"@en ;
                    
                    skos:definition "Reason for Change"@en .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#referenceOtherECN

pdm:referenceOtherECN rdf:type owl:DatatypeProperty ;
                      
                      rdfs:label "Reference Other ECN"@en ;
                      
                      dc:creator "Hristo Lungov"@en ;
                      
                      skos:definition "Reference Other ECN"@en .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#revisionFrom

pdm:revisionFrom rdf:type owl:DatatypeProperty ;
                 
                 rdfs:label "Revision From"@en ;
                 
                 dc:creator "Hristo Lungov"@en ;
                 
                 skos:definition "Revision From"@en .



###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#revisionTo

pdm:revisionTo rdf:type owl:DatatypeProperty ;
               
               rdfs:label "Revision To"@en ;
               
               dc:creator "Hristo Lungov"@en ;
               
               skos:definition "Revision To"@en .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#usedOn

pdm:usedOn rdf:type owl:DatatypeProperty ;
           
           rdfs:label "Used On"@en ;
           
           dc:creator "Hristo Lungov"@en ;
           
           skos:definition "Used On"@en .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#EngineeringChange

pdm:EngineeringChange rdf:type owl:Class ;
                      
                      rdfs:label "Engineering Change"@en ;
                      
                      rdfs:subClassOf pdm:DesignObject ;
                      
                      emf:isSearchable "true"^^xsd:boolean ;
                      
                      emf:isPartOfObjectLibrary "true"^^xsd:boolean ;
                      
                      skos:definition "Engineering Change"@en ;
                      
                      dc:creator "Hristo Lungov"@en ;
                      
                      emf:definitionId "objectinstance"@en .

}
}