PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX chd: <http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain#>

insert data { 

GRAPH <http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain>
{

chd:examinationPurpose rdf:type owl:DatatypeProperty ;
                       
                       rdfs:label "Examination Purpose"@en ;
                       
                       skos:definition "Examination Purpose of the Case"@en ;
                       
                       dc:creator "Kiril Penev"@en ;
                       
                       rdfs:domain emf:Case .
             
}
}