PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
insert data { 

GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>
{

emf:isActive rdf:type owl:DatatypeProperty ;
             
             rdfs:label "Is Active"@en ;
             
             dc:creator "Kiril Penev"@en ;
             
             rdfs:domain emf:Activity ;
             
             skos:definition "Shows if the current activity is in active state or it is Completed"@en .
             
}
}