PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

INSERT DATA {

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#filterCriteria

emf:filterCriteria rdf:type owl:DatatypeProperty ;
                   
                   rdfs:label "Filter Criteria"@en ;
                   
                   skos:definition "Criterias of the search filter"@en ;
                   
                   dc:creator "Kiril Penev"@en ;
                   
                   rdfs:domain emf:SavedFilter .



###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#filterType

emf:filterType rdf:type owl:DatatypeProperty ;
               
               rdfs:label "Filter Type"@en ;
               
               dc:creator "Kiril Penev"@en ;
               
               skos:definition "Type of the search filter - basic or advanced"@en ;
               
               rdfs:domain emf:SavedFilter .
			   
}