PREFIX pdm: <http://www.sirma.com/ontologies/2013/10/pdmConfiguration#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
delete {
pdm:hasPart rdfs:subPropertyOf emf:hasParent .
} insert {
pdm:hasPart rdfs:subPropertyOf emf:isParentOf .
} where {
pdm:hasPart rdfs:subPropertyOf emf:hasParent .
}