PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

PREFIX pdm: <http://www.sirma.com/ontologies/2013/10/pdmConfiguration#>
insert data {

graph <http://www.sirma.com/ontologies/2013/10/pdmConfiguration>  {


pdm:isPartOf rdf:type owl:ObjectProperty ;
             
             rdfs:label "is part of"@en ;
             
             emf:isSearchable "true"^^xsd:boolean ;
             
             skos:definition "Defines the owner of this part"@en ;
             
             dc:creator "Kiril Penev"@en ;
             
             owl:inverseOf pdm:hasPart .
             

pdm:Incident rdf:type owl:Class ;
             
             rdfs:label "Incident"@en ;
             
             rdfs:subClassOf pdm:PDMDomainObject ;
             
             emf:isPartOfObjectLibrary "true"^^xsd:boolean ;
             
             emf:isSearchable "true"^^xsd:boolean ;
             
             dc:creator "Kiril Penev"@en ;
             
             skos:definition "TODO"@en ;
             
             emf:definitionId "objectinstance"@en .
             

pdm:module rdf:type owl:DatatypeProperty ;
           
           rdfs:label "Module"@en ;
           
           dc:creator "Kiril Penev"@en ;
           
           skos:definition "Name of the Module"@en .
           

pdm:scrNumber rdf:type owl:DatatypeProperty ;
              
              rdfs:label "SCR Number"@en ;
              
              dc:creator "Kiril Penev"@en ;
              
              skos:definition "SCR Number"@en .
              

pdm:versionFound rdf:type owl:DatatypeProperty ;
                 
                 rdfs:label "Version Found"@en ;
                 
                 dc:creator "Kiril Penev"@en ;
                 
                 skos:definition "TBD"@en .
                 



}

}