PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX emf:<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>

WITH <http://ittruse.ittbg.com/data/enterpriseManagementFramework>
DELETE {
?source ?instance ?destination.
}
INSERT {
?instance emf:source ?source.
?instance emf:destination ?destination.
}
WHERE
{
?source ?instance ?destination.
?instance a emf:Relation.
}