PREFIX chd: <http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
delete data {

chd:Mark  emf:isPartOfObjectLibrary "true"^^xsd:boolean .
chd:Inscription  emf:isPartOfObjectLibrary "true"^^xsd:boolean .
emf:Company  emf:isPartOfObjectLibrary "true"^^xsd:boolean .
}