PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX pdm: <http://www.sirma.com/ontologies/2013/10/pdmConfiguration#>

insert data {

graph <http://www.sirma.com/ontologies/2013/10/pdmConfiguration> {

emf:contactPerson emf:isSearchable "true"^^xsd:boolean .

emf:hasThumbnail emf:isSearchable "true"^^xsd:boolean .

emf:isThumbnailOf emf:isSearchable "true"^^xsd:boolean .

pdm:createdWithECN rdf:type owl:ObjectProperty ;
                       
                       rdfs:label "created with ECN"@en ;
                       
                       emf:isSearchable "true"^^xsd:boolean ;
                       
                       skos:definition "created with ECN TBD"@en ;
                       
                       dc:creator "Kiril Penev"@en ;
                       
                       rdfs:domain pdm:DesignObject ;
                       
                       rdfs:range ptop:Document .

pdm:engeneeringContact rdf:type owl:ObjectProperty ;
                       
                       rdfs:label "Engeneering Contact"@en ;
                       
                       emf:isSearchable "true"^^xsd:boolean ;
                       
                       skos:definition "Engeneering contact"@en ;
                       
                       dc:creator "Kiril Penev"@en ;
                       
                       rdfs:domain pdm:PDMDomainObject ;
                       
                       rdfs:range emf:DomainUser ;
                       
                       rdfs:subPropertyOf emf:contactPerson .

pdm:hasConfigurationChartRevision rdf:type owl:ObjectProperty ;
                           
                           rdfs:label "has configuration chart revision"@en ;
                           
                           emf:isSearchable "true"^^xsd:boolean ;
                           
                           dc:creator "Kiril Penev"@en ;
                           
                           skos:definition "TBD"@en ;
                           
                           rdfs:range pdm:ProductLineConfigurationChartRevision ;
                           
                           rdfs:domain pdm:ProductConfigurationRevision .


pdm:hasCustomer rdf:type owl:ObjectProperty ;
                           
                           rdfs:label "has customer"@en ;
                           
                           emf:isSearchable "true"^^xsd:boolean ;
                           
                           dc:creator "Kiril Penev"@en ;
                           
                           skos:definition "TBD"@en ;
                           
                           rdfs:range emf:Customer ;
                           
                           rdfs:domain pdm:ProductInstance .

pdm:hasDesign rdf:type owl:FunctionalProperty ,
                       owl:ObjectProperty ;
              
              rdfs:label "has design"@en ;
              
              emf:isSearchable "true"^^xsd:boolean ;
              
              dc:creator "Kiril Penev"@en ;
              
              skos:definition "Specifies part or product instances` design"@en ;
              
              rdfs:range pdm:DesignObject ;
              
              rdfs:domain pdm:InstanceObject .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#hasDocument

pdm:hasDocument rdf:type owl:ObjectProperty ;
              
              rdfs:label "has document"@en ;
              
              emf:isSearchable "true"^^xsd:boolean ;
              
              dc:creator "Kiril Penev"@en ;
              
              skos:definition "TBD"@en .


###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#hasNextRevision

pdm:hasNextRevision rdf:type owl:ObjectProperty ;
               
               rdfs:label "has next revision"@en ;
               
               emf:isSearchable "true"^^xsd:boolean ;
               
               skos:definition "TBD"@en ;
               
               dc:creator "Kiril Penev"@en .

pdm:hasPart rdf:type owl:ObjectProperty ;
            
            rdfs:label "has part"@en ;
            
            emf:isSearchable "true"^^xsd:boolean ;
            
            dc:creator "Kiril Penev"@en ;
            
            skos:definition "Specifies which parts are used to build the product"@en ;
            
            rdfs:subPropertyOf emf:hasParent .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#hasPreviousRevision

pdm:hasPreviousRevision rdf:type owl:ObjectProperty ;
            
            rdfs:label "has previous revision"@en ;
            
            emf:isSearchable "true"^^xsd:boolean ;
            
            dc:creator "Kiril Penev"@en ;
            
            skos:definition "TBD"@en .


pdm:hasRevision emf:isSearchable "true"^^xsd:boolean .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#obsoletedWithECN

pdm:obsoletedWithECN rdf:type owl:ObjectProperty ;
                    
                    rdfs:label "obsolete with ECN"@en ;
                    
                    emf:isSearchable "true"^^xsd:boolean ;
                    
                    skos:definition "TBD"@en ;
                    
                    dc:creator "Kiril Penev"@en ;
                    
                    rdfs:range ptop:Document ;
                    
                    rdfs:domain pdm:DesignObject .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#sales

pdm:sales rdf:type owl:ObjectProperty ;
                    
                    rdfs:label "sales"@en ;
                    
                    emf:isSearchable "true"^^xsd:boolean ;
                    
                    skos:definition "TBD"@en ;
                    
                    dc:creator "Kiril Penev"@en ;
                    
                    rdfs:range ptop:ProductInstance ;
                    
                    rdfs:domain pdm:QVICompany .

###  http://www.sirma.com/ontologies/2013/10/pdmConfiguration#worksOn

pdm:worksOn rdf:type owl:ObjectProperty ;
                    
                    rdfs:label "works on"@en ;
                    
                    emf:isSearchable "true"^^xsd:boolean ;
                    
                    skos:definition "TBD"@en ;
                    
                    dc:creator "Kiril Penev"@en ;
                    
                    rdfs:range ptop:ProductInstance ;
                    
                    rdfs:domain emf:Department .



###  http://www.ontotext.com/proton/protontop#hasEmployee

ptop:hasEmployee emf:isSearchable "true"^^xsd:boolean .



###  http://www.ontotext.com/proton/protontop#hasLeader

ptop:hasLeader emf:isSearchable "true"^^xsd:boolean .



###  http://www.ontotext.com/proton/protontop#owns

ptop:owns emf:isSearchable "true"^^xsd:boolean .



###  http://www.ontotext.com/proton/protontop#partOf

ptop:partOf emf:isSearchable "true"^^xsd:boolean .

emf:Department emf:definitionId "objectinstance"@en ;

			emf:isPartOfObjectLibrary "true"^^xsd:boolean .

emf:DomainUser emf:definitionId "objectinstance"@en .

}

}