PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
delete {
emf:processes rdfs:domain emf:Task .
emf:processedBy rdfs:range emf:Task .
} insert {
GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>
{
emf:processes rdfs:domain emf:Activity .
emf:processedBy rdfs:range emf:Activity .
}
} where {
emf:processes rdfs:domain emf:Task .
emf:processedBy rdfs:range emf:Task .
}