SELECT DISTINCT ?instance ?instanceType where {
    ?targetId ptop:partOf ?instance .
    ?instance emf:instanceType ?instanceType .
    ?instance rdf:type ?type.
    ?instance emf:isDeleted "false"^^xsd:boolean .