PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
delete {
    chc:ConservationActivity rdfs:label "Conservation Activity"@en
} insert {
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        chc:ConservationActivity rdfs:label "Folder"@en
    }
} where {
}