PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
delete {
    ?instance chc:activityPurpose ?activityPurpose
} insert {
    graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
        ?instance chc:activityPurpose "NGA24116"  
    }
} where  {
    ?instance a emf:Project .
    ?instance chc:activityPurpose ?activityPurpose .
    filter(?activityPurpose = "NGA24104"
        || ?activityPurpose = "NGA24105"
        || ?activityPurpose = "NGA24106"
        || ?activityPurpose = "NGA24104"
        || ?activityPurpose = "NGA24107"
        || ?activityPurpose = "NGA24109"
        || ?activityPurpose = "NGA24110"
        || ?activityPurpose = "NGA24111"
        || ?activityPurpose = "NGA24112"
        || ?activityPurpose = "NGA24113"
        || ?activityPurpose = "NGA24114"
        || ?activityPurpose = "NGA24115"
        || ?activityPurpose = "NGA24118"
        || ?activityPurpose = "NGA24119")
}