PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>
DELETE DATA
{
   GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:hasAssignee sec:autoAssignParentPermissionRole "COLLABORATOR" .
    }
}