PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
delete {
    ?instance chc:sourceSystemId "NGASR25001"
} insert {
    graph <http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
        ?instance chc:sourceSystemId "NGASR25005"   
    }
}where  {
    ?instance a emf:Image .
    ?instance chc:sourceSystemId "NGASR25001" .
}