PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#> 
DELETE {
	 GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
		emf:Document sec:allowInheritParentPermissions "true"^^xsd:boolean .
		emf:Document sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
			
		}
}
INSERT {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
		emf:Document sec:allowInheritParentPermissions "false"^^xsd:boolean .
		emf:Document sec:allowInheritLibraryPermissions "true"^^xsd:boolean .
    }
}
WHERE {
    
}