PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
DELETE {
     emf:SavedFilter emf:definitionId "savedfilter".
} INSERT {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>   {
        emf:SavedFilter emf:definitionId "objectinstance".
    } 
} where {}