PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
DELETE {
    ?instance emf:instanceType ?type
} INSERT {
    GRAPH<http://ittruse.ittbg.com/data/enterpriseManagementFramework>   {
        ?instance emf:instanceType "objectinstance".
    } 
} where {
    ?instance emf:instanceType "savedfilter".
    ?instance emf:instanceType ?type.
}