PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

delete data {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:isAttachedTo rdfs:subPropertyOf ptop:partOf .
        emf:hasAttachment rdfs:subPropertyOf emf:hasChild .
    }
}