PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

delete{
    emf:ComplexValue ?p ?o.
    ?s1 ?p1 emf:ComplexValue.
    emf:DatedConcept ?p2 ?o2.
    ?s3 ?p3 emf:DatedConcept.
    emf:Discussion ?p4 ?o4.
    ?s5 ?p5 emf:Discussion.
	emf:DocumentSection ?p6 ?o6.
    ?s7 ?p7 emf:DocumentSection.
	emf:IntelligentDocument ?p8 ?o8.
    ?s9 ?p9 emf:IntelligentDocument.
	emf:Library ?p10 ?o10.
    ?s11 ?p11 emf:Library.
	emf:Tag ?p12 ?o12.
    ?s13 ?p13 emf:Tag.
	emf:Version ?p14 ?o14.
    ?s15 ?p15 emf:Version.
	emf:inWorkflow ?p16 ?o16.
	?s17 ?p17 emf:inWorkflow.
	?s18 emf:inWorkflow ?o18
} where {
    {
        emf:ComplexValue ?p ?o .
    } union {
        ?s1 ?p1 emf:ComplexValue
    } union {
        emf:DatedConcept ?p2 ?o2 
    } union {
        ?s3 ?p3 emf:DatedConcept
    } union {
        emf:Discussion ?p4 ?o4 
    } union {   
        ?s5 ?p5 emf:Discussion
	} union {
        emf:DocumentSection ?p6 ?o6
    } union {   
        ?s7 ?p7 emf:DocumentSection
	} union {
        emf:IntelligentDocument ?p8 ?o8
    } union {   
        ?s9 ?p9 emf:IntelligentDocument
	} union {
        emf:Library ?p10 ?o10
    } union {   
        ?s11 ?p11 emf:Library
	} union {
        emf:Tag ?p12 ?o12
    } union {   
        ?s13 ?p13 emf:Tag
	} union {
        emf:Version ?p14 ?o14
    } union {   
        ?s15 ?p15 emf:Version
	} union {
        emf:inWorkflow ?p16 ?o16
    } union {   
        ?s17 ?p17 emf:inWorkflow
    } union {   
        ?s18 emf:inWorkflow ?o18
    }
}