PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
delete {
    GRAPH<http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
        ?instance emf:viewContentId ?value.
    }
    emf:viewContentId a emf:DefinitionObjectProperty.
    emf:viewContentId a emf:DefinitionProperty.
} where {
    GRAPH<http://ittruse.ittbg.com/data/enterpriseManagementFramework> {
        ?instance emf:viewContentId ?value.
    }
}