PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

delete{
    emf:Service rdfs:subClassOf ptop:Object .
} insert {
graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Service
	emf:Service rdfs:subClassOf ptop:Service.
}
} where {
}