PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

delete {
		emf:DataImportSource skos:definition "Will use for importing data from spreadsheet in the system"@en.
		emf:DataImportReport skos:definition "Will receive information for the data validation"@en.
		emf:Help skos:definition "Help data"@en.    
}insert{
     GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
		emf:DataImportSource skos:definition "Source for importing large amount of data as objects. Generally represented as spreadsheet populated with data to import and information about the location of external files to import (if applicable)"@en.
		emf:DataImportReport skos:definition "Report showing results from data import validation. Contains descriptional information of validation results and location of not acceptable or wrong data (from the set of data to import), if any. Each validation is presented in separate report"@en.
		emf:Help skos:definition "Information, instructions or guide on how to do something, how to use functionalities or how a module works"@en.
    }
}where{}