
package com.sirma.codelist.ws.stub;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


// TODO: Auto-generated Javadoc
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Codelists", targetNamespace = "http://ws.ais.egov.sirma.com/codelists", wsdlLocation = "http://localhost:9766/services/Codelists?wsdl")
public class Codelists_Service
    extends Service
{

    /** The Constant CODELISTS_WSDL_LOCATION. */
    private final static URL CODELISTS_WSDL_LOCATION;
    
    /** The Constant logger. */
    private final static Logger logger = Logger.getLogger(com.sirma.codelist.ws.stub.Codelists_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sirma.codelist.ws.stub.Codelists_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9766/services/Codelists?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9766/services/Codelists?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CODELISTS_WSDL_LOCATION = url;
    }

    /**
     * Instantiates a new codelists_ service.
     *
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public Codelists_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new codelists_ service.
     */
    public Codelists_Service() {
        super(CODELISTS_WSDL_LOCATION, new QName("http://ws.ais.egov.sirma.com/codelists", "Codelists"));
    }

    /**
     * Gets the sOA p11 endpoint.
     *
     * @return the sOA p11 endpoint
     * returns CodelistsPortType
     */
    @WebEndpoint(name = "SOAP11Endpoint")
    public CodelistsPortType getSOAP11Endpoint() {
        return super.getPort(new QName("http://ws.ais.egov.sirma.com/codelists", "SOAP11Endpoint"), CodelistsPortType.class);
    }

    /**
     * Gets the secure soa p11 endpoint.
     *
     * @return the secure soa p11 endpoint
     * returns CodelistsPortType
     */
    @WebEndpoint(name = "SecureSOAP11Endpoint")
    public CodelistsPortType getSecureSOAP11Endpoint() {
        return super.getPort(new QName("http://ws.ais.egov.sirma.com/codelists", "SecureSOAP11Endpoint"), CodelistsPortType.class);
    }

    /**
     * Gets the secure soa p12 endpoint.
     *
     * @return the secure soa p12 endpoint
     * returns CodelistsPortType
     */
    @WebEndpoint(name = "SecureSOAP12Endpoint")
    public CodelistsPortType getSecureSOAP12Endpoint() {
        return super.getPort(new QName("http://ws.ais.egov.sirma.com/codelists", "SecureSOAP12Endpoint"), CodelistsPortType.class);
    }

    /**
     * Gets the sOA p12 endpoint.
     *
     * @return the sOA p12 endpoint
     * returns CodelistsPortType
     */
    @WebEndpoint(name = "SOAP12Endpoint")
    public CodelistsPortType getSOAP12Endpoint() {
        return super.getPort(new QName("http://ws.ais.egov.sirma.com/codelists", "SOAP12Endpoint"), CodelistsPortType.class);
    }

    /**
     * Gets the hTTP endpoint.
     *
     * @return the hTTP endpoint
     * returns CodelistsPortType
     */
    @WebEndpoint(name = "HTTPEndpoint")
    public CodelistsPortType getHTTPEndpoint() {
        return super.getPort(new QName("http://ws.ais.egov.sirma.com/codelists", "HTTPEndpoint"), CodelistsPortType.class);
    }

    /**
     * Gets the secure http endpoint.
     *
     * @return the secure http endpoint
     * returns CodelistsPortType
     */
    @WebEndpoint(name = "SecureHTTPEndpoint")
    public CodelistsPortType getSecureHTTPEndpoint() {
        return super.getPort(new QName("http://ws.ais.egov.sirma.com/codelists", "SecureHTTPEndpoint"), CodelistsPortType.class);
    }

}
