
package com.sirma.codelist.ws.stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


// TODO: Auto-generated Javadoc
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CodelistsPortType", targetNamespace = "http://ws.ais.egov.sirma.com/codelists")
public interface CodelistsPortType {


    /**
     * Gets the codelist cl.
     *
     * @param cl the cl
     * @return the codelist cl
     * @throws DataServiceFault the data service fault
     * returns java.util.List<com.sirma.codelist.ws.stub.Codelist>
     */
    @WebMethod(operationName = "_getcodelist_cl", action = "urn:_getcodelist_cl")
    @WebResult(name = "codelist", targetNamespace = "http://ws.ais.egov.sirma.com/codelists")
    @RequestWrapper(localName = "_getcodelist_cl", targetNamespace = "http://ws.ais.egov.sirma.com/codelists", className = "com.sirma.codelist.ws.stub.GetcodelistCl")
    @ResponseWrapper(localName = "codelists", targetNamespace = "http://ws.ais.egov.sirma.com/codelists", className = "com.sirma.codelist.ws.stub.Codelists")
    public List<Codelist> getcodelistCl(
        @WebParam(name = "cl", targetNamespace = "http://ws.ais.egov.sirma.com/codelists")
        String cl)
        throws DataServiceFault
    ;

    /**
     * Gets the codelists.
     *
     * @return the codelists
     * @throws DataServiceFault the data service fault
     * returns com.sirma.codelist.ws.stub.Codelists
     */
    @WebMethod(operationName = "_getcodelists", action = "urn:_getcodelists")
    @WebResult(name = "codelists", targetNamespace = "http://ws.ais.egov.sirma.com/codelists", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Codelists getcodelists()
        throws DataServiceFault
    ;

}
