package com.sirma.codelist.constants;

/**
 * No comment.
 * 
 * @author Autogenerated
 */
public final class CodeValueDef {

	/**
	 * No comment.
	 */
	public static final String CODE_VALUE = "CodeValue";
	/**
	 * No comment.
	 */
	public static final String ID_CODE_VALUE = "id";
	/**
	 * No comment.
	 */
	public static final String VERSION = "version";
	/**
	 * No comment.
	 */
	public static final String VALUE = "value";
	/**
	 * No comment.
	 */
	public static final String CODELIST = "codelist";
	/**
	 * No comment.
	 */
	public static final String MASTER_VALUE = "masterValue";
	/**
	 * No comment.
	 */
	public static final String DESCR = "descr";
	/**
	 * No comment.
	 */
	public static final String DESCR_EN = "descrEn";
	/**
	 * No comment.
	 */
	public static final String EXTRA1 = "extra1";
	/**
	 * No comment.
	 */
	public static final String EXTRA2 = "extra2";
	/**
	 * No comment.
	 */
	public static final String EXTRA3 = "extra3";
	/**
	 * No comment.
	 */
	public static final String ORDER = "order";
	/**
	 * No comment.
	 */
	public static final String SCOPE = "scope";
	/**
	 * No comment.
	 */
	public static final String COMMENT = "comment";

	/**
	 * No comment.
	 */
	private CodeValueDef() {
		// Hides functionality.
	}
}