SELECT ?instance (skos:Concept as ?instanceType) ?id ?title ?sepRoleUri ?sepRoleId ?sepRolePriority WHERE {
?instance skos:inScheme conc:SecurityRoleTypes ;
        skos:altLabel ?id ;
		skos:exactMatch ?sepRoleUri ;
        skos:prefLabel ?title .
    
    ?sepRoleUri skos:prefLabel ?sepRoleId ;
        skos:inScheme conc:SepBaseRoles ;
        skos:altLabel ?sepRolePriority .
}