SELECT DISTINCT ?instance ?instanceType WHERE {
    ?instance emf:instanceType ?instanceType .
    ?instance emf:isDeleted "false"^^xsd:boolean .
    ?instance a emf:ClassDescription.
    optional{
        ?instance dcterms:title ?title .
        filter(lang(?searchTitle) = ?lang)
    }
    optional {
        ?instance dcterms:title ?title_en .
        filter(lang(?title_en) = "en")
    }
    bind(if(bound(?title), lcase(?title), lcase(?title_en)) as ?title_)
} order by ?title_