PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE DATA {
    emf:Email a owl:Class ;
    rdfs:subClassOf emf:Document .
}; 
INSERT DATA {
	GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    emf:Email a owl:Class ;
        rdfs:subClassOf ptop:InformationResource ;
        emf:isUploadable "false"^^xsd:boolean ;
        emf:isPartOfObjectLibrary "true"^^xsd:boolean ;
        sec:allowInheritLibraryPermissions "true"^^xsd:boolean .
	}
}