SELECT DISTINCT ?instance ?instanceType WHERE {
    ?instance emf:instanceType ?instanceType .
    ?instance emf:contentId ?contentId .
    ?instance emf:isDeleted "false"^^xsd:boolean .
    {
        ?instance emf:ocrStatus ?notStarted .
    } UNION {
        OPTIONAL  {
            ?instance emf:ocrStatus ?ocrStatus .
            ?instance emf:isDeleted ?ocrStatusCheck  .
        } FILTER (  ! BOUND (  ?ocrStatusCheck  )  ) .
    } 
}