PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
insert data {

graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {

emf:actualEndDate rdf:type owl:DatatypeProperty ;
                 
                 rdfs:label "Actual End Date"@en ;
                 
                 skos:definition "Actual end date"@en ;
                 
                 dc:creator "Kiril Penev"@en ;
                 
                 rdfs:domain ptop:Event ;
            
            	 rdfs:range xsd:dateTime .
                 
}
                 
}