PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX hrc: <http://www.sirma.com/ontologies/2014/05/hrConfiguration#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
insert data {
GRAPH <http://www.sirma.com/ontologies/2014/05/hrConfiguration> {

hrc:contractNumber rdf:type owl:DatatypeProperty ;
                
                rdfs:label "Contract/Agreement No."@en ;
                
                skos:definition "Contract/Agreement No."@en ;
                
                dcterms:creator "Lidiya Dimitrova"@en ;
                
                rdfs:domain ptop:Document ;
                
                rdfs:range xsd:string .
                

hrc:drivingLicense rdfs:domain ptop:Person ;
                
                rdfs:range xsd:string .
                

hrc:effectiveDate rdf:type owl:DatatypeProperty ;
               
               rdfs:label "Effective date"@en ;
               
               skos:definition "Contract effective date"@en ;
               
               dcterms:creator "Lidiya Dimitrova"@en ;
               
               rdfs:domain ptop:Document ;
               
               rdfs:range xsd:dateTime .
               
hrc:education rdfs:domain ptop:Person ;
           
           rdfs:range xsd:string .
           

hrc:expirationDate rdf:type owl:DatatypeProperty ;
                
                rdfs:label "Expiration date"@en ;
                
                skos:definition "Contract expiration date"@en ;
                
                dcterms:creator "Lidiya Dimitrova"@en ;
                
                rdfs:domain ptop:Document ;
                
                rdfs:range xsd:dateTime .
                
hrc:language rdfs:domain ptop:Person ;
          
          rdfs:range xsd:string .
          
hrc:location rdfs:domain ptop:Person ;
          
          rdfs:range xsd:string .
          
hrc:occupation rdfs:domain ptop:Person ;
            
            rdfs:range xsd:string .
            
hrc:personType rdfs:domain ptop:Person ;
            
            rdfs:range xsd:string .
            


hrc:typeOfDeal rdf:type owl:DatatypeProperty ;
            
            rdfs:label "Deal Type"@en ;
            
            skos:definition "Contract type"@en ;
            
            dcterms:creator "Lidiya Dimitrova"@en ;
            
            rdfs:domain ptop:Event ;
            
            rdfs:range xsd:string .
			
###  http://www.sirma.com/ontologies/2014/05/hrConfiguration#totalBudget

hrc:totalBudget rdf:type owl:DatatypeProperty ;
             
             rdfs:label "Budget"@en ;
             
             dcterms:creator "Lidiya Dimtirova"@en ;
             
             skos:definition "Total project budget"@en ;
             
             rdfs:domain emf:Activity ;
             
             rdfs:range xsd:string .
}
}