PREFIX hrc: <http://www.sirma.com/ontologies/2014/05/hrConfiguration#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
insert data {

graph <http://www.sirma.com/ontologies/2014/05/hrConfiguration> {
###  http://www.sirma.com/ontologies/2014/05/hrConfiguration#physicalLocationOfTheContract

hrc:physicalLocationOfTheContract rdf:type owl:DatatypeProperty ;
                               
                               rdfs:label "Physical location of the contract"@en ;
                               
                               dcterms:creator "Lidiya Dimitrova"@en ;
                               
                               skos:definition "Physical location of the contract"@en ;
                               
                               rdfs:domain ptop:Document ;
                               
                               rdfs:range xsd:string .
                               
                               

###  http://www.sirma.com/ontologies/2014/05/hrConfiguration#territory

hrc:territory rdf:type owl:DatatypeProperty ;
           
           rdfs:label "Territory"@en ;
           
           dcterms:creator "Lidiya Dimitrova"@en ;
           
           skos:definition "The territory where the contract takes place"@en ;
           
           rdfs:domain ptop:Document ;
           
           rdfs:range xsd:string .
           
}
}