PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX pdm: <http://www.sirma.com/ontologies/2013/10/pdmConfiguration#>
PREFIX chd: <http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain#>
PREFIX eqms: <http://www.sirma.com/ontologies/2014/03/eQMS#>

delete data { 

emf:test_instance a ptop:Document ;
emf:emf:uri "emf:test_instance" ;
emf:type "type" ;
emf:isDeleted "true"^^xsd:boolean ;
emf:isActive "true"^^xsd:boolean ;
dcterms:identifier "123" ;
dcterms:title "title" ;
dcterms:description "description" ;
emf:status "DELETED" ;
emf:compact_header "<span class=truncate-element><a class=SUBMITTED emf:94df4770-3e3e-41d9-936b-11a267c6a1b7 has-tooltip href=/emf/entity/open.jsf?type=projectinstance&instanceId=emf:94df4770-3e3e-41d9-936b-11a267c6a1b7&currentPage=project uid=1><b>1 (Project for testing) Test (Submitted)</b></a></span>" ;
emf:default_header "<span class=truncate-element><a class=SUBMITTED emf:94df4770-3e3e-41d9-936b-11a267c6a1b7 has-tooltip href=/emf/entity/open.jsf?type=projectinstance&instanceId=emf:94df4770-3e3e-41d9-936b-11a267c6a1b7&currentPage=project uid=1><b>1 (Project for testing) Test (Submitted)</b></a></span>" ;
emf:owner emf:test_user ;
emf:hasAssignee emf:test_user ;
emf:hasAssignee emf:test_group ;
emf:hasPoolAssignee emf:test_group ;
emf:hasPoolAssignee emf:test_user ;
ptop:endTime "2014-09-09T00:00:00.000+03:00"^^xsd:dateTime ;
emf:mimetype "jpeg" ;
emf:content "content" ;
emf:plannedEndDate "2014-09-09T00:00:00.000+03:00"^^xsd:dateTime ;
emf:plannedStartDate "2014-09-09T22:28:54.119+03:00"^^xsd:dateTime ;
emf:priority "HIGH" ;
emf:createdOn "2014-06-05T08:50:05.706+03:00"^^xsd:dateTime ;
emf:modifiedOn "2014-06-05T08:50:05.706+03:00"^^xsd:dateTime ;
emf:fileModifiedDate "2014-06-05T08:50:05.706+03:00"^^xsd:dateTime ;
emf:fileCreatedDate "2014-06-05T08:50:05.706+03:00"^^xsd:dateTime ;
emf:createdBy emf:test_user ;
emf:modifiedBy emf:test_user ;
ptop:partOf emf:test_project ;
emf:hasParent emf:test_project ;
chd:accessionNumber "accessionNumber" ;
chd:examinationPurposeFTS "examinationPurposeFTS" ;
emf:externalID "external" ;
emf:fileName "fileName";
emf:purpose "test" ;
emf:departmentName "test" ;
pdm:machineModel "test" ;
pdm:versionFound "test" ;
pdm:scrNumber "test" ;
pdm:module "test" ;
pdm:incidentReason "test" ;
pdm:incidentResolution "test" ;
pdm:rma "test" ;
pdm:partOrder "test" ;
pdm:serviceDispatch "test" ;
pdm:partFailure "test" ;
eqms:isEiso "true"^^xsd:boolean;
eqms:eisoRevision "test";
eqms:eisoDepartment "test";
eqms:eisoSubDepartment "test";
eqms:eisoDocType "test";
eqms:eisoDocNumber "test";
eqms:footerStatus "test";
eqms:owner "owner";
dcterms:creator "creator" .

emf:test_project a emf:Project ;
emf:parentOf emf:test_instance .
     
emf:test_group a ptop:Group .
emf:test_user a emf:User .
emf:test_group ptop:hasMember emf:test_user .

}

