//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.10.14 at 04:01:21 PM EEST
//

package com.sirma.itt.seip.definition.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.persistence.oxm.annotations.XmlCDATA;

/**
 * <p>
 * Java class for complexFieldDefinition complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="complexFieldDefinition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="condition" type="{}conditionDefinition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="control" type="{}controlDefinition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="name" use="required" type="{}idType" /&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="multiValued" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="codelist" type="{}codelist" /&gt;
 *       &lt;attribute name="rnc" type="{}expressionType" /&gt;
 *       &lt;attribute name="label" type="{}labelIdType" /&gt;
 *       &lt;attribute name="tooltip" type="{}labelIdType" /&gt;
 *       &lt;attribute name="mandatory" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="displayType" type="{}displayTypeType" /&gt;
 *       &lt;attribute name="previewEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="dmsType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="filters" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" use="optional" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "complexFieldDefinition", propOrder = { "value", "condition", "control" })
public class ComplexFieldDefinition {

	/** The name. */
	@XmlAttribute(name = "name", required = true)
	protected String name;

	/** The type. */
	@XmlAttribute(name = "type")
	protected String type;

	/** The value. */
	@XmlCDATA
	protected String value;

	/** The condition. */
	protected List<ConditionDefinition> condition;

	/** The control. */
	protected ControlDefinition control;

	/** The order. */
	@XmlAttribute(name = "order")
	protected BigInteger order;

	/** The multi valued. */
	@XmlAttribute(name = "multiValued")
	protected Boolean multiValued;

	/** The codelist. */
	@XmlAttribute(name = "codelist")
	protected String codelist;

	/** The rnc. */
	@XmlAttribute(name = "rnc")
	protected String rnc;

	/** The label. */
	@XmlAttribute(name = "label")
	protected String label;

	/** The tooltip. */
	@XmlAttribute(name = "tooltip")
	protected String tooltip;

	/** The mandatory. */
	@XmlAttribute(name = "mandatory")
	protected Boolean mandatory;

	/** The display type. */
	@XmlAttribute(name = "displayType")
	protected String displayType;

	/** The preview empty. */
	@XmlAttribute(name = "previewEmpty")
	protected Boolean previewEmpty;

	/** The dms type. */
	@XmlAttribute(name = "dmsType")
	protected String dmsType;

	/** The filters. */
	@XmlAttribute(name = "filters")
	protected String filters;

	/** The uri. */
	@XmlAttribute(name = "uri")
	protected String uri;

	@XmlAttribute(name = "unique")
	protected Boolean unique;

	@XmlAttribute(name = "override")
	protected Boolean override;

	/**
	 * Gets the value of the value property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the condition property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the condition property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getCondition().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ConditionDefinition }
	 *
	 * @return the condition
	 */
	public List<ConditionDefinition> getCondition() {
		if (condition == null) {
			condition = new ArrayList<>();
		}
		return condition;
	}

	public void setCondition(List<ConditionDefinition> condition) {
		this.condition = condition;
	}

	/**
	 * Gets the value of the control property.
	 *
	 * @return possible object is {@link ControlDefinition }
	 */
	public ControlDefinition getControl() {
		return control;
	}

	/**
	 * Sets the value of the control property.
	 *
	 * @param value
	 *            allowed object is {@link ControlDefinition }
	 */
	public void setControl(ControlDefinition value) {
		control = value;
	}

	/**
	 * Gets the value of the order property.
	 *
	 * @return possible object is {@link BigInteger }
	 */
	public BigInteger getOrder() {
		return order;
	}

	/**
	 * Sets the value of the order property.
	 *
	 * @param value
	 *            allowed object is {@link BigInteger }
	 */
	public void setOrder(BigInteger value) {
		order = value;
	}

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setName(String value) {
		name = value;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setType(String value) {
		type = value;
	}

	/**
	 * Gets the value of the multiValued property.
	 *
	 * @return possible object is {@link Boolean }
	 */
	public Boolean isMultiValued() {
		return multiValued;
	}

	/**
	 * Sets the value of the multiValued property.
	 *
	 * @param value
	 *            allowed object is {@link Boolean }
	 */
	public void setMultiValued(Boolean value) {
		multiValued = value;
	}

	/**
	 * Gets the value of the codelist property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCodelist() {
		return codelist;
	}

	/**
	 * Sets the value of the codelist property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setCodelist(String value) {
		codelist = value;
	}

	/**
	 * Gets the value of the rnc property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getRnc() {
		return rnc;
	}

	/**
	 * Sets the value of the rnc property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setRnc(String value) {
		rnc = value;
	}

	/**
	 * Gets the value of the label property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * Sets the value of the label property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setLabel(String value) {
		label = value;
	}

	/**
	 * Gets the value of the tooltip property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getTooltip() {
		return tooltip;
	}

	/**
	 * Sets the value of the tooltip property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setTooltip(String value) {
		tooltip = value;
	}

	/**
	 * Gets the value of the mandatory property.
	 *
	 * @return possible object is {@link Boolean }
	 */
	public Boolean isMandatory() {
		return mandatory;
	}

	/**
	 * Sets the value of the mandatory property.
	 *
	 * @param value
	 *            allowed object is {@link Boolean }
	 */
	public void setMandatory(Boolean value) {
		mandatory = value;
	}

	/**
	 * Gets the value of the displayType property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getDisplayType() {
		return displayType;
	}

	/**
	 * Sets the value of the displayType property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setDisplayType(String value) {
		displayType = value;
		if (displayType != null) {
			displayType = displayType.toLowerCase();
		}
	}

	/**
	 * Gets the value of the previewEmpty property.
	 *
	 * @return possible object is {@link Boolean }
	 */
	public Boolean isPreviewEmpty() {
		return previewEmpty;
	}

	/**
	 * Sets the value of the previewEmpty property.
	 *
	 * @param value
	 *            allowed object is {@link Boolean }
	 */
	public void setPreviewEmpty(Boolean value) {
		previewEmpty = value;
	}

	/**
	 * Gets the value of the dmsType property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getDmsType() {
		return dmsType;
	}

	/**
	 * Sets the value of the dmsType property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setDmsType(String value) {
		dmsType = value;
	}

	/**
	 * Gets the value of the filters property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getFilters() {
		return filters;
	}

	/**
	 * Sets the value of the filters property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setFilters(String value) {
		filters = value;
	}

	/**
	 * Gets the value of the uri property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * Sets the value of the uri property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setUri(String value) {
		uri = value;
	}

	/**
	 * Getter for unique field. If true field have to be unique for a certain tenant.
	 *
	 * @return is field marked as unique.
	 */
	public Boolean getUnique() {
		return unique;
	}

	/**
	 * Setter for unique field. If true field have to be unique for a certain tenant.
	 *
	 * @param unique
	 *         - the value for unique field.
	 */
	public void setUnique(Boolean unique) {
		this.unique = unique;
	}

	/**
	 * Getter for override field.
	 *
	 * @return the value of the override field.
	 */
	public Boolean getOverride() {
		return override;
	}

	/**
	 * Setter for override field.
	 *
	 * @param override
	 *         - the value for override field.
	 */
	public void setOverride(Boolean override) {
		this.override = override;
	}
}
