//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.12 at 07:41:33 PM EET
//

package com.sirma.itt.seip.definition.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for filterType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="filterType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="codelist" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mode" type="{}checkTypes" default="in" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filterType", propOrder = { "value" })
public class FilterType {

	/** The value. */
	@XmlValue
	protected String value;

	/** The property. */
	@XmlAttribute(name = "property")
	protected String property;

	/** The codelist. */
	@XmlAttribute(name = "codelist")
	protected String codelist;

	/** The mode. */
	@XmlAttribute(name = "mode")
	protected CheckTypes mode;

	/**
	 * Gets the value of the value property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the property property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getProperty() {
		return property;
	}

	/**
	 * Sets the value of the property property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setProperty(String value) {
		property = value;
	}

	/**
	 * Gets the value of the codelist property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCodelist() {
		return codelist;
	}

	/**
	 * Sets the value of the codelist property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setCodelist(String value) {
		codelist = value;
	}

	/**
	 * Gets the value of the mode property.
	 *
	 * @return possible object is {@link CheckTypes }
	 */
	public CheckTypes getMode() {
		if (mode == null) {
			return CheckTypes.IN;
		} else {
			return mode;
		}
	}

	/**
	 * Sets the value of the mode property.
	 *
	 * @param value
	 *            allowed object is {@link CheckTypes }
	 */
	public void setMode(CheckTypes value) {
		mode = value;
	}

}
