//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.12.01 at 05:12:21 PM EET
//

package com.sirma.itt.seip.definition.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for renderAsType.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="renderAsType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HIDDEN"/&gt;
 *     &lt;enumeration value="VISIBLE"/&gt;
 *     &lt;enumeration value="DISABLED"/&gt;
 *     &lt;enumeration value="ENABLED"/&gt;
 *     &lt;enumeration value="REQUIRED"/&gt;
 *     &lt;enumeration value="READONLY"/&gt;
 *     &lt;enumeration value="DISABLE_SAVE"/&gt;
 *     &lt;enumeration value="PROPERTY"/&gt;
 *     &lt;enumeration value="OPTIONAL"/&gt;
 *     &lt;enumeration value="MANDATORY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "renderAsType")
@XmlEnum
public enum RenderAsType {

	/** The hidden. */
	HIDDEN,

	/** The visible. */
	VISIBLE,

	/** The disabled. */
	DISABLED,

	/** The enabled. */
	ENABLED,

	/** The required. */
	REQUIRED,

	/** The readonly. */
	READONLY,

	/** The disable save. */
	DISABLE_SAVE,

	/** The property. */
	PROPERTY,

	/** The optional. */
	OPTIONAL,

	/** The mandatory. */
	MANDATORY;

	/**
	 * Value.
	 *
	 * @return the string
	 */
	public String value() {
		return name();
	}

	/**
	 * From value.
	 *
	 * @param v
	 *            the v
	 * @return the render as type
	 */
	public static RenderAsType fromValue(String v) {
		return valueOf(v);
	}

}
