PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>

select ?instance ?title ?description where {
    ?instance a owl:Class .
    ?instance dcterms:title ?title .
    optional{
        ?instance dcterms:description ?description .
    }
}
