SELECT DISTINCT ?instance (owl:DatatypeProperty as ?instanceType) ?definition ?auditEvent ?title ?creator ?isSearchable ?isSystemProperty
(if (lang(?title)= "", "en", lang(?title)) as ?titleLanguage)
((if (bound(?domainClass1), ?domainClass1, ptop:Entity)) as ?domainClass)
((if (bound(?rangeClass1), ?rangeClass1, xsd:string)) as ?rangeClass)
WHERE {
    {
        ?property a owl:DatatypeProperty .
    } UNION {
        ?property a emf:DefinitionDataProperty .
    }
    ?property 
        rdfs:comment|skos:definition ?definition ;
        rdfs:label ?title .
    bind (str(?property) as ?instance) .
    optional {
        ?property rdfs:domain ?domainClass1 .
    } optional {
        ?property rdfs:range ?rangeClass1 .
    } optional {
        ?property emf:auditEvent ?auditEvent .
    } optional {
        ?property dc:creator ?creator
    } optional {
        ?property emf:isSearchable ?isSearchable .
    } optional {
        ?instance emf:isSystemProperty ?isSystemProperty .
    }
}