PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#> 
DELETE {
    emf:Case emf:isSearchable "false"^^xsd:boolean;
        emf:isPartOfObjectLibrary "false"^^xsd:boolean ;
		emf:isCreateable "false"^^xsd:boolean.
}
INSERT {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:Case emf:isSearchable "true"^^xsd:boolean;
            emf:isPartOfObjectLibrary "true"^^xsd:boolean ;
			emf:isCreateable "true"^^xsd:boolean;
			sec:allowInheritParentPermissions "true"^^xsd:boolean ;
			sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
    }
}
WHERE {
    
}