PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

delete data {
emf:Department emf:isSearchable "true"^^xsd:boolean .
emf:Company emf:isSearchable "true"^^xsd:boolean .
ptop:Organization emf:isSearchable "true"^^xsd:boolean .
emf:Vendor emf:isSearchable "true"^^xsd:boolean .
emf:Vendor emf:isPartOfObjectLibrary "true"^^xsd:boolean .
}