PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

delete {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    
        emf:Tag 
                        
                        emf:isPartOfObjectLibrary "true"^^xsd:boolean ;
                        emf:isSearchable "true"^^xsd:boolean .
            
            
        emf:hasTag 
        
                            emf:isSearchable "true"^^xsd:boolean .
    }
} insert  {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    
        emf:Tag 
                        
                        emf:isPartOfObjectLibrary "false"^^xsd:boolean ;
                        emf:isSearchable "false"^^xsd:boolean .
            
            
        emf:hasTag 
        
                            emf:isSearchable "false"^^xsd:boolean .
    }
} where { }