PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
DELETE {
    emf:IntelligentDocument emf:isSearchable "true"^^xsd:boolean.
}
INSERT {
    GRAPH <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:IntelligentDocument emf:isSearchable "false"^^xsd:boolean.
    }
}
WHERE {
    
}