PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>

INSERT DATA {
    GRAPH<http://www.sirma.com/ontologies/2014/11/security> {
        sec:allowPermissionOverride rdf:type owl:DatatypeProperty ;
            rdfs:label "Allow permission override"@en ;
            skos:definition "Allow permission override for automatically assigned permissions"@en ;
            dc:creator "Borislav Bonev"@en ;
            rdfs:domain owl:ObjectProperty ;
            rdfs:range xsd:boolean .
        
        sec:autoAssignParentPermissionRole rdf:type owl:DatatypeProperty ;
            rdfs:label "Automatic parent permission role"@en ;
            skos:definition "The role to assign of linked user to the parent of an instance"@en ;
            dc:creator "Borislav Bonev"@en ;
            rdfs:domain owl:ObjectProperty ;
            rdfs:range xsd:string .
        
        sec:autoAssignPermissionRole rdf:type owl:DatatypeProperty ;
            rdfs:label "Automatic permission role"@en ;
            skos:definition "The role to assign of linked user to a instance"@en ;
            dc:creator "Borislav Bonev"@en ;
            rdfs:domain owl:ObjectProperty ;
            rdfs:range xsd:string .
    }
}