PREFIX conc: <http://www.sirma.com/ontologies/2016/06/concepts#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

DELETE data {
	GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
	    conc:SepBaseRoles-NoPermission rdf:type skos:Concept .
	    conc:SepBaseRoles-NoPermission skos:altLabel "-1"^^xsd:integer .
	    conc:SepBaseRoles-NoPermission skos:definition "The user is forbidden to access the Entity and all of its children, if they inherit parent's permission"@en .
	    conc:SepBaseRoles-NoPermission skos:inScheme conc:SepBaseRoles .
	    conc:SepBaseRoles-NoPermission skos:prefLabel "NO_PERMISSION"@en .
	    
	    conc:SecurityRoleTypes-Forbidden rdf:type skos:Concept .
	    conc:SecurityRoleTypes-Forbidden skos:altLabel "Forbidden" .
	    conc:SecurityRoleTypes-Forbidden skos:definition "Security role that forbids access to the assigned users on the given Entity"@en .
	    conc:SecurityRoleTypes-Forbidden skos:exactMatch conc:SepBaseRoles-NoPermission .
	    conc:SecurityRoleTypes-Forbidden skos:inScheme conc:SecurityRoleTypes .
	    conc:SecurityRoleTypes-Forbidden skos:prefLabel "Forbidden role"@en .
    }
}