PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT DATA {
  GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        ptop:hasMember emf:isSearchable "true"^^xsd:boolean .
  }
}