PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

delete {
		emf:DataImportSource rdfs:subClassOf emf:DomainObject.
		emf:DataImportReport rdfs:subClassOf emf:DomainObject.
		emf:Product rdfs:subClassOf emf:DomainObject.
		emf:Service rdfs:subClassOf emf:DomainObject.
		emf:Issue rdfs:subClassOf emf:DomainObject.
		emf:Department rdfs:subClassOf emf:DomainObject.
		emf:Customer rdfs:subClassOf emf:DomainObject.
		ptop:Organization rdfs:subClassOf emf:DomainObject.
}insert{
     GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
		emf:DataImportSource rdfs:subClassOf ptop:Object.
		emf:DataImportReport rdfs:subClassOf ptop:Object.
		emf:Product rdfs:subClassOf ptop:Object.
		emf:Service rdfs:subClassOf ptop:Object.
		emf:Issue rdfs:subClassOf ptop:Object.
		ptop:Organization rdfs:subClassOf ptop:Group.
    }
}where{
}