PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
delete{
    emf:RecordSpace emf:isCreateable ?o.
} insert {
graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
	emf:RecordSpace emf:isCreateable "false"^^xsd:boolean ;
}
} where {
	emf:RecordSpace emf:isCreateable  ?o.
}