PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
delete {
?instance a ptop:Document .

} insert {
graph  <http://ittruse.ittbg.com/data/enterpriseManagementFramework>  {
?instance a emf:IntelligentDocument .
}
} where {
  ?instance a ptop:Document .
  ?instance emf:mimetype "text/html" .
  ?instance emf:isDeleted "false"^^xsd:boolean .
  }