PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

delete {
	emf:revision ?pred ?value .

} insert {
graph  <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>  {

	emf:revisionOfDefinition rdf:type owl:DatatypeProperty ;
                  
                  rdfs:label "Revision of Definition"@en ;
                  
                  dc:creator "Kiril Penev"@en ;
                  
                  skos:definition "The revision of the Definition of the instance"@en .

}
} where {
  emf:revision ?pred ?value .
}