PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>

delete {
	?instance emf:revision ?revision .
} insert {
	graph  <http://ittruse.ittbg.com/data/enterpriseManagementFramework>  {
		?instance emf:revisionOfDefinition ?revision .
	}
} where {
	?instance emf:revision ?revision .
}