PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
delete  {
   		emf:nextRevision emf:isSearchable "false"^^xsd:boolean.
        emf:previousRevision emf:isSearchable "false"^^xsd:boolean.
        emf:hasRevision emf:isSearchable "false"^^xsd:boolean.
        emf:isRevisionOf emf:isSearchable "false"^^xsd:boolean.
        emf:lastPublishedRevision emf:isSearchable "false"^^xsd:boolean.
} insert {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
        emf:nextRevision emf:isSearchable "true"^^xsd:boolean.
        emf:previousRevision emf:isSearchable "true"^^xsd:boolean.
        emf:hasRevision emf:isSearchable "true"^^xsd:boolean.
        emf:isRevisionOf emf:isSearchable "true"^^xsd:boolean.
        emf:lastPublishedRevision emf:isSearchable "true"^^xsd:boolean.
    }
} where {
}