PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>
insert data {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:hasAssignee sec:autoAssignPermissionRole "COLLABORATOR" ;
            sec:autoAssignParentPermissionRole "COLLABORATOR" ;
            sec:allowPermissionOverride "false"^^xsd:boolean .
        emf:hasPoolAssignee sec:autoAssignPermissionRole "COLLABORATOR" ;
            sec:autoAssignParentPermissionRole "COLLABORATOR" ;
            sec:allowPermissionOverride "false"^^xsd:boolean .
        emf:references sec:autoAssignPermissionRole "CONTRIBUTOR" .
        emf:hasWatcher sec:autoAssignPermissionRole "CONSUMER" .
    }
}