PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        
        emf:activityId rdf:type owl:DatatypeProperty ;
            rdfs:label "Activity ID"@en ;
            dc:creator "Kiril Penev"@en ;
            skos:definition "Activity ID"@en ;
            rdfs:domain emf:Activity ;
            rdfs:range xsd:string .
        
        emf:stopReason rdf:type owl:DatatypeProperty ;
            rdfs:label "Stop Reason"@en ;
            dc:creator "Kiril Penev"@en ;
            skos:definition "Reason for stopping a business process"@en ;
            rdfs:domain emf:Activity ;
            rdfs:range xsd:string .
        
        emf:BusinessProcess emf:isCreateable "true"^^xsd:boolean ;
            emf:isPartOfObjectLibrary "true"^^xsd:boolean .
    }
}