PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

insert data {

    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    
		###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#taskNotes

		   emf:taskNotes rdf:type owl:DatatypeProperty ;          
           rdfs:label "Task notes"@en ,
					   "Бележки свръзани с изпълнението на задачата"@bg ;					   
           dc:creator "Anna Radeva"@en ;          
           skos:definition "Notes related to the task outcome"@en ;         
           rdfs:domain emf:Activity ;                   
           rdfs:range xsd:string .
    }
}