SELECT DISTINCT ?uri ?propertyName ?propertyValue 
WHERE {
{
    ?uri ?propertyName ?propertyValue .
    %s
    FILTER EXISTS {
        ?propertyName a emf:DefinitionObjectProperty.
        ?propertyValue emf:isDeleted "false"^^xsd:boolean .
    }
} UNION {
    ?uri ?propertyName ?propertyValue .
    %s
    FILTER EXISTS {
        ?propertyName a emf:DefinitionDataProperty.
    }
} FILTER(