PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
DELETE {
    emf:Customer emf:isSearchable "true"^^xsd:boolean.
    emf:Department emf:isSearchable "true"^^xsd:boolean.
    emf:Vendor emf:isSearchable "true"^^xsd:boolean.
    ptop:Organization emf:isSearchable "true"^^xsd:boolean.
    emf:Customer emf:isCreateable "true"^^xsd:boolean.
    emf:Department emf:isCreateable "true"^^xsd:boolean.
    emf:Vendor emf:isCreateable "true"^^xsd:boolean.
    ptop:Organization emf:isCreateable "true"^^xsd:boolean.
}
INSERT {
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:Customer emf:isSearchable "false"^^xsd:boolean.
        emf:Department emf:isSearchable "false"^^xsd:boolean.
        emf:Vendor emf:isSearchable "false"^^xsd:boolean.
        ptop:Organization emf:isSearchable "false"^^xsd:boolean.
        emf:Customer emf:isCreateable "false"^^xsd:boolean.
        emf:Department emf:isCreateable "false"^^xsd:boolean.
        emf:Vendor emf:isCreateable "false"^^xsd:boolean.
        ptop:Organization emf:isCreateable "false"^^xsd:boolean.
    }
}
WHERE {
}