PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
delete {
    emf:Company emf:isPartOfObjectLibrary "true"^^xsd:boolean.
}
insert{
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:Company emf:isPartOfObjectLibrary "false"^^xsd:boolean.
    }
}where{
}