PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
delete {
    emf:createdBy rdfs:label "Created By"@en.
    emf:modifiedBy rdfs:label "Modified by"@en.
    emf:hasAssignee rdfs:label "Has Assignee"@en.
    emf:isAssigneeOf rdfs:label "Is Assignee Of"@en.
    emf:hasPrimaryImage rdfs:label "Has Primary Image"@en.
    emf:isPrimaryImageOf rdfs:label "Is primary image of"@en.
    emf:hasThumbnail rdfs:label "Has Thumbnail"@en.
    emf:isThumbnailOf rdfs:label "is thumbnail of"@en.
    emf:hasWatcher rdfs:label 	"Has Watcher"@en.
    emf:isWatcherOf rdfs:label "Is Watcher Of"@en.
    emf:parentOf rdfs:label "Parent Of"@en.
    emf:hasParent rdfs:label "Has Parent"@en.
    ptop:hasMember rdfs:label "has Member"@en.
    emf:isMemberOf rdfs:label "Is Member of"@en.
    ptop:involvedIn rdfs:label "Involved in"@en.
    ptop:hasParticipant rdfs:label "Has participant"@en.
}insert{
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:createdBy rdfs:label "system created by"@en.
        emf:modifiedBy rdfs:label "system modified by"@en.
        emf:hasAssignee rdfs:label "has assignee"@en.
        emf:isAssigneeOf rdfs:label "is assignee of"@en.
        emf:hasPrimaryImage rdfs:label "has primary imagey"@en.
        emf:isPrimaryImageOf rdfs:label "is primary image of"@en.
        emf:hasThumbnail rdfs:label "has thumbnail"@en.
        emf:isThumbnailOf rdfs:label "is thumbnail of"@en.
        emf:hasWatcher rdfs:label "has watcher"@en.
        emf:isWatcherOf rdfs:label "is watcher of"@en.
        emf:parentOf rdfs:label "parent of"@en.
        emf:hasParent rdfs:label "has parent"@en.
        ptop:hasMember rdfs:label "has member"@en.
        emf:isMemberOf rdfs:label "is member of"@en.
        ptop:involvedIn rdfs:label "involved in"@en.
        ptop:hasParticipant rdfs:label "has participant"@en.
    }
}
where{
}