PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
delete {
    emf:nextRevision rdfs:label "is revision of"@en.
    emf:isRevisionOf rdfs:label "Is revision of"@en.
}insert{
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
        emf:nextRevision rdfs:label "next revision"@en.
        emf:isRevisionOf rdfs:label "is revision of"@en.
    }
}
where{
}