PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
delete {
     	emf:hasPrimaryImage rdfs:label "has primary imagey"@en.  
}insert{
	graph  <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    	 emf:hasPrimaryImage rdfs:label "has primary image"@en.  
    }
}
where{
    
}