PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
delete {
    emf:processes rdfs:label "Processes"@en.
    emf:processedBy rdfs:label "Processed by"@en.
}insert{
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:processes rdfs:label "process"@en.
        emf:processedBy rdfs:label "processed by"@en.
    }
}
where{
}