PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
delete {
    emf:hasChild rdfs:label "Has child"@en.
    ptop:partOf rdfs:label "Part of"@en.
}insert{
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:hasChild rdfs:label "has child"@en.
        ptop:partOf rdfs:label "part of"@en.
    }
}
where{
}