PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>

delete {
     emf:lastPublishedRevision rdfs:label "Last published revision"@en.  
     emf:previousRevision rdfs:label "Previous revision"@en.
     emf:nextRevision rdfs:label "Next revision"@en.
     emf:hasRevision rdfs:label "Has revision"@en.
     emf:hasPoolAssignee rdfs:label "Has Pool Assignee"@en.
     emf:hasTemplate rdfs:label "Has Template"@en.
     emf:isPoolAssigneeTo rdfs:label "Is Pool Assignee To"@en. 
}insert{
  GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
     emf:lastPublishedRevision rdfs:label "last published revision"@en.  
     emf:previousRevision rdfs:label "previous revision"@en.
     emf:nextRevision rdfs:label "is revision of"@en.
     emf:hasRevision rdfs:label "has revision"@en.
     emf:hasPoolAssignee rdfs:label "has pool assignee"@en.
     emf:hasTemplate rdfs:label "has template"@en.
     emf:isPoolAssigneeTo rdfs:label "is pool assignee to"@en.
  }
}
where{
    
}