PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX chc: <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation#>
delete {
    emf:associatedWith emf:isSearchable "true"^^xsd:boolean.
    emf:isMemberOfCollection  emf:isSearchable "true"^^xsd:boolean.
    emf:inWorkflow  emf:isSearchable "true"^^xsd:boolean.
    emf:hasPoolAssignee  emf:isSearchable "true"^^xsd:boolean.
    emf:isPoolAssigneeTo  emf:isSearchable "true"^^xsd:boolean .
} insert {
    graph <http://www.sirma.com/ontologies/2016/02/culturalHeritageConservation> {
        emf:associatedWith emf:isSearchable "false"^^xsd:boolean .
        emf:isMemberOfCollection  emf:isSearchable "false"^^xsd:boolean.
        emf:inWorkflow  emf:isSearchable "false"^^xsd:boolean.
        emf:hasPoolAssignee  emf:isSearchable "false"^^xsd:boolean.
        emf:isPoolAssigneeTo  emf:isSearchable "false"^^xsd:boolean .
    }
} where {
}