PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
INSERT DATA {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    	emf:defaultView rdf:type owl:DatatypeProperty .
    	emf:revisionNumber rdf:type owl:DatatypeProperty.
    	emf:ocrLanguage rdf:type owl:DatatypeProperty.
    	emf:contentId rdf:type owl:DatatypeProperty.
    	emf:actualEndDate rdf:type owl:DatatypeProperty.
    	skos:prefLabel rdf:type owl:DatatypeProperty.
    	skos:altLabel rdf:type owl:DatatypeProperty.
    	emf:mobileNumber rdf:type owl:DatatypeProperty.
    	emf:internationality rdf:type owl:DatatypeProperty.
    	emf:isTopConcept rdf:type owl:DatatypeProperty.
    	dc:creator rdf:type owl:DatatypeProperty.
    	emf:isPrimaryTemplate rdf:type owl:DatatypeProperty.
    	emf:templatePurpose rdf:type owl:DatatypeProperty.
    }
}