PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX oa: <http://www.w3.org/ns/oa#>
insert data {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:auditEvent                 rdfs:label "Revisionsbegivenhed"@da .
        emf:definitionId               rdfs:label "Definition-ID"@da .
        emf:isPartOfObjectLibrary      rdfs:label "Er en del af objekt bibliotek"@da .
        emf:isSearchable               rdfs:label "Kan søges"@da .
        emf:acceptDataTypePattern      rdfs:label "Datatype mønster"@da .
        emf:isCreateable               rdfs:label "Er kreativ"@da .
        emf:isUploadable               rdfs:label "Kan uploades"@da .
        emf:isSystemProperty           rdfs:label "Er systemegenskab"@da .
        emf:isVersionable              rdfs:label "Er versionable"@da .
        emf:isMailboxSupportable       rdfs:label "Er postkassen understøttelig"@da .
        emf:partOfOntology             rdfs:label "En del af ontologi"@da .
        emf:associatedWith             rdfs:label "Forbundet med"@da .
        emf:blocks                     rdfs:label "Spærre"@da .
        emf:isBlockedBy                rdfs:label "Blokeres af"@da .
        emf:hasAgent                   rdfs:label "Har agent"@da .
        emf:hasClient                  rdfs:label "Har klient"@da .
        emf:hasMailAttachment          rdfs:label "Har Mail Attachment"@da .
        emf:hasModel                   rdfs:label "Har Model"@da .
        emf:hasRelation                rdfs:label "Har relation"@da .
        emf:hasSubsidiary              rdfs:label "Har datterselskab"@da .
        emf:inverseRelation            rdfs:label "Invers relation"@da .
        emf:isAgentOf                  rdfs:label "Er agent of"@da .
        emf:isAuthorOf                 rdfs:label "Er forfatter af"@da .
        emf:isClientOf                 rdfs:label "Er klient af"@da .
        emf:isDeliveredTo              rdfs:label "Leveres til"@da .
        emf:isDuplicatedBy             rdfs:label "Duplikere"@da .
        emf:isEmployeeOf		       rdfs:label "Er medarbejder af"@da .
        emf:isHeadOf			       rdfs:label "Er leder af"@da .
        emf:isIssuerOf			       rdfs:label "Еr forlæggeren af"@da .
        emf:isMemberOf			       rdfs:label "Er medlem af"@da .
        emf:isMemberOfCollection       rdfs:label "Er medlem af samling"@da .
        emf:isPoolAssigneeTo	       rdfs:label "Er potentielle ansvarlige til"@da .
        emf:hasPoolAssignee		       rdfs:label "Potentielle ansvarlige"@da .
        emf:isPrimaryImageOf           rdfs:label "Primært billede af"@da .
        emf:isProducerOf		       rdfs:label "Er producent af"@da .
        emf:isProviderOf		       rdfs:label "Er leverandør af"@da .
        emf:isRelatedTo			       rdfs:label "Er relateret til"@da .
        emf:isRecipientOf              rdfs:label "Er modtager af"@da .
        emf:isRevisionOf		       rdfs:label "Er revision af"@da .
        emf:isSubsidiaryOf		       rdfs:label "Er datterselskab af"@da .
        emf:issuedBy			       rdfs:label "Udstedt af"@da .
        emf:isThumbnailOf		       rdfs:label "Er thumbnail af"@da .
        emf:isVendorOf		           rdfs:label "Er leverandør af"@da .
        emf:isWatcherOf			       rdfs:label "Er observatør af"@da .
        emf:lastPublishedRevision      rdfs:label "Seneste publicerede revision"@da .
        emf:lastRevision		       rdfs:label "Seneste revision"@da .
        emf:loggedBy			       rdfs:label "Registreret af"@da .
        emf:markedForDownload	       rdfs:label "Markeret til download"@da .
        emf:modifiedBy			       rdfs:label "Opdateret af"@da .
        emf:completedBy				   rdfs:label "Afsluttet af"@da .
        emf:nextRevision		       rdfs:label "Næste revision"@da .
        emf:owner				       rdfs:label "Ejer"@da .
        emf:dependsOn			       rdfs:label "Afhænger af"@da .
        emf:ownedBy				       rdfs:label "Ejet af"@da .
        emf:parentOf			       rdfs:label "Overordnet kontekst for"@da .
        emf:previousRevision	       rdfs:label "Forrige revision"@da .
        emf:processedBy			       rdfs:label "Behandlet af"@da .
        emf:processes			       rdfs:label "Behandler"@da .
        emf:publishedBy			       rdfs:label "Publiceret af"@da .
        emf:references			       rdfs:label "Referencer"@da .
        emf:relationType		       rdfs:label "Relationstypen"@da .
        emf:replyTo 			       rdfs:label "Svar til"@da .
        emf:source				       rdfs:label "Kilde"@da .
        emf:isContactPersonOf	       rdfs:label "Er kontaktperson for"@da .
        emf:isDefaultLocation	       rdfs:label "Er standardplacering"@da .
        emf:mailboxAddress		       rdfs:label "Email adresse"@da .
        emf:hasAuthor			       rdfs:label "Har forfatter"@da .
        emf:hasDeliveredItem	       rdfs:label "Har leveret vare"@da .
        emf:hasEmployee			       rdfs:label "Har medarbejder"@da .
        emf:hasRecipient		       rdfs:label "Har modtager"@da .
        emf:hasReporter			       rdfs:label "Har rapportør"@da .
        emf:isReporterOf		       rdfs:label "Er rapportør afа"@da .
        emf:accumulatedActualEffort    rdfs:label "Akkumuleret faktisk timeforbrug"@da .
        emf:accumulatedEstimatedEffort rdfs:label "Akkumuleret estimeret timeforbrug"@da .
        emf:activityId				   rdfs:label "AktivitetsID"@da .
        emf:actualEffort			   rdfs:label "Faktisk timeforbrug"@da .
        emf:actualStartDate			   rdfs:label "Faktisk startdato"@da .
        emf:address					   rdfs:label "Adresse"@da .
        emf:addressCity				   rdfs:label "By"@da .
        emf:addressCountry			   rdfs:label "Land"@da .
        emf:addressState			   rdfs:label "Stat"@da .
        emf:addressTimeZone			   rdfs:label "Tidszone"@da .
        emf:addressWebSite			   rdfs:label "Websted"@da .
        emf:addressZip				   rdfs:label "Postnummer"@da .
        emf:altTitle				   rdfs:label "Alternativ titel"@da .
        emf:author 					   rdfs:label "Forfatter"@da .
        emf:avatar					   rdfs:label "Avatar (profilbillede)"@da .
        emf:businessSector			   rdfs:label "Erhvervssektor"@da .
        emf:businessType			   rdfs:label "Forretnings type"@da .
        emf:changeReason			   rdfs:label "Skift årsag"@da .
        emf:commentsOnSection		   rdfs:label "Kommentarer til sektion"@da .
        emf:companyRole  			   rdfs:label "Virksomhedens rolle"@da .
        emf:completedOn				   rdfs:label "Afsluttet den"@da .
        emf:completedReason			   rdfs:label "Afsluttet årsag"@da .
        emf:content					   rdfs:label "Indhold"@da .
        emf:ocrContent				   rdfs:label "OCR-indhold"@da .
        emf:ocrStatus				   rdfs:label "OCR-Status"@da .
        emf:countryName				   rdfs:label "Landenavn"@da .
        emf:createdOn				   rdfs:label "Oprettet den"@da .
        emf:currency    			   rdfs:label "Møntfod"@da .
        emf:defaultTemplate			   rdfs:label "Standardskabelon"@da .
        emf:defaultViewLocation		   rdfs:label "Standardplacering"@da .
        emf:departmentName			   rdfs:label "Afdeling/enhed"@da .
        emf:dmsId					   rdfs:label "DMS Id"@da .
        emf:duration				   rdfs:label "Varighed"@da .
        emf:email					   rdfs:label "E-mail"@da .
        emf:estimatedEffort			   rdfs:label "Estimeret timeforbrug"@da .
        emf:externalID				   rdfs:label "Ekstern ID"@da .
        emf:fileCreatedDate			   rdfs:label "Original Oprettet Dato"@da .
        emf:fileModifiedDate		   rdfs:label "Original senest ændret dato"@da .
        emf:fileName				   rdfs:label "Filnavn"@da .
        emf:flag					   rdfs:label "Flag"@da .
        emf:location			       rdfs:label "Placering"@da .
        emf:hasPosition				   rdfs:label "Har position"@da .
        emf:id 						   rdfs:label "ID"@da .
        emf:instanceType			   rdfs:label "Instans type"@da .
        emf:instantMessengerId 		   rdfs:label "Instans messenger ID"@da .
        emf:isActive				   rdfs:label "Er aktiv"@da .
        emf:isDeleted				   rdfs:label "Er slettet"@da .
        emf:issueDate				   rdfs:label "Udstedelsesdato"@da .
        emf:jobTitle				   rdfs:label "Jobtitel"@da .
        emf:majorVersion			   rdfs:label "Større version"@da .
        emf:mimetype				   rdfs:label "MIME-type"@da .
        emf:size					   rdfs:label "Forlimning"@da .
        emf:minorVersion			   rdfs:label "Mindre version"@da .
        emf:mobilePhoneNumber		   rdfs:label "Mobilnummer"@da .
        emf:modifiedOn				   rdfs:label "Opdateret"@da .
        emf:mutable					   rdfs:label "Foranderlig"@da .
        emf:organizationName		   rdfs:label "Organisation navn"@da .
        emf:phoneNumber				   rdfs:label "Telefonnummer"@da .
        emf:plannedEndDate			   rdfs:label "Planlagt slutdato"@da .
        emf:plannedStartDate		   rdfs:label "Planlagt startdato"@da .
        emf:priority				   rdfs:label "Prioritet"@da .
        emf:productGroup			   rdfs:label "Produktgruppe"@da .
        emf:productNumber			   rdfs:label "Produktnummer"@da .
        emf:publishedOn				   rdfs:label "Publiceret den"@da .
        emf:purpose 				   rdfs:label "Formål"@da .
        emf:revisionOfDefinition	   rdfs:label "Revision af definition"@da .
        emf:revisionType			   rdfs:label "Revisionstype"@da .
        emf:salutation				   rdfs:label "Salutation"@da .
        emf:searchCriteria			   rdfs:label "Søgekriterier"@da .
        emf:searchOrderDirection	   rdfs:label "Ordreretning"@da .
        emf:searchOrderBy			   rdfs:label "Bestil af"@da .
        emf:searchType				   rdfs:label "Søgetype"@da .
        emf:startDate				   rdfs:label "Startdato"@da .
        emf:status					   rdfs:label "Status"@da .
        emf:stopReason				   rdfs:label "Årsag til afbrydelse"@da .
        emf:subType					   rdfs:label "Undertype"@da .
        emf:templateRule			   rdfs:label "Skabelonregel"@da .
        emf:templateRuleDescription	   rdfs:label "Skabelon regel beskrivelse"@da .
        emf:thumbnailImage			   rdfs:label "Miniaturebillede"@da .
        emf:timeSpent				   rdfs:label "Tid brugt"@da .
        emf:transitionMatrix		   rdfs:label "Overgangsmatrice"@da .
        emf:type					   rdfs:label "Type"@da .
        emf:recurring				   rdfs:label "Tilbagevendende"@da .
        emf:revision				   rdfs:label "Definition revision"@da .
        emf:uri						   rdfs:label "URI"@da .
        emf:vatNumber				   rdfs:label "Momsnummer"@da .
        emf:version					   rdfs:label "Version"@da .
        emf:queriesContentId		   rdfs:label "Forespørgsler indhold id"@da .
        emf:queriesResultContentId	   rdfs:label "Forespørgsler resultater indhold id"@da .
        emf:viewContent				   rdfs:label "Se indhold"@da .
        emf:viewWidgetsContent		   rdfs:label "Se widget indhold"@da .
        emf:viewDefinition			   rdfs:label "Se definition"@da .
        emf:workDescription			   rdfs:label "Beskrivelse af arbejde"@da .
        emf:widthOfSubject			   rdfs:label "Værkets bredde"@da .
        emf:heightOfSubject			   rdfs:label "Højde"@da .
        emf:dimensionUnit			   rdfs:label "Egenskabsenhed"@da .
        emf:outcome 				   rdfs:label "Resultat/udfald"@da .
        emf:taskNotes				   rdfs:label "Opgavenoter"@da .
        emf:integrated				   rdfs:label "Integreret"@da .
        emf:issueType				   rdfs:label "Emnetype"@da .
        emf:uniqueId				   rdfs:label "Unikt ID"@da .
        emf:defaultView				   rdfs:label "Standardvisning"@da .
        emf:revisionNumber			   rdfs:label "Revisionsnummer"@da .
        emf:ocrLanguage				   rdfs:label "OCR sprog"@da .
        emf:contentId				   rdfs:label "Indhold ID"@da .
        emf:actualEndDate			   rdfs:label "Faktisk slutdato"@da .
        emf:mobileNumber		       rdfs:label "Mobilnummer"@da .
        emf:internationality		   rdfs:label "Internationalitet"@da .
        emf:isTopConcept			   rdfs:label "Er topkoncept"@da .
        emf:templatePurpose			   rdfs:label "Formål skabelon"@da .
        emf:isPrimaryTemplate		   rdfs:label "Primær skabelon"@da .
        emf:classCategory			   rdfs:label "Klasse kategori"@da .
        skos:prefLabel				   rdfs:label "Foretrukken label"@da .
        skos:altLabel				   rdfs:label "Alternativ label"@da .
        dc:creator					   rdfs:label "Skaberen"@da .
        emf:Activity				   rdfs:label "Aktivitet"@da .
        emf:Audio					   rdfs:label "Audio"@da .
        emf:BusinessProcess			   rdfs:label "Workflow"@da .
        emf:BusinessProcessTask		   rdfs:label "Forretningsproces opgave"@da .
        emf:Case					   rdfs:label "Sag"@da .
        emf:ClassDescription		   rdfs:label "Klasse beskrivelse"@da .
        emf:Company				       rdfs:label "Company"@da .
        emf:Customer				   rdfs:label "Kunde"@da .
        emf:DefinitionProperty		   rdfs:label "Definition ejendom"@da .
        emf:DefinitionDataProperty	   rdfs:label "Definition af data ejendom"@da .
        emf:DefinitionObjectProperty   rdfs:label "Definition af objekt ejendom"@da .
        emf:Department				   rdfs:label "Afdeling/enhed"@da .
        emf:Document			       rdfs:label "Dokument"@da .
        emf:DataImportSource		   rdfs:label "Dataimport Kilde"@da .
        emf:DataImportReport		   rdfs:label "Dataimport Rapport"@da .
        emf:File					   rdfs:label "Fil"@da .
        emf:Folder				       rdfs:label "Folder"@da .
        emf:Group					   rdfs:label "Gruppe"@da .
        emf:Help					   rdfs:label "Hjælp"@da .
        emf:helpTarget				   rdfs:label "Hjælp emne"@da .
        emf:Image					   rdfs:label "Billede"@da .
        emf:Media					   rdfs:label "Medieobjekt"@da .
        emf:Meeting					   rdfs:label "Møde"@da .
        emf:Product					   rdfs:label "Produkt"@da .
        emf:Project					   rdfs:label "Projekt"@da .
        emf:Relation				   rdfs:label "Relation"@da .
        emf:SavedSearch				   rdfs:label "Gemt søgning"@da .
        emf:Service					   rdfs:label "Service"@da .
        emf:Space					   rdfs:label "Plads"@da .
        emf:Task					   rdfs:label "Opgave"@da .
        emf:User				       rdfs:label "Bruger"@da .
        emf:Vendor					   rdfs:label "Sælger"@da .
        emf:Video					   rdfs:label "Video"@da .
        emf:Template				   rdfs:label "Skabelon"@da .
        emf:Definition				   rdfs:label "Definition"@da .
        emf:Email					   rdfs:label "E-mail"@da .
        emf:Issue					   rdfs:label "Emne"@da .
        oa:Annotation				   rdfs:label "Annotation"@da .
        skos:Concept				   rdfs:label "Koncept"@da .
        skos:Collection				   rdfs:label "Kollektion"@da .
        skos:ConceptScheme			   rdfs:label "Konceptskema"@da .
        emf:RecordSpace				   rdfs:label "Arkivplads"@da .
        emf:destination				   rdfs:label "Bestemmelsessted"@da .
        emf:isAssigneeOf			   rdfs:label "Er ansvarlig for"@da .
        emf:hasAssignee  			   rdfs:label "Har ansvarlig"@da .
        emf:hasFavourite  			   rdfs:label "Har favorit"@da .
        emf:hasVendor  			   	   rdfs:label "Har forhandler"@da .
        emf:hasHead  			   	   rdfs:label "Har leder"@da .
        emf:hasWatcher 			   	   rdfs:label "Har observatør"@da .
        emf:hasParent 			   	   rdfs:label "Har overordnet kontekst"@da .
        emf:hasProducer			   	   rdfs:label "Har producent"@da .
        emf:hasRevision			   	   rdfs:label "Har revision"@da .
        emf:hasTemplate				   rdfs:label "Har skabelon"@da .
        emf:hasTag					   rdfs:label "Har tag"@da .
        emf:hasThumbnail  			   rdfs:label "Har thumbnail"@da .
        emf:hasProvider  			   rdfs:label "Har udbyder"@da .
        emf:hasChild  			   	   rdfs:label "Har underordnet kontekst"@da .
        emf:commentsOn 			   	   rdfs:label "Kommentarer til sektion"@da .
        emf:contactPerson		   	   rdfs:label "Kontaktperson"@da .
        emf:createdBy 			   	   rdfs:label "Oprettet af"@da .
        emf:templateVersion		   	   rdfs:label "Skabelonversion"@da .
        emf:hasAttachment		   	   rdfs:label "Vedhæftede filer"@da .
        emf:isAttachedTo		   	   rdfs:label "Vedhæftet til"@da .
		emf:isAttachmentTo		   	   rdfs:label "Er vedhæftning af"@da .
		emf:hasPrimaryImage		   	   rdfs:label "Primære billeder"@da .
    }
}