PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX oa: <http://www.w3.org/ns/oa#>

insert data {

graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#auditEvent
  emf:auditEvent rdfs:label "Tilintarkastustapahtuma"@fi, "Audit-Ereignis"@de .
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#definitionId
  emf:definitionId rdfs:label "Määritelmä id"@fi ,"Definitions-ID"@de .
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isPartOfObjectLibrary
  emf:isPartOfObjectLibrary rdfs:label "Osa osastokirjastosta"@fi , "Ist Teil der Objektbibliothek"@de .
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isSearchable
  emf:isSearchable rdfs:label "On haettavissa"@fi , "Ist durchsuchbar"@de .
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#acceptDataTypePattern
  emf:acceptDataTypePattern rdfs:label "Datatyyppikuvio"@fi , "Datentypmuster"@de . 
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isCreateable
  emf:isCreateable rdfs:label "Voidaan luoda"@fi , "Ist erstellbar"@de .
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isUploadable
  emf:isUploadable rdfs:label "Voidaan ladata"@fi , "Kann hochgeladen werden"@de .
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isSystemProperty
  emf:isSystemProperty rdfs:label "Järjestelmän ominaisuus"@fi , "Ist Systemeigenschaft"@de .

  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isVersionable
  emf:isVersionable rdfs:label "Voidaan verrata"@fi , "Ist versionierbar"@de .
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isMailboxSupportable
  emf:isMailboxSupportable rdfs:label "Onko postilaatikko tukevaa"@fi  , "Ist Mailbox unterstützbar"@de .
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#associatedWith
  emf:associatedWith rdfs:label "Liittyvä"@fi , "Verknüpft mit"@de .

  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#blocks
  emf:blocks rdfs:label "Lohkot"@fi , "Blöcke"@de , "Блокира"@bg .
        
  ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isBlockedBy
  emf:isBlockedBy rdfs:label "On estetty"@fi , "Wird blockiert von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#commentsOn
 emf:commentsOn rdfs:label "Kommentteja"@fi , "Kommentare zu"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#completedBy
 emf:completedBy rdfs:label "Täydentänyt"@fi , "Vervollständigt von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#contactPerson
 emf:contactPerson rdfs:label "Yhteyshenkilö"@fi , "Gesprächspartner"@de . 

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#createdBy
 emf:createdBy rdfs:label "Luonut"@fi , "Erstellt von"@de . 

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#dependsOn
 emf:dependsOn rdfs:label "Riippuu"@fi  , "Kommt drauf an"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#destination
 emf:destination rdfs:label "Määränpää"@fi , "Ziel"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasAgent
 emf:hasAgent rdfs:label "Onko agentti"@fi , "Hat Bevollmächtigter"@de .
   
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasAssignee
 emf:hasAssignee rdfs:label "Onko vastaanottaja"@fi , "Hat Bevollmächtigter"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasAttachment
 emf:hasAttachment rdfs:label "On kiinnitys"@fi , "hat Anhang"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasChild
 emf:hasChild rdfs:label "Onko lapsi"@fi , "Hat ein Kind"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasMailAttachment
 emf:hasMailAttachment rdfs:label "Onko sähköpostiliite"@fi , "Hat Mail-Anhang"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasModel
 emf:hasModel rdfs:label "Onko malli"@fi , "Hat Modell"@de .
 
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasRelation
 emf:hasRelation rdfs:label "On suhde"@fi  , "Hat Beziehung"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasTemplate
 emf:hasTemplate rdfs:label "Onko malli"@fi .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#templateVersion                          
 emf:templateVersion rdfs:label "Mallipohja"@fi , "Vorlagenversion"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasParent
 emf:hasParent rdfs:label "Onko vanhempi"@fi  , "Hat Elternteil"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasPoolAssignee
 emf:hasPoolAssignee rdfs:label "On Pool Assignee"@fi  , "Hat einen Pool-Beauftragten"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasPrimaryImage
 emf:hasPrimaryImage rdfs:label "Onko ensisijainen kuva"@fi  , "Hat das primäre Image"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasTag
 emf:hasTag rdfs:label "Onko tunniste"@fi , "Hat Tag"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasRevision
 emf:hasRevision rdfs:label "Onko tarkistus"@fi , "Hat Überarbeitung"@de .
 
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasThumbnail
 emf:hasThumbnail rdfs:label "On Thumbnail"@fi , "Hat Miniaturansicht"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasFavourite
 emf:hasFavourite rdfs:label "On suosikki"@fi , "Hat Favorit"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasVendor
 emf:hasVendor rdfs:label "Onko myyjä"@fi  , "Hat Verkäufer"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasWatcher
 emf:hasWatcher rdfs:label "Onko Watcher"@fi , "Hat Wächter"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#inverseRelation
 emf:inverseRelation rdfs:label "käänteinen suhde"@fi , "umgekehrte Beziehung"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isAgentOf
 emf:isAgentOf rdfs:label "On Agent Of"@fi , "Ist Agent von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isAssigneeOf
 emf:isAssigneeOf rdfs:label "Onko Assignee Of"@fi , "Ist Beauftragter von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isAttachedTo
 emf:isAttachedTo rdfs:label "Liitetään mukaan"@fi , "Ist beigefügt"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isAttachmentTo                 
 emf:isAttachmentTo rdfs:label "On liittäminen"@fi , "Ist Anhang von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isDuplicatedBy
 emf:isDuplicatedBy rdfs:label "Kopioidaan"@fi , "Wird dupliziert von"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isMemberOf
 emf:isMemberOf rdfs:label "Onko jäsen"@fi , "Ist Mitglied von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isMemberOfCollection
 emf:isMemberOfCollection rdfs:label "Onko jäsen kokoelmasta"@fi , "Ist Mitglied der Sammlung"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isPoolAssigneeTo
 emf:isPoolAssigneeTo rdfs:label "On Pool Assignee To"@fi , "Ist Pool-Beauftragter zu"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isPrimaryImageOf
 emf:isPrimaryImageOf rdfs:label "On ensisijainen kuva"@fi , "Ist das primäre Bild von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isRelatedTo
 emf:isRelatedTo rdfs:label "On sukua"@fi , "Bezieht sich auf"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isRevisionOf
 emf:isRevisionOf rdfs:label "Tarkistetaanko"@fi , "Ist Revision von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isThumbnailOf
  emf:isThumbnailOf rdfs:label "On pikkukuva"@fi , "ist ein Vorschaubild von"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isVendorOf
  emf:isVendorOf rdfs:label "Onko toimittaja"@fi , "Ist Verkäufer von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isWatcherOf
  emf:isWatcherOf rdfs:label "Onko Watcher Of"@fi , "Ist Beobachter von"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#lastPublishedRevision
 emf:lastPublishedRevision rdfs:label "Viimeisin julkaistu versio"@fi , "Letzte veröffentlichte Überarbeitung"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#lastRevision
 emf:lastRevision rdfs:label "Viimeinen tarkistus"@fi , "Letzte Überarbeitung"@de .	
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#loggedBy
 emf:loggedBy rdfs:label "Kirjautunut"@fi , "Angemeldet von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#markedForDownload
 emf:markedForDownload rdfs:label  "Merkitty lataukseen"@fi , "Zum Download markiert"@de .
     
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#modifiedBy
 emf:modifiedBy rdfs:label "Muokannut"@fi , "Angepasst von"@de .
				  
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#nextRevision
 emf:nextRevision rdfs:label "Seuraava tarkistus"@fi , "Nächste Überarbeitung"@de .
             
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#owner
 emf:owner rdfs:label "Omistaja"@fi , "Inhaber"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#ownedBy
 emf:ownedBy rdfs:label "Omistuksessa"@fi , "Gehört"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#parentOf
 emf:parentOf rdfs:label "Vanhempi"@fi , "Elternteil von"@de .
           
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#previousRevision
 emf:previousRevision rdfs:label "Edellinen versio"@fi , "Vorherige Überarbeitung"@de .
               
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#processedBy
 emf:processedBy rdfs:label "Prosessoinut"@fi ,"Verarbeitet von"@de .
	
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#processes
 emf:processes rdfs:label "Prosessit"@fi , "Prozesse"@de . 
             
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#publishedBy
 emf:publishedBy rdfs:label "Julkaissut"@fi , "Veröffentlicht von"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#references
 emf:references rdfs:label "Viitteet"@fi , "Verweise"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#relationType
 emf:relationType rdfs:label "Suhteiden tyyppi"@fi , "Beziehungstyp"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#replyTo
 emf:replyTo rdfs:label "Vastata"@fi , "Antwort an"@de .
  
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#source
 emf:source rdfs:label "Lähde"@fi , "Quelle"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isDefaultLocation
 emf:isDefaultLocation rdfs:label "Oletuspaikka"@fi , "Ist der Standardstandort"@de .
	
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mailboxAddress       
 emf:mailboxAddress rdfs:label "Sähköpostiosoite"@fi , "E-Mail-Addresse"@de .
	
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasReporter
 emf:hasReporter rdfs:label "Onko Reporter"@fi , "Hat Reporter"@de . 

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isReporterOf
 emf:isReporterOf rdfs:label "Onko Reporter Of"@fi , "Ist Reporter von"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#accumulatedActualEffort
 emf:accumulatedActualEffort rdfs:label "Kertynyt todellinen ponnistus"@fi , "Kumulierter tatsächlicher Aufwand"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#accumulatedEstimatedEffort
 emf:accumulatedEstimatedEffort rdfs:label "Kertynyt arvioitu ponnistus"@fi , "Kumulierter geschätzter Aufwand"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#activityId
 emf:activityId rdfs:label "Toimintotunnus"@fi , "Aktivitäts-ID"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#actualEffort
 emf:actualEffort rdfs:label "Todelliset ponnistelut"@fi , "Tatsächliche Anstrengung"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#actualStartDate
 emf:actualStartDate rdfs:label "Todellinen alkamispäivä"@fi , "Aktuelles Startdatum"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#actualStartDate
 emf:actualStartDate rdfs:label "Todellinen alkamispäivä"@fi , "Aktuelles Startdatum"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#address
 emf:address rdfs:label "Osoite"@fi , "Adresse"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#altTitle
 emf:altTitle rdfs:label "Vaihtoehtoinen nimi"@fi , "Alternativer Titel"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#author
 emf:author rdfs:label "kirjailija"@fi , "Autor"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#avatar
 emf:avatar rdfs:label "Avatar"@fi , "Benutzerbild"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#businessSector
 emf:businessSector rdfs:label "Liiketoiminta-alue"@fi , "Geschäftsbereich"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#businessType
 emf:businessType rdfs:label "Yritystyyppi"@fi , "Unternehmensart"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#changeReason
 emf:changeReason rdfs:label "Muuttaa syytä"@fi , "Grund ändern"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#commentsOnSection
 emf:commentsOnSection rdfs:label "Huomautukset osasta"@fi , "Kommentare zum Abschnitt"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#completedOn
 emf:completedOn rdfs:label "Valmistunut"@fi , "Vervollständigt am"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#completedReason
 emf:completedReason rdfs:label "Täytetty syy"@fi , "Abgeschlossener Grund"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#content
 emf:content rdfs:label "Pitoisuus"@fi , "Inhalt"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#ocrContent
 emf:ocrContent rdfs:label "OCR-sisältö"@fi , "OCR-Inhalt"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#ocrStatus
 emf:ocrStatus rdfs:label "OCR-tila"@fi , "OCR-Status"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#countryName
 emf:countryName rdfs:label "Maan nimi"@fi , "Ländername"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#createdOn
 emf:createdOn rdfs:label "Luotu"@fi , "Erstellt am"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#defaultTemplate
 emf:defaultTemplate rdfs:label "Oletusmalli"@fi , "Standardvorlage"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#defaultViewLocation
 emf:defaultViewLocation rdfs:label "Oletusnäkymän sijainti"@fi , "Standardansichtsspeicherort"@de .
  
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#definitionId
 emf:definitionId rdfs:label "Määritelmä id"@fi , "Definitions-ID"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#departmentName
 emf:departmentName rdfs:label "Osaston nimi"@fi , "Abteilungsname"@de .
                  
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#dmsId
 emf:dmsId rdfs:label "DMS Id"@fi , "DMS-Id"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#duration
 emf:duration rdfs:label "Kesto"@fi , "Dauer"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#email
 emf:email rdfs:label "Sähköposti"@fi , "E-Mail"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#estimatedEffort
 emf:estimatedEffort rdfs:label "Arvioitu ponnistus"@fi , "Geschätzter Aufwand"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#externalID
 emf:externalID rdfs:label "ExternalID"@fi ,  "externe ID"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#fileCreatedDate
 emf:fileCreatedDate rdfs:label "Alkuperäinen luontipäivämäärä"@fi , "Ursprüngliches Erstellungsdatum"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#fileModifiedDate
 emf:fileModifiedDate rdfs:label "Alkuperäinen viimeisin muutettu päivämäärä"@fi , "Ursprüngliches Datum der letzten Änderung"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#fileName 
 emf:fileName rdfs:label "Tiedoston nimi"@fi , "Dateiname"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#flag
 emf:flag rdfs:label "Lippu"@fi , "Flagge"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasPosition
 emf:hasPosition rdfs:label "On asema"@fi , "hat Position"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#id
 emf:id rdfs:label "id"@fi , "Ich würde"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#instanceType
 emf:instanceType rdfs:label "Istuntotyyppi"@fi , "Instanztyp"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#instantMessengerId
 emf:instantMessengerId rdfs:label "Instant Messenger-tunnus"@fi , "Instant-Messenger-ID"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isActive
 emf:isActive rdfs:label "On aktiivinen"@fi , "Ist aktiv"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isDeleted
 emf:isDeleted rdfs:label "Poistetaan"@fi , "Ist gelöscht"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#jobTitle
 emf:jobTitle rdfs:label "Työnimike"@fi , "Berufsbezeichnung"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#majorVersion
 emf:majorVersion rdfs:label "MajorVersion"@fi	, "Hauptversion"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mimetype
 emf:mimetype rdfs:label "Mimetype"@fi, "Mime Typ"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#size
 emf:size rdfs:label "Koko"@fi , "Größe"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#minorVersion
 emf:minorVersion rdfs:label "Minor Version"@fi , "Minor Version"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mobilePhoneNumber
 emf:mobilePhoneNumber rdfs:label "Matkapuhelinnumero"@fi , "Handynummer"@de .
																									 				           
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#modifiedOn
 emf:modifiedOn rdfs:label "Muokattu"@fi , "Geändert am"@de .						
																					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mutable
 emf:mutable rdfs:label "Vaihteleva"@fi , "Veränderlich"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#organizationName
 emf:organizationName rdfs:label "Organisaation nimi"@fi , "Name der Organisation"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#phoneNumber
 emf:phoneNumber rdfs:label "Puhelinnumero"@fi , "Telefonnummer"@de .
 
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#plannedEndDate
 emf:plannedEndDate rdfs:label "Suunniteltu päättymispäivä"@fi, "Geplantes Enddatum"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#plannedStartDate
 emf:plannedStartDate rdfs:label "Suunniteltu alkamispäivä"@fi , "Geplantes Startdatum,"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#priority
 emf:priority rdfs:label "Prioriteetti"@fi, "Priorität"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#publishedOn
 emf:publishedOn rdfs:label "Julkaistu"@fi, "Veröffentlicht auf"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#purpose
 emf:purpose rdfs:label "Tarkoitus"@fi , "Zweck"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#revisionOfDefinition
 emf:revisionOfDefinition rdfs:label "Määritelmän tarkistus"@fi  , "Überarbeitung der Definition"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#revisionType
 emf:revisionType rdfs:label "Versiotyyppi"@fi , "Revisionsart"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#searchCriteria
 emf:searchCriteria rdfs:label "Hakukriteerit"@fi , "Suchkriterium"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#searchOrderDirection
 emf:searchOrderDirection rdfs:label "Tilauksen suunta"@fi , "Auftragsrichtung"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#searchOrderBy
 emf:searchOrderBy rdfs:label "Tilannut"@fi, "Sortieren nach"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#searchType
 emf:searchType rdfs:label "Haku tyyppi"@fi , "Suchtyp"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#startDate
 emf:startDate rdfs:label "Aloituspäivämäärä"@fi, "Anfangsdatum"@de .
						 
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#status
 emf:status rdfs:label "Status"@fi , "Status"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#stopReason
 emf:stopReason rdfs:label "Pysäytä syy"@fi , "Stoppt den Grund"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#templateRule
 emf:templateRule rdfs:label "Mallipohja"@fi , "Vorlagenregel"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#templateRuleDescription
 emf:templateRuleDescription rdfs:label "Mallin säännön kuvaus"@fi , "Vorlagenregelbeschreibung"@de .
      
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#thumbnailImage
 emf:thumbnailImage rdfs:label "Pikkukuva"@fi , "Vorschaubild"@de .
                 
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#timeSpent
 emf:timeSpent rdfs:label "Käytetty aika"@fi , "Zeitaufwand"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#transitionMatrix
 emf:transitionMatrix rdfs:label "Siirtymämatriisi"@fi , "Übergangsmatrix"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#type
 emf:type rdfs:label "Tyyppi"@fi , "Art"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#revision
 emf:revision rdfs:label "Määritelmän tarkistus"@fi	, "Definitionsrevision"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#uri
 emf:uri rdfs:label "URI"@fi , "URI"@de .
										
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#vatNumber
 emf:vatNumber rdfs:label "ALV-numero"@fi, "Umsatzsteuer-Identifikationsnummer"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#version
 emf:version rdf:type owl:DatatypeProperty , emf:DefinitionDataProperty , emf:DefinitionProperty ;
      rdfs:label "Versio"@fi , "Ausführung"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#queriesContentId
 emf:queriesContentId rdfs:label "Kyselyt sisällön tunnusta"@fi, "Fragt die Content-ID ab"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#queriesResultContentId        
 emf:queriesResultContentId rdfs:label "Kyselyjen tulosten sisällön tunnus"@fi , "Fragt die Inhalts-ID des Ergebnisses ab"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#viewContent
 emf:viewContent rdfs:label "Näytä sisältö"@fi , "Inhalt anzeigen"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#viewWidgetsContent
 emf:viewWidgetsContent rdfs:label "Näytä widgetin sisältö"@fi , "Widget-Inhalt anzeigen"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#viewDefinition
 emf:viewDefinition rdfs:label "Näytä määritelmä"@fi , "Definition anzeigen"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#workDescription
 emf:workDescription rdfs:label "Työnkuvaus"@fi , "Arbeitsbeschreibung"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#widthOfSubject
 emf:widthOfSubject rdfs:label "Aiheen leveys"@fi , "Breite des Betreffs"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#heightOfSubject
 emf:heightOfSubject rdfs:label "Aiheen korkeus"@fi , "Höhe des Betreffs"@de .
	
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#dimensionUnit
 emf:dimensionUnit rdfs:label "Kiinteistöyksikkö"@fi , "Immobilieneinheit"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#outcome
 emf:outcome rdfs:label "Tulokset"@fi , "Ergebnis"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#taskNotes
 emf:taskNotes rdfs:label "Tehtävähuomautukset"@fi , "Aufgabennotizen"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#integrated
 emf:integrated rdfs:label "Integroitu"@fi , "Integriert"@de .
									 								     
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#issueType
 emf:issueType rdfs:label "Asia tyyppi"@fi , "Fehlertyp"@de .
						    
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#uniqueId
 emf:uniqueId rdfs:label "Unique ID"@de .
											 
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Activity
 emf:Activity rdfs:label "Aktiviteetti"@fi , "Aktivität"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Audio
 emf:Audio rdfs:label "Audio"@fi , "Audio"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#BusinessProcess
 emf:BusinessProcess rdfs:label "Työnkulku"@fi , "Arbeitsablauf"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#BusinessProcessTask
 emf:BusinessProcessTask rdfs:label "Liiketoimintaprosessi"@fi , "Geschäftsprozess-Aufgabe"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Case
 emf:Case rdfs:label "Tapaus"@fi , "Fall"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#ClassDescription
 emf:ClassDescription rdfs:label "Luokka Kuvaus"@fi , "Klassenbeschreibung"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Company
 emf:Company rdfs:label "Yhtiö"@fi , "Unternehmen"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Customer
 emf:Customer rdfs:label "Asiakas"@fi , "Kunde"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DefinitionProperty
 emf:DefinitionProperty rdfs:label "Määritelmäominaisuus"@fi , "Definitionseigenschaft"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DefinitionDataProperty
 emf:DefinitionDataProperty rdfs:label "Määritelmätietojen ominaisuus"@fi , "Definitionsdateneigenschaft"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DefinitionObjectProperty
 emf:DefinitionObjectProperty rdfs:label "Määritelmäominaisuus"@fi , "Definitionseigenschaft"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Department
 emf:Department rdfs:label "Osasto"@fi , "Abteilung"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Document
 emf:Document rdfs:label "Asiakirja"@fi , "Dokument"@de .
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DomainObject
 emf:DomainObject rdfs:label "Verkkotunnuksen kohde"@fi , "Domänenobjekt"@de .
													
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DomainUser
 emf:DomainUser rdfs:label "Verkkotunnuksen käyttäjä"@fi , "Domänenbenutzer"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DataImportSource
 emf:DataImportSource rdfs:label "Tietolähteen lähde"@fi , "Datenimportquelle"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DataImportReport
 emf:DataImportReport rdfs:label "Tietojen tuontiraportti"@fi , "Datenimportbericht"@de .   
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Group
 emf:Group rdfs:label "Ryhmä"@fi , "Gruppe"@de .
        
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Help
 emf:Help rdfs:label "Auta"@fi , "Hilfe"@de .
	
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#helpTarget
 emf:helpTarget rdfs:label "Auta kohde"@fi , "Zielhilfe"@de . 
								
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Image
 emf:Image rdfs:label "Kuva"@fi , "Bild"@de .
									
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Media
 emf:Media rdfs:label "Media Object"@fi , "Medienobjekt"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Project
 emf:Project rdfs:label "Projekti"@fi , "Projekt"@de .

 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Relation
 emf:Relation rdfs:label "Suhde"@fi, "Beziehung"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#SavedSearch
 emf:SavedSearch rdfs:label "Tallennettu haku"@fi , "Gespeicherte Suche"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Task
 emf:Task rdfs:label "Tehtävä"@fi , "Aufgabe"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#User
 emf:User rdfs:label "Käyttäjä"@fi	, "Benutzer"@de .
	
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Vendor
 emf:Vendor rdfs:label "Myyjä"@fi , "Verkäufer"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Video
 emf:Video rdfs:label "Video"@fi , "Video"@de .
					
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Template
 emf:Template rdfs:label "Sapluuna"@fi , "Vorlage"@de .
							
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Definition
 emf:Definition rdfs:label "Määritelmä"@fi , "Definition"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Email
 emf:Email rdfs:label "Sähköposti"@fi , "Email"@de .
						
 ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Issue
 emf:Issue rdfs:label "Asia"@fi 	, "Problem"@de .
					
 ###  http://www.w3.org/ns/oa#Annotation
 oa:Annotation rdfs:label "Huomautus"@fi , "Anmerkung"@de .
						
 ###  http://www.w3.org/2004/02/skos/core#Concept
 skos:Concept rdfs:label "Konsepti"@fi , "Konzept"@de .
 skos:Collection rdfs:label "Kokoelma"@fi , "Sammlung"@de .

 ###  http://www.w3.org/2004/02/skos/core#ConceptScheme
 skos:ConceptScheme rdfs:label "Käsitejärjestelmä"@fi , "Konzeptschema"@de .		   
    }
}