PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX oa: <http://www.w3.org/ns/oa#>
insert data {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#auditEvent
        emf:auditEvent rdfs:label "Одиторско събитие"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#definitionId
        emf:definitionId rdfs:label "Идентификатор на дефиниция"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isPartOfObjectLibrary
        emf:isPartOfObjectLibrary rdfs:label "Е част от библиотека"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isSearchable
        emf:isSearchable rdfs:label "Може да се търси"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#acceptDataTypePattern
        emf:acceptDataTypePattern rdfs:label "Позволени типове файлове"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isCreateable
        emf:isCreateable rdfs:label "Може да се създава"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isUploadable
        emf:isUploadable rdfs:label "Може да се качва"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isSystemProperty
        emf:isSystemProperty rdfs:label "Е системно свойство"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isVersionable
        emf:isVersionable rdfs:label "Може да има версии"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isMailboxSupportable
        emf:isMailboxSupportable rdfs:label "Поддържа пощенска кутия"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#partOfOntology
        emf:partOfOntology rdfs:label "Част от онтология"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#associatedWith
        emf:associatedWith rdfs:label "Свързан с"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#commentsOn
        emf:commentsOn rdfs:label "Коментира по"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#destination
        emf:destination rdfs:label "Посока"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasAgent
        emf:hasAgent rdfs:label "Има агент"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasAttachment
        emf:hasAttachment rdfs:label "Hat Anhang"@de .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasClient
        emf:hasClient rdfs:label "Има клиент"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasChild
        emf:hasChild rdfs:label "Има подобект"@bg .       
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasModel
        emf:hasModel rdfs:label "Има модел"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasRelation
        emf:hasRelation rdfs:label "Има връзка"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasSubsidiary
        emf:hasSubsidiary rdfs:label "Има филиал"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasTemplate
        emf:hasTemplate rdfs:label "Hat Vorlage"@de , "Има шаблон"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasHead
        emf:hasHead rdfs:label "Има ръководител"@bg .  
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasPoolAssignee
        emf:hasPoolAssignee rdfs:label "Има изпълнител от група"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasProvider      
        emf:hasProvider rdfs:label "Има доставчик"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasTag
        emf:hasTag rdfs:label "Има етикет"@bg .     
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasVendor
        emf:hasVendor rdfs:label "Има търговец"@bg .       
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasWatcher    
        emf:hasWatcher rdfs:label "Има наблюдаващ"@bg .           
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#inverseRelation
        emf:inverseRelation rdfs:label "Inverse relation"@en , "Обратна връзка"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isAgentOf
        emf:isAgentOf rdfs:label "Е извършвано от"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isAssigneeOf       
        emf:isAssigneeOf rdfs:label "Е изпълнител на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isDeliveredTo
        emf:isDeliveredTo rdfs:label "Е доставен на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isIssuerOf
        emf:isIssuerOf rdfs:label "Е издател на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isMemberOfCollection
        emf:isMemberOfCollection rdfs:label "Е част от колекция"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isPoolAssigneeTo
        emf:isPoolAssigneeTo rdfs:label "Е добавен към изпълнителите на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isRelatedTo
        emf:isRelatedTo rdfs:label "Отнася се към"@bg .       
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isVendorOf
        emf:isVendorOf rdfs:label "Е търговец на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isWatcherOf
        emf:isWatcherOf rdfs:label "Наблюдава се от"@bg . 
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#loggedBy
        emf:loggedBy rdfs:label "Регистрирано от"@bg .        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#processedBy
        emf:processedBy rdfs:label "Обработвано от"@bg . 
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#publishedBy
        emf:publishedBy rdfs:label "Публикувано от"@bg .                          
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#relationType
        emf:relationType rdfs:label "Тип връзка"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#source
        emf:source rdfs:label "Source"@en , "Начало на връзката"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isContactPersonOf
        emf:isContactPersonOf  rdfs:label "Е лице за контакт"@bg .        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mailboxAddress
        emf:mailboxAddress rdfs:label "Адрес на електроннa поща"@bg .        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasAuthor
        emf:hasAuthor rdfs:label "Има автор"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasEmployee
        emf:hasEmployee rdfs:label "Има служител"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasRecipient
        emf:hasRecipient rdfs:label "Има получател"@bg .       
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isReporterOf
        emf:isReporterOf rdfs:label "Докладва за"@bg .      
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#accumulatedActualEffort
        emf:accumulatedActualEffort rdfs:label "Натрупано действително усилие"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#accumulatedEstimatedEffort
        emf:accumulatedEstimatedEffort rdfs:label "Натрупано прогнозирано усилие"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#activityId
        emf:activityId rdfs:label "Идентификатор на дейност"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#actualEffort
        emf:actualEffort rdfs:label "Действително усилие"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#actualStartDate
        emf:actualStartDate  rdfs:label "Действителна начална дата"@bg .        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#address
        emf:address rdfs:label "Адрес"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#addressCountry
        emf:addressCountry rdfs:label "Име на държава"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#altTitle
        emf:altTitle rdfs:label "Алтернативно заглавие"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#author
        emf:author rdfs:label "Автор"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#avatar
        emf:avatar rdfs:label "Персонално изображение на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#businessSector
        emf:businessSector rdfs:label "Бизнес сектор"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#businessType
        emf:businessType rdfs:label "Бизнес тип"@bg .        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#changeReason
        emf:changeReason rdfs:label "Change reason"@en , "Причина за промяна"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#commentsOnSection
        emf:commentsOnSection rdfs:label "Коментари по секция"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#completedOn
        emf:completedOn rdfs:label "Приключено на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#completedReason
        emf:completedReason rdfs:label "Причина за приключване"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#content
        emf:content rdfs:label "Съдържание"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#ocrContent
        emf:ocrContent  rdfs:label "OCR-съдържание"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#ocrStatus
        emf:ocrStatus  rdfs:label "OCR-състояние"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#countryName
        emf:countryName rdfs:label "Държава"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#createdOn
        emf:createdOn rdfs:label "Създаден на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#defaultTemplate
        emf:defaultTemplate rdfs:label "Шаблон по подразбиране"@bg .        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#defaultViewLocation
        emf:defaultViewLocation rdfs:label "Локация по подразбиране"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#definitionId
        emf:definitionId rdfs:label "Идентификатор на дефиниция"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#departmentName
        emf:departmentName rdfs:label "Отдел"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#dmsId
        emf:dmsId rdfs:label "DMS идентификатор"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#duration
        emf:duration rdfs:label "Продължителност"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#email
        emf:email rdfs:label "Електронна поща"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#estimatedEffort
        emf:estimatedEffort rdfs:label "Прогнозирано усилие"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#externalID
        emf:externalID rdfs:label "Външен идентификатор"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#fileCreatedDate
        emf:fileCreatedDate rdfs:label "Дата на първоначално създаване"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#fileModifiedDate
        emf:fileModifiedDate rdfs:label "Дата на последна промяна"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#fileName
        emf:fileName rdfs:label "Име на файл"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#flag
        emf:flag rdfs:label "Флаг"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#hasPosition
        emf:hasPosition rdfs:label "Позиция"@bg .       
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#id
        emf:id rdfs:label "Идентификатор"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#instanceType
        emf:instanceType rdfs:label "Тип инстанция"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#instantMessengerId
        emf:instantMessengerId rdfs:label "Идентификатор на потребителския акаунт в незабавни съобщения"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isActive
        emf:isActive rdfs:label "Е активно"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isDeleted
        emf:isDeleted rdfs:label "Е изтрито"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#jobTitle
        emf:jobTitle rdfs:label "Длъжност"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#majorVersion
        emf:majorVersion rdfs:label "Основна версия"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mimetype
        emf:mimetype rdfs:label "Тип разширение"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#minorVersion
        emf:minorVersion rdfs:label "Подверсия"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mobilePhoneNumber
        emf:mobilePhoneNumber rdfs:label "Мобилен номер"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#modifiedOn
        emf:modifiedOn rdfs:label "Променено на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mutable
        emf:mutable  rdfs:label "Редактируемо"@bg .        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#organizationName		
        emf:organizationName rdfs:label "Организация"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#phoneNumber
        emf:phoneNumber rdfs:label "Телефонен номер"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#plannedEndDate
        emf:plannedEndDate rdfs:label "Планирана крайна дата"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#plannedStartDate
        emf:plannedStartDate rdfs:label "Планирана начална дата"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#priority
        emf:priority rdfs:label "Приоритет"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#publishedOn
        emf:publishedOn rdfs:label "Публикувано на"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#purpose
        emf:purpose rdfs:label "Цел"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#revisionOfDefinition
        emf:revisionOfDefinition rdfs:label "Ревизия на дефиницията"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#revisionType
        emf:revisionType rdfs:label "Тип на ревизия"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#searchCriteria
        emf:searchCriteria rdfs:label "Критерии за търсене"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#searchOrderDirection
        emf:searchOrderDirection rdfs:label "Ред на подреждане"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#searchOrderBy
        emf:searchOrderBy rdfs:label "Подредени по"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#searchType
        emf:searchType rdfs:label "Тип на търсене"@bg .       
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#startDate
        emf:startDate rdfs:label "Начална дата"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#status
        emf:status rdfs:label "Състояние"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#stopReason
        emf:stopReason  rdfs:label "Причина за прекратяване"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#templateRule
        emf:templateRule rdfs:label "Правило за шаблона"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#templateRuleDescription
        emf:templateRuleDescription rdfs:label "Описание на правило за шаблон"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#thumbnailImage
        emf:thumbnailImage rdfs:label "Thumbnail image"@en , "Умалено изображение"@bg .        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#timeSpent
        emf:timeSpent rdfs:label "Изразходвано време"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#transitionMatrix
        emf:transitionMatrix rdfs:label "Матрица на преходите"@bg .       
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#type
        emf:type rdfs:label "Тип"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#revision
        emf:revision rdfs:label "Ревизия на дефиниция"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#uri
        emf:uri rdfs:label "Унифициран идентификатор на ресурс"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#vatNumber
        emf:vatNumber rdfs:label "ДДС номер"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#version
        emf:version rdfs:label "Версия"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#queriesContentId
        emf:queriesContentId rdfs:label "Идентификатор на съдържанието на заявката за търсене"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#queriesResultContentId        
        emf:queriesResultContentId rdfs:label "Идентификатор на резултата от заявката за търсене"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#viewContent
        emf:viewContent rdfs:label "Преглед на съдържание"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#viewWidgetsConten
        emf:viewWidgetsContent  rdfs:label "Преглед на съдържанието на уиджети"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#viewDefinition
        emf:viewDefinition rdfs:label "Преглед на дефиниция"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#workDescription
        emf:workDescription rdfs:label "Описание на работата"@bg .       
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#issueType
        emf:issueType rdfs:label "Вид проблем"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#defaultView
        emf:defaultView rdfs:label "Изглед по подразбиране"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#contentId
        emf:contentId rdfs:label "Идентификатор на съдържание"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mobileNumber
        emf:mobileNumber rdfs:label "Мобилен номер"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#isPrimaryTemplate
        emf:isPrimaryTemplate rdfs:label "Е главен шаблон"@bg .               
        ### skos:altLabel
        skos:altLabel rdfs:label "Алтернативен етикет"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Activity
        emf:Activity rdfs:label "Дейност"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#ClassDescription
        emf:ClassDescription rdfs:label "Описание на семантичен клас"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DefinitionProperty
        emf:DefinitionProperty rdfs:label "Член променлива на дефиниция"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DefinitionDataProperty
        emf:DefinitionDataProperty rdfs:label "Данни на ресурс"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#DefinitionObjectProperty		
        emf:DefinitionObjectProperty rdfs:label "Връзка на обект"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Group
        emf:Group rdfs:label "Група"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Relation
        emf:Relation rdfs:label "Връзка"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#User
        emf:User rdfs:label "Потребител"@bg .
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Vendor       
        emf:Vendor rdfs:label "Търговец"@bg .      
        ###  http://www.w3.org/ns/oa#Annotation
        oa:Annotation rdfs:label "Анотация"@bg .
        ###  http://www.w3.org/2004/02/skos/core#Concept
        skos:Concept rdfs:label "Concept"@en .
        ###  http://www.w3.org/2004/02/skos/core#Collection   
        skos:Collection rdfs:label "Collection"@en .
        ###  http://www.w3.org/2004/02/skos/core#ConceptScheme
        skos:ConceptScheme rdfs:label "Concept scheme"@en .
    }
}