PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>

insert data {
graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#BusinessProcess
emf:BusinessProcess emf:isUploadable "false"^^xsd:boolean .
                    
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#BusinessProcessTask
emf:BusinessProcessTask   emf:isUploadable "false"^^xsd:boolean ;
					 emf:isCreateable "false"^^xsd:boolean ;            
                     emf:isPartOfObjectLibrary "false"^^xsd:boolean ; 
  		  			 sec:allowInheritParentPermissions "false"^^xsd:boolean ;
          			 sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
          			 
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Case
emf:Case  emf:isUploadable "false"^^xsd:boolean .
          
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Company
emf:Company emf:isUploadable "false"^^xsd:boolean ;
			sec:allowInheritParentPermissions "true"^^xsd:boolean ;
            sec:allowInheritLibraryPermissions "false"^^xsd:boolean ;
            emf:classCategory "objectinstance" .
            
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Customer
emf:Customer emf:isUploadable "false"^^xsd:boolean ;     
			 sec:allowInheritParentPermissions "true"^^xsd:boolean ;
             sec:allowInheritLibraryPermissions "false"^^xsd:boolean ;
             emf:classCategory "objectinstance" ;
             emf:isPartOfObjectLibrary "false"^^xsd:boolean .
             
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Department
emf:Department emf:isUploadable "false"^^xsd:boolean ;
               emf:isPartOfObjectLibrary "false"^^xsd:boolean ;
			   sec:allowInheritParentPermissions "true"^^xsd:boolean ;
               sec:allowInheritLibraryPermissions "false"^^xsd:boolean ;
               emf:classCategory "objectinstance" .
               
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#File
emf:File emf:isCreateable "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Folder
emf:Folder emf:isUploadable "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Group
emf:Group emf:isUploadable "false"^^xsd:boolean ;
		  emf:isPartOfObjectLibrary "false"^^xsd:boolean ;
		  sec:allowInheritParentPermissions "true"^^xsd:boolean ;
		  dc:creator "Ginka Angelova"@en ;
          sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
          
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Help
emf:Help sec:allowInheritParentPermissions "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Image
emf:Image emf:isCreateable "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Media
emf:Media emf:isCreateable "false"^^xsd:boolean ;
          emf:isUploadable "true"^^xsd:boolean ;
          emf:isPartOfObjectLibrary "true"^^xsd:boolean ;
          sec:allowInheritParentPermissions "true"^^xsd:boolean ;
          sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
          
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Meeting
emf:Meeting emf:isUploadable "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Product
emf:Product emf:isUploadable "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#SavedSearch
emf:SavedSearch emf:isCreateable "false"^^xsd:boolean ;
                emf:isUploadable "false"^^xsd:boolean ;
                sec:allowInheritParentPermissions "false"^^xsd:boolean ;
            	sec:allowInheritLibraryPermissions "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Service
emf:Service emf:isUploadable "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Space
emf:Space emf:isUploadable "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Task
emf:Task  emf:isUploadable "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#User
emf:User emf:isUploadable "false"^^xsd:boolean ;
		 emf:isPartOfObjectLibrary "false"^^xsd:boolean ;
         sec:allowInheritParentPermissions "false"^^xsd:boolean ;
         sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
         
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Vendor
emf:Vendor emf:isUploadable "false"^^xsd:boolean ;
           emf:isPartOfObjectLibrary "false"^^xsd:boolean ;
           sec:allowInheritParentPermissions "true"^^xsd:boolean ;
           sec:allowInheritLibraryPermissions "false"^^xsd:boolean ;
           emf:classCategory "vendor" .
           
###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Template
emf:Template emf:isUploadable "false"^^xsd:boolean .

###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#Definition
emf:Definition  emf:isCreateable "false"^^xsd:boolean ;
                emf:isUploadable "false"^^xsd:boolean ;
                sec:allowInheritParentPermissions "false"^^xsd:boolean ;
			    sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
    }
}