PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
DELETE {
    emf:Group emf:isCreateable "false"^^xsd:boolean.
}
INSERT {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
        emf:Group emf:isCreateable "true"^^xsd:boolean.
    }
}  where { }
