PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
delete {
    emf:User emf:isCreateable "false"^^xsd:boolean.
}
insert {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
        emf:User emf:isCreateable "true"^^xsd:boolean.
    }
}  where { }
