PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

delete {
    emf:Help emf:isUploadable "false"^^xsd:boolean .
}
insert {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
        emf:Help emf:isUploadable "true"^^xsd:boolean .
    }
}  where { }