PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

insert data {

    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
    
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#instantMessengerId
        emf:instantMessengerId rdf:type owl:DatatypeProperty ;
            rdfs:label "Instant messenger ID"@en ;
            dc:creator "Kiril Penev"@en ;
            skos:definition "ID of the users account in instant messengers"@en .
        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#countryName
        emf:countryName rdf:type owl:DatatypeProperty ;
            rdfs:label "Country Name"@en ;
            skos:definition "Name of the country"@en ;
            dc:creator "Kiril Penev"@en .
        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#mobilePhoneNumber
        emf:mobilePhoneNumber rdf:type owl:DatatypeProperty ;
            rdfs:label "Mobile number"@en ;
            dc:creator "Kiril Penev"@en ;
            skos:definition "Mobile number"@en .
        
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#organizationName
        emf:organizationName rdf:type owl:DatatypeProperty ;
            rdfs:label "Organization name"@en ;
            dc:creator "Kiril Penev"@en ;
            skos:definition "Organization name"@en .
            
        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#jobTitle
		emf:jobTitle rdf:type owl:DatatypeProperty ;
              rdfs:label "Job title"@en ;
              skos:definition "Job title"@en ;
              dc:creator "Kiril Penev"@en .
    }
}