PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
insert data{
graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
				
###  http://www.w3.org/2000/01/rdf-schema#subClassOf
rdfs:subClassOf rdf:type owl:AnnotationProperty ;
                 rdfs:label "Под клас на"@bg ,
                            "Sub class of"@en .

    }
}
