PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:isPartOfObjectLibrary rdf:type emf:DefinitionDataProperty.
        emf:isSearchable rdf:type emf:DefinitionDataProperty.
        emf:isCreateable rdf:type emf:DefinitionDataProperty.
        emf:isUploadable rdf:type emf:DefinitionDataProperty.
        emf:isVersionable rdf:type emf:DefinitionDataProperty.
        emf:isMailboxSupportable rdf:type emf:DefinitionDataProperty.
        emf:acceptDataTypePattern rdf:type emf:DefinitionDataProperty.
    }
}