PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        
        emf:hasAssignee emf:auditEvent "+assign|-unassign|reassign" .

		emf:isAssigneeOf  emf:auditEvent "+addIsAssigneeOf|-removeIsAssigneeOf" .	

		emf:hasThumbnail  emf:auditEvent "+addThumbnail|-removeThumbnail|changeThumbnail" .		

		emf:isThumbnailOf  emf:auditEvent "+addIsThumbnailOf|-removeIsThumbnailOf|changeIsThumbnailOf" .

		emf:owner emf:auditEvent "+addOwner|-removeOwner|changeOwner" .

		emf:ownedBy emf:auditEvent "+addOwnedBy|-removeOwnedBy|changeOwnedBy" .
    }
}