PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        
        emf:widthOfSubject rdf:type owl:DatatypeProperty ;                    
			rdfs:label "Width of Subject"@en ,
						"Ширина на обекта"@bg ;                    
			skos:definition "Width of Subject"@en ;                    
			dc:creator "Daniela Todorova"@en ;	       
			rdfs:range xsd:double .

		emf:heightOfSubject rdf:type owl:DatatypeProperty ;                    
			rdfs:label "Height of Subject"@en ,
						"Височина на обекта"@bg ;                    
			skos:definition "Height of Subject"@en ;                    
			dc:creator "Daniela Todorova"@en ;	         
			rdfs:range xsd:double .					
					
		emf:dimensionUnit rdf:type owl:DatatypeProperty ;                    
			rdfs:label "Property Unit"@en ,
						"Мерна единица"@bg ;                    
			skos:definition "Property Unit"@en ;                    
			dc:creator "Daniela Todorova"@en ;	     
			rdfs:range xsd:string .	
    }
}