PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        
		emf:references  emf:auditEvent "+addReferences|-removeReferences|changeReferences" .		

		emf:dependsOn  emf:auditEvent "+addDependsOn" .

		emf:isRelatedTo  emf:auditEvent "-removeIsRelatedTo" .

		emf:hasAttachment  emf:auditEvent "+addHasAttachment|-removeHasAttachment|changeHasAttachment" .

		emf:isAttachedTo  emf:auditEvent "+addIsAttachedTo|-removeIsAttachedTo|changeIsAttachedTo" .

		emf:blocks  emf:auditEvent "+addBlocks|-removeBlocks|changeBlocks" .

		emf:isBlockedBy  emf:auditEvent "+addIsBlockedBy|-removeIsBlockedBy|changeIsBlockedBy" .

		emf:processes emf:auditEvent "+addProcesses|-removeProcesses|changeProcesses".

		emf:processedBy emf:auditEvent "+addProcessedBy|-removeProcessedBy|changeProcessedBy".

		emf:contactPerson  emf:auditEvent "+addContactPerson|-removeContactPerson|changeContactPerson" .

		emf:hasAgent  emf:auditEvent "+addHasAgent|-removeHasAgent|changeHasAgent" .

		emf:isAgentOf  emf:auditEvent "+addIsAgentOf" .

		emf:isMemberOf  emf:auditEvent "+addIsMemberOf" .

		emf:hasWatcher  emf:auditEvent "+addHasWatcher|-removeHasWatcher|changeHasWatcher" .

		emf:isWatcherOf  emf:auditEvent "+addIsWatcherOf|-removeIsWatcherOf|changeIsWatcherOf" .

		emf:hasPrimaryImage  emf:auditEvent "+addHasPrimaryImage|-removeHasPrimaryImage|changeHasPrimaryImage" .

		emf:isPrimaryImageOf  emf:auditEvent "+addIsPrimaryImage|-removeIsPrimaryImage|changeIsPrimaryImage" .	
    }
}