PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
insert data {
    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        skos:Concept rdfs:label "Концепция"@bg ;
            rdfs:subClassOf ptop:Object ;
            emf:isPartOfObjectLibrary "true"^^xsd:boolean ;
            sec:allowInheritParentPermissions "true"^^xsd:boolean ;
            emf:isCreateable "true"^^xsd:boolean ;
            emf:isSearchable "true"^^xsd:boolean ;
            sec:allowInheritLibraryPermissions "true"^^xsd:boolean ;
            emf:classCategory "concept"@en ;
            emf:definitionId "objectinstance"@en .
        skos:Collection rdfs:label "Колекция"@bg ;
            rdfs:subClassOf ptop:Object ;
            emf:isPartOfObjectLibrary "true"^^xsd:boolean ;
            sec:allowInheritParentPermissions "true"^^xsd:boolean ;
            emf:isCreateable "true"^^xsd:boolean ;
            emf:isSearchable "true"^^xsd:boolean ;
            sec:allowInheritLibraryPermissions "true"^^xsd:boolean ;
            emf:classCategory "concept"@en ;
            emf:definitionId "objectinstance"@en .
        ###  http://www.w3.org/2004/02/skos/core#ConceptScheme
        skos:ConceptScheme rdfs:label "Концепционна схема"@bg ;
            rdfs:subClassOf ptop:Object ;
            emf:isCreateable "true"^^xsd:boolean ;
            sec:allowInheritParentPermissions "true"^^xsd:boolean ;
            emf:isPartOfObjectLibrary "true"^^xsd:boolean ;
            sec:allowInheritLibraryPermissions "true"^^xsd:boolean ;
            emf:isSearchable "true"^^xsd:boolean ;
            emf:definitionId "objectinstance"@en ;
            emf:classCategory "concept"@en .
        skos:broadMatch emf:isSearchable "true"^^xsd:boolean .
        skos:broader emf:isSearchable "true"^^xsd:boolean .
        skos:broaderTransitive emf:isSearchable "true"^^xsd:boolean .
        skos:closeMatch emf:isSearchable "true"^^xsd:boolean .
        skos:exactMatch emf:isSearchable "true"^^xsd:boolean .
        skos:hasTopConcept emf:isSearchable "true"^^xsd:boolean .
        skos:inScheme emf:isSearchable "true"^^xsd:boolean .
        skos:member emf:isSearchable "true"^^xsd:boolean .
        skos:narrowMatch emf:isSearchable "true"^^xsd:boolean .
        skos:narrower emf:isSearchable "true"^^xsd:boolean .
        skos:narrowerTransitive emf:isSearchable "true"^^xsd:boolean .
        skos:related emf:isSearchable "true"^^xsd:boolean .
        skos:relatedMatch emf:isSearchable "true"^^xsd:boolean .
        skos:topConceptOf emf:isSearchable "true"^^xsd:boolean .
    }
}