PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>
insert data {

    graph <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
		emf:DataImportSource rdf:type owl:Class ;
			   emf:classCategory "objectinstance" ;
			   emf:definitionId "objectinstance" .
        
		emf:DataImportReport rdf:type owl:Class ;
			   emf:classCategory "objectinstance" ;
			   emf:definitionId "objectinstance" .
    }
}