PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
	GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework>{
    	emf:duration rdfs:range xsd:long .
   	}
}