PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
INSERT DATA {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:altTitle rdf:type owl:DatatypeProperty , emf:DefinitionDataProperty ;
            rdfs:label "Alternative title"@en ;
            skos:definition "Alternative instance title used for sorting and indexing of instances"@en ;
            dc:creator "Borislav Bonev"@en ;
            rdfs:range xsd:string .
    }
}
