PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT DATA {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {

        ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#templateRule
		emf:templateRule rdf:type owl:DatatypeProperty ;
       		rdfs:label "Template rule"@en ;
           	dc:creator "Vilizar Tsonev"@en ;
           	skos:definition "Defines a rule of the template, used to best match its target type"@en ;
           	emf:isSystemProperty "true"^^xsd:boolean ;
		   	emf:isSearchable "false"^^xsd:boolean ;
		   	rdfs:domain emf:Template ;
           	rdfs:range xsd:string .

         ###  http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#templateRuleDescription
		 emf:templateRuleDescription rdf:type owl:DatatypeProperty ;
       	 	 rdfs:label "Template rule description"@en ;
           	 dc:creator "Vilizar Tsonev"@en ;
           	 skos:definition "Describes a template rule in a human-readable way"@en ;
           	 emf:isSearchable "false"^^xsd:boolean ;
           	 rdfs:domain emf:Template ;
           	 rdfs:range xsd:string .    
    }
}