PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX sec: <http://www.sirma.com/ontologies/2014/11/security#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT DATA {
  GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        
        emf:Document sec:allowInheritParentPermissions "true"^^xsd:boolean ;
            		 sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
        
        emf:Audio sec:allowInheritParentPermissions "true"^^xsd:boolean ;
          		  sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
        
        emf:Image sec:allowInheritParentPermissions "true"^^xsd:boolean ;
          		  sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
        
        emf:Video sec:allowInheritParentPermissions "true"^^xsd:boolean ;
          		  sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
        
        emf:Project sec:allowInheritParentPermissions "true"^^xsd:boolean ;
          			sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
        
        emf:Case sec:allowInheritParentPermissions "true"^^xsd:boolean ;
          		 sec:allowInheritLibraryPermissions "true"^^xsd:boolean .
        
        emf:Task sec:allowInheritParentPermissions "true"^^xsd:boolean ;
          		 sec:allowInheritLibraryPermissions "false"^^xsd:boolean .
        
  }
}