PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
DELETE DATA {
    emf:hasChild rdf:type emf:DefinitionObjectProperty , emf:DefinitionProperty .
}