PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

DELETE {
	emf:Service dcterms:creator "Yaldaz Mehmedova"@en.
	emf:Product dcterms:creator "Yaldaz Mehmedova"@en.
	emf:subType dcterms:creator "Lyubomir Marinov"@en.
	emf:salutation dcterms:creator "Lyubomir Marinov"@en.
	emf:currency dcterms:creator "Lyubomir Marinov"@en.
	emf:companyRole dcterms:creator "Yaldaz Mehmedova"@en.
	emf:addressZip dcterms:creator "Lyubomir Marinov"@en.
	emf:addressState dcterms:creator "Lyubomir Marinov"@en.
	emf:addressCity dcterms:creator "Lyubomir Marinov"@en.
}
INSERT {
 GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
	emf:Service dc:creator "Yaldaz Mehmedova"@en.
	emf:Product dc:creator "Yaldaz Mehmedova"@en.
	emf:subType dc:creator "Lyubomir Marinov"@en.
	emf:salutation dc:creator "Lyubomir Marinov"@en.
	emf:currency dc:creator "Lyubomir Marinov"@en.
	emf:companyRole dc:creator "Yaldaz Mehmedova"@en.
	emf:addressZip dc:creator "Lyubomir Marinov"@en.
	emf:addressState dc:creator "Lyubomir Marinov"@en.
	emf:addressCity dc:creator "Lyubomir Marinov"@en.
}
} WHERE {
}