PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
DELETE {
   ptop:title rdfs:label ?o1.
   ptop:title dcterms:title ?o2.
}
INSERT {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        ptop:title rdfs:label "Наименование"@bg, "Title"@en, "Titel"@de, "Otsikko"@fi, "Titel"@da .
        ptop:title dcterms:title "Наименование"@bg, "Title"@en, "Titel"@de, "Otsikko"@fi, "Titel"@da .
        ptop:title skos:definition "Official title of the item"@en .
        ptop:title dcterms:description "Official title of the item"@en .
    }
} WHERE {
	 ptop:title rdfs:label ?o1.
     optional {
        ptop:title dcterms:title ?o2.
     }
}