PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE {
	emf:Group rdfs:label ?label
}
INSERT {
 GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
	emf:Group rdfs:label "User Group"@en .
	emf:Group rdfs:label "Потребителска Група"@bg .
	emf:Group rdfs:label "Benutzergruppe"@de .
	emf:Group rdfs:label "Käyttäjäryhmä"@fi .
}
} WHERE {
	emf:Group rdfs:label ?label
}