//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.01 at 02:59:00 PM EEST
//

package com.sirma.itt.emf.definition.model.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for renderAsType.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="renderAsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HIDDEN"/>
 *     &lt;enumeration value="VISIBLE"/>
 *     &lt;enumeration value="DISABLED"/>
 *     &lt;enumeration value="ENABLED"/>
 *     &lt;enumeration value="REQUIRED"/>
 *     &lt;enumeration value="READONLY"/>
 *     &lt;enumeration value="DISABLE_SAVE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "renderAsType")
@XmlEnum
public enum RenderAsType {

	/** The hidden. */
	HIDDEN,

	/** The visible. */
	VISIBLE,

	/** The disabled. */
	DISABLED,

	/** The enabled. */
	ENABLED,

	/** The required. */
	REQUIRED,

	/** The readonly. */
	READONLY,

	/** The disable save. */
	DISABLE_SAVE;

	/**
	 * Value.
	 * 
	 * @return the string
	 */
	public String value() {
		return name();
	}

	/**
	 * From value.
	 * 
	 * @param v
	 *            the v
	 * @return the render as type
	 */
	public static RenderAsType fromValue(String v) {
		return valueOf(v);
	}

}
