PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
delete {
       ptop:hasParticipant rdfs:label "Participant in a Happening"@en. 
}
insert{
       ptop:hasParticipant rdfs:label "Has participant"@en.
}where{
    
}