SELECT DISTINCT ?instance ?instanceType ?v7fcbc0bfda8e45fea368d764cdc0555fsort WHERE {
    ?instance emf:instanceType ?instanceType .
    ?instance emf:isDeleted "false"^^xsd:boolean .
    FILTER ( ?instanceType != "sectioninstance" && ?instanceType != "classinstance" && ?instanceType != "commoninstance" && ?instanceType != "topicinstance" && ?instanceType != "commentinstance" && ?instanceType != "annotation" ) 
    {
        {
            ?instance rdf:type <http://www.sirma.com/ontologies/2013/10/culturalHeritageDomain#CulturalObject>.
        }
    } .
    OPTIONAL  {
        ?instance emf:modifiedOn ?v7fcbc0bfda8e45fea368d764cdc0555fsort .
    } 
}