PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

delete {
    emf:classCategory rdf:type emf:DefinitionDataProperty, emf:DefinitionProperty.
} insert {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:classCategory rdf:type owl:AnnotationProperty;
    }
} where { }
