PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
DELETE {
    emf:existingInContext ?o ?p.
    ?s emf:existingInContext ?p .
}
WHERE {
    {
        emf:existingInContext ?o ?p.
    } UNION {
        ?s emf:existingInContext ?p .
    }
}