PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
delete data {
    emf:address	rdfs:domain	ptop:Agent .
    emf:address	rdfs:range	xsd:string .
}