PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
delete data {
    emf:hasAttachment rdfs:label  "hat Anhang"@de .
    emf:hasClient rdfs:label "Клиент"@bg .
    emf:hasChild rdfs:label "Има дете"@bg .
    emf:hasModel rdfs:label "Има Модел"@bg .
    emf:hasRelation rdfs:label "Има Връзка"@bg .
    emf:hasSubsidiary rdfs:label "Филиал"@bg .
    emf:hasHead rdfs:label "Ръководител"@bg .
    emf:hasPoolAssignee rdfs:label "Има потребители в пула"@bg .
    emf:hasProvider rdfs:label "Доставчик"@bg .
    emf:hasTag rdfs:label "Има таг"@bg .  
    emf:hasVendor rdfs:label "Има доставчик"@bg .
    emf:hasWatcher rdfs:label "Има наблюдаващ"@bg .  
    emf:hasTemplate rdfs:label "Има Темплейт"@bg .  
    emf:inverseRelation rdfs:label "inverse relation"@en .
    emf:isAgentOf rdfs:label "Извършва"@bg .
    emf:isAssigneeOf rdfs:label "Изпълнител на"@bg .
    emf:isDeliveredTo rdfs:label "Доставен на"@bg .
    emf:isIssuerOf rdfs:label "Издател на"@bg .
    emf:isPoolAssigneeTo rdfs:label "Е добавен към пул"@bg .   
    emf:isRelatedTo rdfs:label "Се отнася към"@bg .
    emf:isWatcherOf rdfs:label "Наблюдава"@bg .
    emf:processedBy rdfs:label "Обработва се от"@bg .    
    emf:source rdfs:label "source"@en .
    emf:isContactPersonOf  rdfs:label "Лице за контакт"@bg .
    emf:mailboxAddress rdfs:label "Електроннa поща"@bg .
    emf:hasAuthor rdfs:label "Автор"@bg .
    emf:hasEmployee rdfs:label "Служител"@bg .
    emf:hasRecipient rdfs:label "Получател"@bg .    
    emf:isReporterOf rdfs:label "Докладва"@bg .  
    emf:addressCountry rdfs:label "Държава"@bg .   
    emf:changeReason rdfs:label "change reason"@en .
    emf:thumbnailImage rdfs:label "thumbnail image"@en .
    emf:issueType rdfs:label "Вид Проблем"@bg .
    emf:defaultView rdfs:label "По подразбиране"@bg .
    emf:contentId rdfs:label "Съдържание id"@bg .
    emf:mobileNumber rdfs:label "Мобилен телефон"@bg .
    emf:isPrimaryTemplate rdfs:label "Главен шаблон"@bg .
    skos:altLabel rdfs:label "Alt наименование"@bg .
    emf:Vendor rdfs:label "Доставчик"@bg .
}