PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
DELETE {
     emf:DataImportSource emf:classCategory "objectinstance".
	 emf:DataImportReport emf:classCategory "objectinstance".
}
INSERT {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
     emf:DataImportSource emf:classCategory "dataimportsource".
	 emf:DataImportReport emf:classCategory "dataimportreport".
	 ptop:Organization emf:classCategory "organization".
	 ptop:Person emf:classCategory "person".
	 
    }
} WHERE {
}