PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
DELETE {
     ?instance rdfs:subClassOf emf:Library.
}
INSERT {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
       ?instance rdfs:subClassOf ptop:Object.
    }
} WHERE {
    ?instance rdfs:subClassOf emf:Library.
}