PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
DELETE {
    emf:RecordSpace rdfs:label "Record space"@en .
}
INSERT {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:RecordSpace rdfs:label "Record Space"@en .
    }
} WHERE {
    emf:RecordSpace rdfs:label "Record space"@en .
}