PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
delete {
    ?property rdfs:label ?label.
    ?property dcterms:title ?title.
    ?property skos:definition ?definition.
    ?property rdfs:comment ?definition.
    ?property dcterms:description ?description.
}insert{
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
		emf:mimetype rdfs:label "Разширение"@bg, "MIME-type"@da, "Mime Typ"@de, "Mimetype"@en, "Mimetype"@fi .
        emf:mimetype dcterms:title "Разширение"@bg, "MIME-type"@da, "Mime Typ"@de, "Mimetype"@en, "Mimetype"@fi .
        emf:mimetype skos:definition "Mimetype of the file: jpg, png, etc."@en .
        emf:mimetype dcterms:description "Mimetype of the file: jpg, png, etc."@en .
        
        emf:type skos:definition "Classification of the item"@en .
        emf:type dcterms:description "Classification of the item"@en .
        
        emf:createdBy rdfs:label "Създаден от"@bg, "Oprettet af"@da, "System erstellt von"@de, "System created by"@en, "Järjestelmä luonut"@fi .
        emf:createdBy dcterms:title "Създаден от"@bg, "Oprettet af"@da, "System erstellt von"@de, "System created by"@en, "Järjestelmä luonut"@fi .
       
        emf:createdOn rdfs:label "Създаден на"@bg, "Oprettet"@da, "System erstellt am"@de, "System created on"@en, "Järjestelmä luotu"@fi .
        emf:createdOn dcterms:title "Създаден на"@bg, "Oprettet"@da, "System erstellt am"@de, "System created on"@en, "Järjestelmä luotu"@fi .
        
        emf:modifiedBy rdfs:label "Актуализиран от"@bg, "Opdateret af"@da, "Geändert von"@de, "Modified by"@en, "Muokannut"@fi .
        emf:modifiedBy dcterms:title "Актуализиран от"@bg, "Opdateret af"@da, "Geändert von"@de, "Modified by"@en, "Muokannut"@fi .
        
        emf:modifiedOn rdfs:label "Актуализиран на"@bg, "Opdateret"@da, "Geändert am"@de, "Modified on"@en, "Muokattu"@fi .
        emf:modifiedOn dcterms:title "Актуализиран на"@bg, "Opdateret"@da, "Geändert am"@de, "Modified on"@en, "Muokattu"@fi .
        
        ptop:partOf rdfs:label "Част от"@bg, "Del af"@da, "Teil von"@de, "Part of"@en, "Osa"@fi .
        ptop:partOf dcterms:title "Част от"@bg, "Del af"@da, "Teil von"@de, "Part of"@en, "Osa"@fi .
        ptop:partOf skos:definition "The object to which the current object is part of"@en .
        ptop:partOf dcterms:description "The object to which the current object is part of"@en .
        
        emf:hasChild rdfs:label "Има деца"@bg, "Har underordnet kontekst"@da, "Hat ein kind"@de, "Has child"@en, "Onko lapsi"@fi .
        emf:hasChild dcterms:title "Има деца"@bg, "Har underordnet kontekst"@da, "Hat ein kind"@de, "Has child"@en, "Onko lapsi"@fi .
        emf:hasChild skos:definition "Specifies which are the children of the object"@en .
        emf:hasChild dcterms:description "Specifies which are the children of the object"@en .
        
        emf:hasThumbnail rdfs:label "Има умалено изображение"@bg, "Har thumbnail"@da, "Hat miniaturansicht"@de, "Has thumbnail"@en, "Pienoiskuva"@fi .
        emf:hasThumbnail dcterms:title "Има умалено изображение"@bg, "Har thumbnail"@da, "Hat miniaturansicht"@de, "Has thumbnail"@en, "Pienoiskuva"@fi .
        
        emf:hasWatcher rdfs:label "Наблюдатели"@bg, "Observatører"@da, "Beobachter"@de, "Watchers"@en, "Watchers"@fi .
        emf:hasWatcher dcterms:title "Наблюдатели"@bg, "Observatører"@da, "Beobachter"@de, "Watchers"@en, "Watchers"@fi .
        
        emf:hasTemplate rdfs:label "Има шаблон"@bg, "Har skabelon"@da, "Hat eine Vorlage"@de, "Has template"@en, "Malli"@fi .
        emf:hasTemplate dcterms:title "Има шаблон"@bg, "Har skabelon"@da, "Hat eine Vorlage"@de, "Has template"@en, "Malli"@fi .
        
        emf:templateVersion rdfs:label "Версия на приложения шаблон"@bg, "Version af den anvendte skabelon"@da, "Version der verwendeten vorlage"@de, "Version of the applied template"@en, "Käytetyn mallin versio"@fi .
        emf:templateVersion dcterms:title "Версия на приложения шаблон"@bg, "Version af den anvendte skabelon"@da, "Version der verwendeten vorlage"@de, "Version of the applied template"@en, "Käytetyn mallin versio"@fi .
        
        emf:version rdfs:label "Версия"@bg, "Version"@da, "Version"@de, "Version"@en, "Versio"@fi .
        emf:version dcterms:title "Версия"@bg, "Version"@da, "Version"@de, "Version"@en, "Versio"@fi .
        emf:version skos:definition "The version of the item"@en .
        emf:version dcterms:description "The version of the item"@en . 
    }
} where {
    {
        ## titles only
        ?property rdfs:label ?label.
        optional {
            ?property dcterms:title ?title.
        }
        filter(?property in (emf:createdBy, emf:createdOn, emf:modifiedBy, emf:modifiedOn, emf:hasThumbnail, emf:hasWatcher, emf:hasTemplate, emf:templateVersion))
    } UNION {
        ## descriptions only
        ?property rdfs:comment|skos:definition ?definition.
        optional {
            ?property dcterms:description ?description.
        }
        filter(?property in (emf:type))
    } UNION {
        ## both
        ?property rdfs:label ?label.
        ?property skos:definition|rdfs:comment ?definition.
        optional {
            ?property dcterms:description ?description.
        }
        optional {
            ?property dcterms:title ?title.
        }
        filter(?property in (emf:mimetype, ptop:partOf, emf:hasChild, emf:version))
    }
}