PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
delete {
    ?property rdfs:label ?label.
    ?property dcterms:title ?title.
    ?property skos:definition ?definition.
    ?property rdfs:comment ?definition.
    ?property dcterms:description ?description.
}insert{
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
		emf:mailboxAddress rdfs:label "Системен имейл"@bg, "Systemgenereret e-mail"@da, "System e-mail"@de, "System e-mail"@en, "System e-mail"@fi .
        emf:mailboxAddress dcterms:title "Системен имейл"@bg, "Systemgenereret e-mail"@da, "System e-mail"@de, "System e-mail"@en, "System e-mail"@fi .
        emf:mailboxAddress skos:definition "System e-mail of the item"@en .
        emf:mailboxAddress dcterms:description "System e-mail of the item"@en .
      
      	ptop:firstName rdfs:label "Име"@bg, "First name"@en, "Vorname"@de, "Etunimi"@fi, "Fornavn"@da .
        ptop:firstName dcterms:title "Име"@bg, "First name"@en, "Vorname"@de, "Etunimi"@fi, "Fornavn"@da .
        ptop:firstName skos:definition "The first name of the user"@en .
        ptop:firstName dcterms:description "The first name of the user"@en .
        
        ptop:lastName rdfs:label "Фамилия"@bg, "Last name"@en, "Familienname, Nachname"@de, "Sukunimi"@fi, "Efternavn"@da .
        ptop:lastName dcterms:title "Фамилия"@bg, "Last name"@en, "Familienname, Nachname"@de, "Sukunimi"@fi, "Efternavn"@da .
        ptop:lastName skos:definition "The last name of the user"@en .
        ptop:lastName dcterms:description "The last name of the user"@en .
        
        emf:countryName rdfs:label "Държава"@bg, "Land"@da, "Land"@de, "Country"@en, "Maa"@fi .
        emf:countryName dcterms:title "Държава"@bg, "Land"@da, "Land"@de, "Country"@en, "Maa"@fi .
        
        emf:phoneNumber rdfs:label "Телефон"@bg, "Telefon"@da, "Hausnummer"@de, "Telephone"@en, "Puhelin"@fi .
        emf:phoneNumber dcterms:title "Телефон"@bg, "Telefon"@da, "Hausnummer"@de, "Telephone"@en, "Puhelin"@fi .
        
        emf:mobileNumber rdfs:label "Мобилен телефон"@bg, "Mobil"@da, "Mobile nummer"@de, "Mobile"@fi, "Mobile"@en .
        emf:mobileNumber dcterms:title "Мобилен телефон"@bg, "Mobil"@da, "Mobile nummer"@de, "Mobile"@fi, "Mobile"@en .
        
        emf:organizationName rdfs:label "Търговско предприятие"@bg, "Organisation navn"@da, "Name der Organisation"@de, "Organization"@en, "Organisaatio"@fi .
        emf:organizationName dcterms:title "Търговско предприятие"@bg, "Organisation navn"@da, "Name der Organisation"@de, "Organization"@en, "Organisaatio"@fi .
        emf:organizationName skos:definition "Name of the organization"@en .
        emf:organizationName dcterms:description "Name of the organization"@en .
        
        dcterms:language rdfs:label "Език"@bg, "Language"@en, "Sprache"@de, "Kieli"@fi, "Sprog"@da .
        dcterms:language dcterms:title "Език"@bg, "Language"@en, "Sprache"@de, "Kieli"@fi, "Sprog"@da .
        dcterms:language skos:definition "The language of the user"@en .
        dcterms:language dcterms:description "The language of the user"@en .
        
        emf:isAssigneeOf rdfs:label "Изпълнител на"@bg, "Er ansvarlig for"@da, "Ist bevollmächtigter von"@de, "Is assignee of"@en, "Oleskelulupa on"@fi .
        emf:isAssigneeOf dcterms:title "Изпълнител на"@bg, "Er ansvarlig for"@da, "Ist bevollmächtigter von"@de, "Is assignee of"@en, "Oleskelulupa on"@fi .
        emf:isAssigneeOf skos:definition "The item the user is assinee to"@en .
        emf:isAssigneeOf dcterms:description "The item the user is assinee to"@en .
        
        emf:isPoolAssigneeTo rdfs:label "Е добавен към пул"@bg, "Er knyttet via pulje til"@da, "Ist pool-beauftragter zu"@de, "Is pool assignee to"@en, "On pool assignee to"@fi .
        emf:isPoolAssigneeTo dcterms:title "Е добавен към пул"@bg, "Er knyttet via pulje til"@da, "Ist pool-beauftragter zu"@de, "Is pool assignee to"@en, "On pool assignee to"@fi .
        emf:isPoolAssigneeTo skos:definition "The items that the users is assignee to"@en .
        emf:isPoolAssigneeTo dcterms:description "The items that the users is assignee to"@en .
        
        emf:isReporterOf rdfs:label "Докладва"@bg, "Er rapportør af"@da, "Ist reporter von"@de, "Is reporter of"@en, "Onko toimittaja"@fi .
        emf:isReporterOf dcterms:title "Докладва"@bg, "Er rapportør af"@da, "Ist reporter von"@de, "Is reporter of"@en, "Onko toimittaja"@fi .
        emf:isReporterOf skos:definition "Reporter of the item"@en .
        emf:isReporterOf dcterms:description "Reporter of the item"@en .
        
        ptop:hasMember rdfs:label "Има член"@bg, "Has member"@en, "Hat mitglied"@de, "Onko jäsen"@fi, "Har medlem"@da .
        ptop:hasMember dcterms:title "Има член"@bg, "Has member"@en, "Hat mitglied"@de, "Onko jäsen"@fi, "Har medlem"@da .
        ptop:hasMember skos:definition "Users that are members of the group"@en .
        ptop:hasMember dcterms:description "Users that are members of the group"@en .
        
        emf:uniqueId rdfs:label "Уникално ИД на колекция"@bg, "UUnik samlings-id"@da, "Eindeutige sammlungs-ID"@de, "Unique collection ID"@en, "UnUnique collection ID"@fi .
        emf:uniqueId dcterms:title "Уникално ИД на колекция"@bg, "UUnik samlings-id"@da, "Eindeutige sammlungs-ID"@de, "Unique collection ID"@en, "UnUnique collection ID"@fi .
        
        skos:member rdfs:label "Членове"@bg, "Members"@en, "Mitglieder"@de, "Jäsenet"@fi, "Medlemmer"@da .
        skos:member dcterms:title "Членове"@bg, "Members"@en, "Mitglieder"@de, "Jäsenet"@fi, "Medlemmer"@da .
        skos:member skos:definition "Relates a collection to one of its members"@en .
        skos:member dcterms:description "Relates a collection to one of its members"@en .
        
        emf:isMemberOfCollection rdfs:label "Член на колекция"@bg, "Er del af samling"@da, "Ist mitglied der Sammlung"@de, "Is member of Collection"@en, "Onko jäsen Kokoelmasta"@fi .
        emf:isMemberOfCollection dcterms:title "Член на колекция"@bg, "Er del af samling"@da, "Ist mitglied der Sammlung"@de, "Is member of Collection"@en, "Onko jäsen Kokoelmasta"@fi .
        
        emf:isTopConcept rdfs:label "Главна концепция"@bg, "Er topkoncept"@da, "Er øvre koncept"@en, "Is top concept"@fi, "Ist top-konzept"@de .
        emf:isTopConcept dcterms:title "Главна концепция"@bg, "Er topkoncept"@da, "Er øvre koncept"@en, "Is top concept"@fi, "Ist top-konzept"@de .
        
        emf:associatedWith rdfs:label "Свързва се с обект"@bg, "Associeret med"@da, "Verknüpfen mit objekt"@de, "Associated with object"@en, "Associated with object"@fi .
        emf:associatedWith dcterms:title "Свързва се с обект"@bg, "Associeret med"@da, "Verknüpfen mit objekt"@de, "Associated with object"@en, "Associated with object"@fi .
        
        emf:processedBy rdfs:label "Обработен от"@bg, "Behandlet af"@da, "Verarbeitet von"@de, "Processed by"@en, "Jalostanut"@fi .
        emf:processedBy dcterms:title "Обработен от"@bg, "Behandlet af"@da, "Verarbeitet von"@de, "Processed by"@en, "Jalostanut"@fi .
        emf:processedBy skos:definition "Automatic relation between a Document or Object to a Task or Workflow that are processing them"@en .
        emf:processedBy dcterms:description "Automatic relation between a Document or Object to a Task or Workflow that are processing them"@en .
        
        skos:inScheme rdfs:label "В схема"@bg, "In scheme"@en, "In schema"@de, "In scheme"@fi, "I systemplan"@da .
        skos:inScheme dcterms:title "В схема"@bg, "In scheme"@en, "In schema"@de, "In scheme"@fi, "I systemplan"@da .
        skos:inScheme skos:definition "Relates a resource (for example a concept) to a concept scheme in which it is included"@en .
        skos:inScheme dcterms:description "Relates a resource (for example a concept) to a concept scheme in which it is included"@en .
        
        skos:topConceptOf rdfs:label "Главна концепция на"@bg, "Top concept of"@en, "Top-konzept von"@de, "Top concept of"@fi, "Øvre koncept for"@da .
        skos:topConceptOf dcterms:title "Главна концепция на"@bg, "Top concept of"@en, "Top-konzept von"@de, "Top concept of"@fi, "Øvre koncept for"@da .
        skos:topConceptOf skos:definition "Top concept of"@en .
        skos:topConceptOf dcterms:description "Top concept of"@en .
        
        skos:related rdfs:label "Свързана с"@bg, "Related"@en, "Verbunden"@de, "Liittyvä"@fi, "Relaterede"@da .
        skos:related dcterms:title "Свързана с"@bg, "Related"@en, "Verbunden"@de, "Liittyvä"@fi, "Relaterede"@da .
        skos:related skos:definition "Related property is disjoint with Broader transitive property"@en .
        skos:related dcterms:description "Related property is disjoint with Broader transitive property"@en .
        
        skos:broaderTransitive rdfs:label "Broader transitive"@bg, "Broader transitive"@en, "Hat einen breiteren transitiv"@de, "Broader transitive"@fi, "Broader transitive"@da .
        skos:broaderTransitive dcterms:title "Broader transitive"@bg, "Broader transitive"@en, "Hat einen breiteren transitiv"@de, "Broader transitive"@fi, "Broader transitive"@da .
        skos:broaderTransitive skos:definition "Broader transitive property is a transitive superproperty of Broader property"@en .
        skos:broaderTransitive dcterms:description "Broader transitive property is a transitive superproperty of Broader property"@en .
        
        skos:broader rdfs:label "Broader"@bg, "Broader"@en, "Hat breiter"@de, "Broader"@fi, "Bredere"@da .
        skos:broader dcterms:title "Broader"@bg, "Broader"@en, "Hat breiter"@de, "Broader"@fi, "Bredere"@da .
        skos:broader skos:definition "Relates a concept to a concept that is more general in meaning"@en .
        skos:broader dcterms:description "Relates a concept to a concept that is more general in meaning"@en .
        
        skos:narrowerTransitive rdfs:label "Narrower transitive"@bg, "Narrower transitive"@en, "Hat einen breiteren transitiv"@de, "Narrower transitive"@fi, "Smallere transitiv"@da .
        skos:narrowerTransitive dcterms:title "Narrower transitive"@bg, "Narrower transitive"@en, "Hat einen breiteren transitiv"@de, "Narrower transitive"@fi, "Smallere transitiv"@da .
        skos:narrowerTransitive skos:definition "Narrower transitive property is a transitive superproperty of Narrower property"@en .
        skos:narrowerTransitive dcterms:description "Narrower transitive property is a transitive superproperty of Narrower property"@en .
        
        skos:narrower rdfs:label "Narrower"@bg, "Narrower"@en, "Hat schmaler"@de, "Narrower"@fi, "Smallere"@da .
        skos:narrower dcterms:title "Narrower"@bg, "Narrower"@en, "Hat schmaler"@de, "Narrower"@fi, "Smallere"@da .
        skos:narrower skos:definition "Relates a concept to a concept that is more specific in meaning"@en .
        skos:narrower dcterms:description "Relates a concept to a concept that is more specific in meaning"@en .
        
        skos:broadMatch rdfs:label "Broad match"@bg, "Broad match"@en, "Breites spiel"@de, "Broad match"@fi, "Bredere match"@da .
        skos:broadMatch dcterms:title "Broad match"@bg, "Broad match"@en, "Breites spiel"@de, "Broad match"@fi, "Bredere match"@da .
        skos:broadMatch skos:definition "Broad match is used to state a hierarchical mapping link between two conceptual resources in different concept schemes"@en .
        skos:broadMatch dcterms:description "Broad match is used to state a hierarchical mapping link between two conceptual resources in different concept schemes"@en .
        
        skos:narrowMatch rdfs:label "Narrow match"@bg, "Narrow match"@en, "Hat engere Übereinstimmung"@de, "Narrow match"@fi, "Smallere match"@da .
        skos:narrowMatch dcterms:title "Narrow match"@bg, "Narrow match"@en, "Hat engere Übereinstimmung"@de, "Narrow match"@fi, "Smallere match"@da .
        skos:narrowMatch skos:definition "Narrow match is used to state a hierarchical mapping link between two conceptual resources in different concept schemes"@en .
        skos:narrowMatch dcterms:description "Narrow match is used to state a hierarchical mapping link between two conceptual resources in different concept schemes"@en .
        
        skos:closeMatch rdfs:label "Close match"@bg, "Close match"@en, "Hat enge Übereinstimmung"@de, "Close match"@fi, "Nært match"@da .
        skos:closeMatch dcterms:title "Close match"@bg, "Close match"@en, "Hat enge Übereinstimmung"@de, "Close match"@fi, "Nært match"@da .
        skos:closeMatch skos:definition "Close match is used to link two concepts that are sufficiently similar that they can be used interchangeably in some information retrieval applications. In order to avoid the possibility of \"compound errors\" when combining mappings across more than two concept schemes, Close match is not declared to be a transitive property"@en .
        skos:closeMatch dcterms:description "Close match is used to link two concepts that are sufficiently similar that they can be used interchangeably in some information retrieval applications. In order to avoid the possibility of \"compound errors\" when combining mappings across more than two concept schemes, Close match is not declared to be a transitive property"@en .
        
        skos:exactMatch rdfs:label "Exact match"@bg, "Exact match"@en, "Hat genaue Übereinstimmung"@de, "Exact match"@fi, "Præcist match"@da .
        skos:exactMatch dcterms:title "Exact match"@bg, "Exact match"@en, "Hat genaue Übereinstimmung"@de, "Exact match"@fi, "Præcist match"@da .
        skos:exactMatch skos:definition "Exact match is used to link two concepts, indicating a high degree of confidence that the concepts can be used interchangeably across a wide range of information retrieval applications. Exact match is a transitive property, and is a sub-property of Close match"@en .
        skos:exactMatch dcterms:description "Exact match is used to link two concepts, indicating a high degree of confidence that the concepts can be used interchangeably across a wide range of information retrieval applications. Exact match is a transitive property, and is a sub-property of Close match"@en .
        
        skos:relatedMatch rdfs:label "Related match"@bg, "Related match"@en, "Hat ein ähnliches spiel"@de, "Related match"@fi, "Relateret match"@da .
        skos:relatedMatch dcterms:title "Related match"@bg, "Related match"@en, "Hat ein ähnliches spiel"@de, "Related match"@fi, "Relateret match"@da .
        skos:relatedMatch skos:definition "Related match is used to state an associative mapping link between two conceptual resources in different concept schemes"@en .
        skos:relatedMatch dcterms:description "Related match is used to state an associative mapping link between two conceptual resources in different concept schemes"@en .
        
        skos:example rdfs:label "Пример"@bg, "Example"@en, "Beispiel"@de, "Esimerkki"@fi, "Eksempel"@da .
        skos:example dcterms:title "Пример"@bg, "Example"@en, "Beispiel"@de, "Esimerkki"@fi, "Eksempel"@da .
        skos:example skos:definition "An example of the use of a concept"@en .
        skos:example dcterms:description "An example of the use of a concept"@en .
        
        skos:note rdfs:label "Бележка"@bg, "Note"@en, "Hinweis"@de, "Huomautus"@fi, "Bemærk"@da .
        skos:note dcterms:title "Бележка"@bg, "Note"@en, "Hinweis"@de, "Huomautus"@fi, "Bemærk"@da .
        skos:note skos:definition "A general note, for any purpose"@en .
        skos:note dcterms:description "A general note, for any purpose"@en .
        
        skos:notation rdfs:label "Нотация"@bg, "Notation"@en, "Notation"@de, "Merkintätapa"@fi, "Notation"@da .
        skos:notation dcterms:title "Нотация"@bg, "Notation"@en, "Notation"@de, "Merkintätapa"@fi, "Notation"@da .
        skos:notation skos:definition "Notation is used with a typed literal in the object position of the triple"@en .
        skos:notation dcterms:description "Notation is used with a typed literal in the object position of the triple"@en .
        
        skos:hiddenLabel rdfs:label "Скрит етикет"@bg, "Hidden label"@en, "Verstecktes etikett"@de, "Piilotettu tarra"@fi, "Skjult label"@da .
        skos:hiddenLabel dcterms:title "Скрит етикет"@bg, "Hidden label"@en, "Verstecktes etikett"@de, "Piilotettu tarra"@fi, "Skjult label"@da .
        skos:hiddenLabel skos:definition "Hidden label"@en .
        skos:hiddenLabel dcterms:description "Hidden label"@en .
        
        skos:prefLabel rdfs:label "Предпочитан етикет"@bg, "Preferred label"@en, "Bevorzugter aufkleber"@de, "Suositeltava tarra"@fi, "Foretrukken label"@da .
        skos:prefLabel dcterms:title "Предпочитан етикет"@bg, "Preferred label"@en, "Bevorzugter aufkleber"@de, "Suositeltava tarra"@fi, "Foretrukken label"@da .
        skos:prefLabel skos:definition "Preferred label"@en .
        skos:prefLabel dcterms:description "Preferred label"@en .
        
        skos:altLabel rdfs:label "Алтернативен етикет"@bg, "Alternative label"@en, "Alternatives etikett"@de, "Vaihtoehtoinen tarra"@fi, "Alternativ label"@da .
        skos:altLabel dcterms:title "Алтернативен етикет"@bg, "Alternative label"@en, "Alternatives etikett"@de, "Vaihtoehtoinen tarra"@fi, "Alternativ label"@da .
        skos:altLabel skos:definition "Alternative label"@en .
        skos:altLabel dcterms:description "Alternative label"@en .
        
        skos:hasTopConcept rdfs:label "Главна концепция"@bg, "Has top concept"@en, "Hat top-konzept"@de, "On top concept"@fi, "Har øvre koncept"@da .
        skos:hasTopConcept dcterms:title "Главна концепция"@bg, "Has top concept"@en, "Hat top-konzept"@de, "On top concept"@fi, "Har øvre koncept"@da .
        skos:hasTopConcept skos:definition "Relates, by convention, a concept scheme to a concept which is topmost in the broader/narrower concept hierarchies for that scheme, providing an entry point to these hierarchies"@en .
        skos:hasTopConcept dcterms:description "Relates, by convention, a concept scheme to a concept which is topmost in the broader/narrower concept hierarchies for that scheme, providing an entry point to these hierarchies"@en .
    }
} where {
    {
        ## titles only
        ?property rdfs:label ?label.
        optional {
            ?property dcterms:title ?title.
        }
        filter(?property in (emf:countryName, emf:phoneNumber, emf:mobileNumber, emf:uniqueId, emf:isMemberOfCollection, emf:isTopConcept, emf:associatedWith))
    } UNION {
        ## both
        ?property rdfs:label ?label.
        ?property skos:definition|rdfs:comment ?definition.
        optional {
            ?property dcterms:description ?description.
        }
        optional {
            ?property dcterms:title ?title.
        }
        filter(?property in (emf:mailboxAddress, ptop:firstName, ptop:lastName, emf:organizationName, dcterms:language, emf:isAssigneeOf, ptop:hasMember, skos:member, emf:processedBy, skos:inScheme, skos:topConceptOf, skos:related, skos:broaderTransitive, skos:broader, skos:narrowerTransitive, skos:narrower, skos:broadMatch, skos:narrowMatch, skos:closeMatch, skos:exactMatch, skos:relatedMatch, skos:example, skos:note, skos:notation, skos:hiddenLabel, skos:prefLabel, skos:altLabel, skos:hasTopConcept, emf:isPoolAssigneeTo, emf:isReporterOf))
    }
}