PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX oa: <http://www.w3.org/ns/oa#>
DELETE {
    emf:hasClient         rdfs:label "Onko asiakas"@fin .
    emf:hasSubsidiary     rdfs:label "Onko tytäryhtiö"@fin .
    emf:hasHead           rdfs:label "on Leader"@fin .
    emf:hasProducer       rdfs:label "Tuotannossa"@fin .
    emf:hasProvider       rdfs:label "Onko palveluntarjoaja"@fin .
    emf:isAuthorOf        rdfs:label "on kirjoittaja"@fin .
    emf:isClientOf        rdfs:label "Asiakkaalla"@fin .
    emf:isDeliveredTo     rdfs:label "Toimitetaan"@fin .
    emf:isEmployeeOf      rdfs:label "On työntekijällä"@fin .
    emf:isHeadOf          rdfs:label "Johtaja"@fin .
    emf:isIssuerOf        rdfs:label "IsIssuer Of"@fin .
    emf:isProducerOf      rdfs:label "Tuotannossa"@fin .
    emf:isProviderOf      rdfs:label "Onko palveluntarjoaja"@fin .
    emf:isRecipientOf     rdfs:label "Onko vastaanottaja"@fin .
    emf:isSubsidiaryOf    rdfs:label "On tytäryhtiö"@fin .
    emf:issuedBy          rdfs:label "Myöntänyt"@fin .
    emf:isContactPersonOf rdfs:label "Yhteyshenkilö"@fin .
    emf:hasAuthor         rdfs:label "on kirjoittaja"@fin .
    emf:hasDeliveredItem  rdfs:label "Onko toimitettu tuote"@fin .
    emf:hasEmployee       rdfs:label "on työntekijä"@fin .
}
INSERT {
    GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
            emf:hasClient         rdfs:label "Onko asiakas"@fi .
            emf:hasSubsidiary     rdfs:label "Onko tytäryhtiö"@fi .
            emf:hasHead           rdfs:label "on Leader"@fi .
            emf:hasProducer       rdfs:label "Tuotannossa"@fi .
            emf:hasProvider       rdfs:label "Onko palveluntarjoaja"@fi .
            emf:isAuthorOf        rdfs:label "on kirjoittaja"@fi .
            emf:isClientOf        rdfs:label "Asiakkaalla"@fi .
            emf:isDeliveredTo     rdfs:label "Toimitetaan"@fi .
            emf:isEmployeeOf      rdfs:label "On työntekijällä"@fi .
            emf:isHeadOf          rdfs:label "Johtaja"@fi .
            emf:isIssuerOf        rdfs:label "IsIssuer Of"@fi .
            emf:isProducerOf      rdfs:label "Tuotannossa"@fi .
            emf:isProviderOf      rdfs:label "Onko palveluntarjoaja"@fi .
            emf:isRecipientOf     rdfs:label "Onko vastaanottaja"@fi .
            emf:isSubsidiaryOf    rdfs:label "On tytäryhtiö"@fi .
            emf:issuedBy          rdfs:label "Myöntänyt"@fi .
            emf:isContactPersonOf rdfs:label "Yhteyshenkilö"@fi .
            emf:hasAuthor         rdfs:label "on kirjoittaja"@fi .
            emf:hasDeliveredItem  rdfs:label "Onko toimitettu tuote"@fi .
            emf:hasEmployee       rdfs:label "on työntekijä"@fi .
    }
} WHERE {
}