PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>


select distinct ?property ?description 
	where {
	?property a owl:DatatypeProperty .
	?property rdfs:comment|skos:definition ?comment .
	bind(if(contains(str(?property), "#"), STRAFTER(str(?property), "#"), if(contains(str(?property), "dc/terms"), replace(str(?property), "http://purl.org/dc/terms/", ""),replace(str(?property), "http://purl.org/dc/elements/1.1/", ""))) as ?label1) .
	filter ( contains(str(?property), ?ontology)) .
	bind(concat(
	"h2. Property ", ?label1, "\n",
	"\n",
	"Namespace: ", str(?property), "\n", 
	"h4. Description", "\n", 
	?comment, "\n") as ?description) .
} order by ?property