PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX ptop: <http://www.ontotext.com/proton/protontop#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE {
    emf:departmentName rdfs:domain emf:Case .
}
INSERT {
	GRAPH <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
		emf:departmentName rdfs:domain ptop:Entity .
	}
} WHERE {
    emf:departmentName rdfs:domain emf:Case
}