PREFIX emf: <http://ittruse.ittbg.com/ontology/enterpriseManagementFramework#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
DELETE { 
    emf:SavedFilter emf:isSearchable "true"^^xsd:boolean .
}
INSERT {
    GRAPH<http://ittruse.ittbg.com/ontology/enterpriseManagementFramework> {
        emf:SavedFilter emf:isSearchable "false"^^xsd:boolean .
    }
}
WHERE {
}